### ISSUE TITLE
The top-right of the MultiSelect component doesn't seem to close the box

### ISSUE THREAD

**Issue by ryshah** [carbon-design-system/carbon-components-react#1009]
## Detailed description

There is small dropdown arrow on MultiSelect component. It seems to open/close the MultiSelect component before any option is selected/unselected. 

After clicking inside dropdown to select an option, the top-right button seems to stop working. Clicking on that button while drop-down is closed will not close the box. 

## Steps to reproduce the issue

1. Go to `http://react.carbondesignsystem.com/?selectedKind=MultiSelect&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel`
2. Open/close the MultiSelect component by clicking on top-right button.
3. Open the component and select any option from MultiSelect. 
4. Clicking on top-right button doesn't close the box. To close the box one must click outside the MultiSelect component.

**Comment by k-nut** [comment]
We are also running in to this. It seems like the `handleOnStateChange` function is actually always called twice after a user selected a value in the `MultiSelect`. I added two `console.log`s and created a video to demonstrate this. You can see that at the beginning there is one `Setting isOpen to` log per click but after a selection there are two, where the second call is undoing the first one.

This is actually not limited to the icon on the right but applies to clicking anywhere in the `ListBox.Field`

![screen recording](https://thumbs.gfycat.com/LividChillyHoneybee-size_restricted.gif)
