### ISSUE TITLE
Table headers move on expansion

### ISSUE THREAD

**Issue by uridabomb** [carbon-design-system/carbon-components-react#1016]
## Detailed description

> **On expansion of a row, the table headers move.**

> Is this a feature request (new component, new icon), a bug, or a general issue? 
**A bug**

> Is this issue related to a specific component? **Table**

> What did you expect to happen? What happened instead? What would you like to see changed? **The table headers shouldn't move, of course :)**

> What browser are you working in? **Chrome**

> What version of the Carbon Design System are you using? **It's even in the Storybook...**

## Steps to reproduce the issue
In the [Storybook](http://react.carbondesignsystem.com/?selectedKind=Table&selectedStory=Nested%20Table&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel), click to expand Harry Potter. The headers move to the left.

## Additional information
Thanks!

**Comment by tw15egan** [comment]
This is the old version of DataTable. We advise you use the newer `DataTableV2` which has expansion without table headers shifting 😄 Here is a [link](http://react.carbondesignsystem.com/?selectedKind=DataTable&selectedStory=with%20expansion&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

Going to close this as we recommend using v2
