### ISSUE TITLE
Overflow throwing a warning in console

### ISSUE THREAD

**Issue by cknabe** [carbon-design-system/carbon-components-react#1030]
## Detailed description

> Describe in detail the issue you're having.
A warning shows up in the console when using OverflowMenu:
```
proxyConsole.js:72 Warning: Unknown event handler property `onOpen`. It will be ignored.
    in div (created by ClickListener)
    in ClickListener (created by OverflowMenu)
    in OverflowMenu (created by OverflowMenuTest)
    in OverflowMenuTest (created by App)
    in div (created by App)
    in App
```
Reproduced here:
https://codesandbox.io/s/4xz2rz7xl0

Found by davidyue

**Comment by emyarod** [comment]
Looks like the warning's being logged by `<ClickListener>`. This is caused by [frivolous usage of the spread operator](https://reactjs.org/warnings/unknown-prop.html)!
