### ISSUE TITLE
Button's icon didn't show will

### ISSUE THREAD

**Issue by Wenpei** [carbon-design-system/carbon-components-react#1032]
## Detailed description

> Describe in detail the issue you're having.
Button with icon 'add--solid' didn't show the icon.

> Is this a feature request (new component, new icon), a bug, or a general issue?
bug?

> Is this issue related to a specific component?
Button, Icon, 

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

https://codesandbox.io/s/y3kl75k9lv

## Additional information

* Screenshots or code
* Notes
 I didn't find a document say how to map Icon to carbon Icon http://www.carbondesignsystem.com/style/iconography/library

And search icon works fine. No idea why.

PS: When have lots Batch Action, should be wrapper to new line but no-wrapper currently. I guess it should be carbon-components issues?

**Comment by asudoh** [comment]
Hi @Wenpei thank you for trying to report an issue! You seems to be using `6.x` version of `carbon-icons`, [whose last release](https://github.com/carbon-design-system/carbon-icons/releases/tag/v6.1.0) was done in August last year. OTOH one of the icons you are using `icon--add--solid` is a new icon that was [introduced approximately a month ago](https://github.com/carbon-design-system/carbon-icons/pull/63). That said, you may want to try `7.x` version of `carbon-icons`. Feel free to reopen if it doesn’t resolve the issue. Thanks!
