### ISSUE TITLE
feat(TextInput): Add Show/hide password for password inputs

### ISSUE THREAD

**Issue by AndySeymour2904** [carbon-design-system/carbon-components-react#1033]
Similar to this;
![image](https://user-images.githubusercontent.com/36265276/41973224-411a0dcc-7a0c-11e8-8424-710e13845a2d.png)

Quite a common UX feature. My suggestion would be to put an 'eye' icon in the side like is done above with carbon-icons 'icon--visibility-on' and only show password whilst this button is pressed>

Also add a new prop to TextInput to allow user customisation for this feature.

Happy to put this in a PR once agreed

**Comment by asudoh** [comment]
@carbon-design-system/design Would this be something that we should maintain in core Carbon? Thanks!

**Comment by tay-aitken** [comment]
I actually made designs around this a while back but since its a pattern we decided not to introduce it into the system just yet. Something we will hopefully be doing in the future!

**Comment by AndySeymour2904** [comment]
@tay-aitken Is there a conversation or topic around why it was decided not to use this pattern?

As mentioned, I come to expect it of all user forms I use on the web nowadays.

**Comment by tw15egan** [comment]
I think it was just a lack of dev resources. @tay-aitken, do we still have designs for this? Seems like @AndySeymour2904 said he was willing to put this in a PR if we can align on a design

**Comment by tay-aitken** [comment]
It would sit in a PR for a while. We need to make a whole new patterns section on the site for this documentation. We currently only have components. It’s one we’ve been wanting to add but we haven’t had time to flesh out the new section.

**Comment by tw15egan** [comment]
I think if someone is willing to create it, we can at least add it to the repo as a variation and prioritize documentation. I don't think this is a sufficient reason to _not_ build a component, especially if someone is willing to build it for us

**Comment by tay-aitken** [comment]
I'm not saying we don't build, definitely think we should! I'm just saying we might not be able to surface it on the kit and website for a while. 

@AndySeymour2904 the only design requirements I have for it are:

- the `icon--visibility-off` and `icon--visibility-on` icons from the [carbon library](http://www.carbondesignsystem.com/style/iconography/library)are used
- the icons are 16px from the right side of the text input field
- that they follow our hover and active [guidelines for icons](http://www.carbondesignsystem.com/style/iconography/usage) > usage > visual usage > color

**Comment by tw15egan** [comment]
Okay awesome, just want to make sure we encourage contributions 😄

 @AndySeymour2904, since this will require style updates, it makes sense to start in the vanilla repo and create a variation there. Then we can consume the style updates here.

**Comment by tay-aitken** [comment]
Sorry if thats the impression I was giving . We love contributions!

**Comment by emyarod** [comment]
changes pending in this PR https://github.com/IBM/carbon-components-react/pull/1344 will be revisited after Carbon X release

**Comment by asudoh** [comment]
@emyarod Still interested in restarting #1344? Thanks!

**Comment by emyarod** [comment]
yes @asudoh, will open a PR now that the v10 release is more stable
