### ISSUE TITLE
Multiselect supports filtering but DropdownV2 does not

### ISSUE THREAD

**Issue by kglickman** [carbon-design-system/carbon-components-react#1039]
Dare I hope that this feature could be added fairly easily by re-using that code?

**Comment by joshblack** [comment]
Hi @kglickman! 👋 Would this not be a [ComboBox](http://react.carbondesignsystem.com/?selectedKind=ComboBox&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)?

**Comment by kglickman** [comment]
Doesn't a combo box let you add new items to the list?

**Comment by tw15egan** [comment]
`ComboBox` works just like a Dropdown, except that you can filter. We'd recommend using this component for your use-case

**Comment by kglickman** [comment]
@tw15egan Ok, thanks.  I would update your doc, though, to mention that.  That is not typically what a combo box is.  A cross-reference in the dropdown component doc would be useful, too.
