### ISSUE TITLE
Uncaught TypeError: m.default.createRef is not a function - Modal.js

### ISSUE THREAD

**Issue by snehag28** [carbon-design-system/carbon-components-react#1044]
"Uncaught TypeError: m.default.createRef is not a function" - Modal.js

I am using Modal component, and I get this error in my console "Uncaught TypeError: m.default.createRef is not a function". 
I tracked it down to https://github.com/carbon-design-system/carbon-components-react/blob/102f805f22b0ff8c296f9038bc84f947fb77fb85/src/components/Modal/Modal.js#L40
It fails to load the Modal component.
-->

## Detailed description

> Is this a feature request (new component, new icon), a bug, or a general issue?
A bug

> Is this issue related to a specific component?
Modal.js

> What browser are you working in?
Chrome, Firefox

> What version of the Carbon Design System are you using?
"carbon-components-react": "^6.5.0"

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
ICP for Data. July 12.

**Comment by asudoh** [comment]
@snehag28 A quick question - Any chance your app is using React15-?

**Comment by snehag28** [comment]
@asudoh Yes it is. We are planning to update it to React-16 in our next release.

**Comment by asudoh** [comment]
@snehag28 Great - `React.createRef()` is a new feature in React `16.x`. We stopped supporting React 15- since `9.0` release.

Feel free to reopen if there is still something we need to address here. Thanks!
