### ISSUE TITLE
The Tag Component should be added back

### ISSUE THREAD

**Issue by bellsworth13** [carbon-design-system/carbon-components-react#1046]
## Detailed description

The Tag component appears to have been removed from this repo and should be added back in since it is still included in the carbon design kit 
> Is this a feature request (new component, new icon), a bug, or a general issue?

Request to add the Tag component back

**Comment by tw15egan** [comment]
@carbon-design-system/design should the `tag` component still be in the main repos, or should they belong in the cloud addons?

**Comment by tay-aitken** [comment]
Tag should still be in the main repo :)

**Comment by tw15egan** [comment]
👍
