### ISSUE TITLE
Sometime after loading of page the popup of overflowmenu do not come up.

### ISSUE THREAD

**Issue by nidhiag** [carbon-design-system/carbon-components-react#105]
![overflow](https://user-images.githubusercontent.com/22441670/28309328-a50bdd7e-6bc6-11e7-9fb1-09496998deb5.png)
Hi , Overflow mwnu popup not coming up on click if i do wait for sometime on the page after load or do some scrolling.

**Comment by hellobrian** [comment]
Hey, not sure how to reproduce this issue. Make sure that you're using all the OverflowMenu components. Please refer to the [storybook](http://localhost:8080/?selectedKind=OverflowMenu&selectedStory=basic&full=0&down=1&left=1&panelRight=0&downPanel=jbovenschen%2Fstorybook-addon-a11y%2Faddon-panel):

![image](https://user-images.githubusercontent.com/4185382/28532839-a7b6b35c-7060-11e7-80ba-46b3b96c0e43.png)
