### ISSUE TITLE
Need a tooltip to indicate the reason of 'disabled' for Checkbox

### ISSUE THREAD

**Issue by lukewang2018** [carbon-design-system/carbon-components-react#1059]
## Need a tooltip to indicate the reason of 'disabled' for Checkbox

> Describe in detail the issue you're having.
When we disable the checkbox option, the cursor will be changed. **While user may not know why this checkbox is disabled.** We'd like to show a **tooltip** when hovering on the checkbox. 
Fox example, in a checkbox list, we want to disable (but show) some options, and we want to let user know why this option is disabled (may be filtered under some condition). 

> Is this a feature request (new component, new icon), a bug, or a general issue?
feature request

> Is this issue related to a specific component?
Checkbox

> What did you expect to happen? What happened instead? What would you like to see changed?
When we disable the checkbox option, the cursor (not-allowed) will be changed. While user may not know why this checkbox is disabled. We'd like to show a tooltip when hovering on the checkbox. 

> What browser are you working in?
Any

> What version of the Carbon Design System are you using?
"carbon-components-react": "^5.44.0",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Yes, we want this feature asap. 

## Additional information

* Screenshots or code
<img width="107" alt="checkbox" src="https://user-images.githubusercontent.com/40848250/42431109-fd01d796-8375-11e8-8c03-16ff77b1dd64.png">

* Notes

**Comment by asudoh** [comment]
@carbon-design-system/design I thought there may be one, but it totally slipped from mind - Did we have a guideline of this kind of use case? Thanks!

**Comment by aagonzales** [comment]
I don't believe `disabled` components can receive tooltips. The recommend design pattern would be to use an Inline Notification to explain to the user why an option is not-allowed. This is actually between than a Tooltip because a Tooltip actually hides this important information from the user. You've put the burden of discover-ability on the user at that point which is a gamble, what if they never hover over it? 

Can you please share this use-case in context? Why is the checkbox disabled in your scenario?

**Comment by lukewang2018** [comment]
@asudoh  @aagonzales  @tw15egan  thanks a lot for your comments!  

Here is the snapshot to explain the scenario, you can see that some checkbox items may be disabled due to various reasons (e.g. limitation). It's not good to show inline notification before the table header. And we want to show a tooltip to indicate the reason why we disable current item when hovering over it. Thanks.
![snip20180710_189](https://user-images.githubusercontent.com/40848250/42485393-0f0a5eea-842a-11e8-8895-33d51c15cbe2.png)

**Comment by asudoh** [comment]
Thanks @aagonzales, @tw15egan and @emyarod for jumping in! Hope @emyarod’s recent fix addresses @lukewang2018’ requirement.

**Comment by lukewang2018** [comment]
@aagonzales, @tw15egan and @emyarod @asudoh thanks a lot for your quick help! 

I just tested new Checkbox in v6.10.0, it's showing as below. I notice that there is overlap for the icon and tooltip, is there a way to adjust the tooltip location? Thanks!

![disabled-checkbox](https://user-images.githubusercontent.com/40848250/42550235-285486d0-8503-11e8-85b5-f073a3949f46.png)

**Comment by tw15egan** [comment]
This is the browser default behavior. If you move the cursor away but keep the pointer on the checkbox label, it will still appear and will not be blocked by the icon. 

![tooltip](https://user-images.githubusercontent.com/11928039/42580982-610126a8-84f1-11e8-9c82-93c18b5d7d26.gif)

**Comment by lukewang2018** [comment]
thanks @tw15egan . I just tested it again. the tooltip (title) is always moving with your mouse pointer  (icon) after some time.

**Comment by tw15egan** [comment]
This is the browser default behavior and we are unlikely to add any extra behavior to account for this
