### ISSUE TITLE
5.52.3: OverflowMenu: onPlace is never called for floating menus in React 15

### ISSUE THREAD

**Issue by chrisbygrave** [carbon-design-system/carbon-components-react#1066]
## Detailed description

FloatingMenu.js is responsible for calling onPlace on an OverflowMenu, which is necessary for the OverflowMenu to be able to determine if a mouse click is within or outside of it's own content, and hence decide whether or not it should close.

When using React 15, FloatingMenu goes down a different route (as hasCreatePortal is false). This results in _placeInProgress never being set to true, and as a consequence, the onPlace callback is never triggered.

Subsequently, any click within the floating menu closes the menu without being passed to the content of the menu.

## Workaround

Using React 16.x (i.e. a ReactDOM which provides createPortal) works fine.

**Comment by asudoh** [comment]
#1144 addresses this.
