### ISSUE TITLE
File Upload Button does not allow icons like other buttons.

### ISSUE THREAD

**Issue by iamgollum** [carbon-design-system/carbon-components-react#1071]
# FileUploaderButton

This button should support the following properties just like other buttons:

 ```
icon="search"
 iconDescription="Search"
```

**Comment by tw15egan** [comment]
@aagonzales, I don't see any usage guidelines around icons being used in the File Uploader Button. Should we allow this functionality?

**Comment by aagonzales** [comment]
The file uploader button should be used as-is. The prompt should only ever be "Add files".  
The action is to add a file not to search through files. The user would do the search within the system window that is triggered by the "Add file" button.

We can start a discussion around whether or not we should allow other prompts and icons however. What is your UI flow that would require a different prompt? And there by an icon? I could see something more like "upload file + icon" more so than search. From a system perspective I think we'd want to define a set of actions you that could be attached to file uploader.

**Comment by iamgollum** [comment]
@aagonzales 

The example text was from the documentation from the "Button" with "Search Icon" but the properties are applicable. As a result, I didn't mean to imply the functionality from the actaul value of the icons merely as defined in the Issue Title icon + file upload. My use case is multiple file section.

**Comment by aagonzales** [comment]
@iamgollum hi, not sure I understand what you're saying.

**Comment by asudoh** [comment]
Hi @iamgollum - The question from @aagonzales is solely from UX perspective - What is the use case and what is the user flow for adding icons? Great to hear - Thanks!

**Comment by itdove** [comment]
Hi, It would be nice to have that possibility, my uses case is:
I have a table and for each row, I need to possibility to upload a file.
Embedding a button is quite ugly and so if we can have an icon instead it would be nice... also the hoovertext would be great.

**Comment by aagonzales** [comment]
@itdove so you want to one for one swap out a button for an icon? And have the file added to a table? This file uploader is not built for adding files to a data-table. Those seem like two different pattern, correct? With Carbon missing a pattern for data table upload.

**Comment by itdove** [comment]
@aagonzales No, I want the button to be an clickable icon... The upload action will upload a file and call an API behind the scene to post it on the server side. The file will not be added as a data table.

**Comment by tw15egan** [comment]
The file uploader adds the content that was uploaded below the button so that a user can delete the file. This seems like a different use-case than our file uploader was built for

![image](https://user-images.githubusercontent.com/11928039/42698704-4f461380-8684-11e8-8a8f-747c0dd79fd2.png)

**Comment by tw15egan** [comment]
Seems like you could just use a Ghost Button with a `type="file"`

**Comment by itdove** [comment]
@aagonzales The button is showing the file name... @tw15egan  I use the FileUploaderButton not the FileUploader http://react.carbondesignsystem.com/?selectedKind=FileUploader&selectedStory=FileUploaderButton&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by asudoh** [comment]
Just to leave a technical not before this issue is closed - Technically @tw15egan is right that file uploader button merely is a label-input combination with small button styles - See https://github.com/carbon-design-system/carbon-components-react/blob/v7.1.0/src/components/FileUploader/FileUploader.js#L161-L193. Whether the UX the author desires fits well in Carbon design ecosystem is an interesting discussion. Feel free to re-open if anybody wants to continue the discussion.
