### ISSUE TITLE
Tooltip trigger text size is different to the label size of form controls, like Select, TextInput

### ISSUE THREAD

**Issue by ilovepumpkin** [carbon-design-system/carbon-components-react#115]
Now I need to create a Select control with label and a tooltip icon near the label. Since Select component does not support, so I wanted to use Tooltip together with Select (hide its own lable). But I found the font-size of "bx--tooltip__trigger" is 1rem, but font-size of "bx--label" is 0.875rem. So when I put this field with other normal fields with label, its label looks bigger. 

Can you change the font-size of "bx--tooltip__trigger" to 0.875rem? Or provide tooltip in form controls?

**Comment by tw15egan** [comment]
This seems like a common use case, and we should modify the `bx--form-item` to accept a tooltip as well as a label

**Comment by ilovepumpkin** [comment]
@tw15egan agree

**Comment by marijohannessen** [comment]
This is resolved in #314 .
