### ISSUE TITLE
Multiple select: can not get all the selected rows

### ISSUE THREAD

**Issue by zhuzmzm** [carbon-design-system/carbon-components-react#1155]
## Detailed description

> Describe in detail the issue you're having.

1. When i select multiple rows use TableSelectRow component one by one, how can i know how many rows and each row value i selected, as now i can only see the current  selected row. Thanks very much!
2. When i select one row, in the callback function, the parameter "isSelected" is false not true, is it an known issue?
![1](https://user-images.githubusercontent.com/42019585/43634097-cfcec4ba-973d-11e8-9292-77d7d5fee857.png)

> Is this a feature request (new component, new icon), a bug, or a general issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by joshblack** [comment]
Hi @zhuzmzm! 👋 Would `selectedRows` help in this case? https://github.com/IBM/carbon-components-react/blob/master/src/components/DataTable/README.md#state

**Comment by pinakidey** [comment]
Can somebody provide an example of appropriate usage of `selectedRows`?

```
<TableSelectAll {...getSelectionProps()} onSelect={() => { this.onDeploymentSelection(selectedRows) }} />
```

```
onDeploymentSelection(rows) {
		console.log(rows);
}
```

prints empty array, even after a row is selected.

```
[]
length: 0
<prototype>: Array []
```

**Comment by zhuzmzm** [comment]
@pinakidey Did you solve this issue?

**Comment by pinakidey** [comment]
`console.log(selectedRows)` inside `render()` will tell you which all rows are selected.

Usage:

```
render={({rows, headers, selectedRows, ...}) => { 

// select specific rows, as per the state, on render()
if (isEmpty(selectedRows) && !isEmpty(this.state.selectedDeployments)) {
this.state.selectedDeployments.forEach(item => selectRow(item.id));
}

// selectAll on render() by default, if state is empty										
if (isEmpty(selectedRows) && isEmpty(this.state.selectedDeployments) {
selectAll();
}

...
```

Make sure to use `shouldComponentUpdate()` to compare states to avoid infinite loop.
