### ISSUE TITLE
Label is not color highlighting when user is interacting with an input field

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-components-react#1173]
## Detailed description
According to our carbon components spec, the labels should highlight when the user has focused on an input field.  

I believe this was injected by the a11y fix.  I believe this fix injected the issue because the css no longer finds the label field since it's been reordered: https://github.com/IBM/carbon-components-react/commit/f02c1f9a7ecb92bb42028b34b8b95bb09ac2e425

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug
> Is this issue related to a specific component?

Select
> What did you expect to happen? What happened instead? What would you like to see changed?

expected label to highlight
> What browser are you working in?

Chrome
> What version of the Carbon Design System are you using?

6.18.4
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue
Simply interact with the Select widget in this storybook.  The label should be highlighted red as you interact.
http://react.carbondesignsystem.com/?selectedKind=Select&selectedStory=invalid&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by alisonjoseph** [comment]
Ah, this explains the reasoning why the label/input order was switched with v9. Will need to fix this in `carbon-components` also.

**Comment by asudoh** [comment]
Let's continue the discussion in carbon-design-system/carbon-components#1052 for now. Can re-open as needed.
