### ISSUE TITLE
[Enhancement] Add ability to pre-select rows in DataTable

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-components-react#1247]
Tried checking before making this to see if this was already an issue, but didn't see any ones specifically for creating the enhancement. The closest I could find was: #1088.

This issue is for discussion around adding in the ability to pre-select rows in the DataTable, and then for figuring out who can take on this feature and built it out in a PR 👍

**Comment by javadude24** [comment]
This was not an enhancement request, but a more details to explain how I can pre-set selected row. 

This is a write up on renderProps, but not sure how to implement.  I've tried setting isSelected in my base table data. But how does it get converted into the array called  'rowsById', which also has a isSelected attribute. However, the mystery is where this reduction of row data happen and why my isSelected does Not have an impact.

https://medium.com/carbondesign/data-table-updates-in-carbon-react-v5-22-0-6da0c24a96d6

**Comment by marklindsay24** [comment]
There is a very simple fix for this, allowing for raw data rows to have isSelected. In the normalize function, pull initial value from there.

![datatable-isselected](https://user-images.githubusercontent.com/42783294/44744053-27a85f00-aad2-11e8-8e92-497309dfab2f.png)


Please let me know if I can fix for team.

**Comment by joshblack** [comment]
Oh duh, thanks @javadude24!

**Comment by David-Yuen** [comment]
Just adding to the post: I had originally requested this feature on slack

**Comment by David-Yuen** [comment]
What kind of variable name do you want to be exposed externally?

Currently the PR is set using `isSelected`, which is what is used internally. 

From an external's perspective `row.isSelected` directly equals "is the row selected?", which should be answered with a boolean `true` or `false`. My opinion, besides the exposed external name having the same name as the internal name, `isSelected` is a straight-forward and valid API name and wouldn't cause any confusion for developers using it.

Josh raised that he wasn't comfortable with exposing internal variables, I agree but at the same time, that is not the intended pattern/format that will follow for all variables going forward. Some variables (used internally and externally) are generic or very basic for the reason of understanding, and I think the most important thing is the variable name is straight forward and self-describes the purpose within the given scope (such as internally or externally). So I personally don't think it is an issue in this case to having it called `isSelected`. 

Otherwise, the other options I can think of is `selected` or `checked` but to me, doesn't feel as strong as `isSelected` or `isChecked` because adding `is` is asking yes or no. 
Also, the subcomponents are all using 'Select', such as `TableSelectRow` `selectedRows` `with selection`, so I think `isSelected` makes more sense than `isChecked`.

**Comment by joshblack** [comment]
@David-Yuen I agree on the name, but not on the placement in the rows themselves. For example, how would we handle the situation where someone has a value on each row called `isSelected` that they would want shown in the table under a `selected` header, in addition to having that row initially selected.

**Comment by David-Yuen** [comment]
I understand what you're saying,

In my opinion, a Table using TableSelectRow, which adds in a column of checkboxes that can be selected or unselected), makes sense to be that a row with isSelected directly refers to that column. This column with checkboxes is the same as having a `selected` header. 

If someone was wanting to display content that had an internal meaning of `selected`.. 
For example, it is a list of songs to play or download, and selected means something like, it is already selected by another user. 
It would look like
<NoHeader> | Name | Selected
[ ] | Song1 | yes
[checked] | Song2 | no

That kind of design wouldn't really make sense. I don't know how to make a proper example of this, but if someone had a generic header like `selected`, it would be very confusing to the checkboxes (TableSelectRow) column..
Trying to say is, having a generic `selected` header column in a component that has a column to allow the user to select/unselect, should be the same thing, not separate. I would imagine if there was a "selected" internal meaning, the header/variable names would be alot more descriptive.

Or another way of saying the above: When a user displaying a table of data and they want to use TableSelectRow, this column with variable `isSelected` should be built into their rows anyways. 

In my opinion, having the built-in `selected` column (using `isSelected`) still seems valid to me, and no different from how row reserves `id` and headers reserve `key` and `header`.
This is my opinon and I'm going to leave it at this.

If you have other suggestion or better idea, go ahead and please implement it.

**Comment by joshblack** [comment]
@David-Yuen thanks for taking the time to write this up! Definitely understand that this might not make any sense design-wise, however that doesn't mean that this situation cannot exist. We also need to be aware that this would set a precedent for all state-related bits being able to be set in the `row` prop data structure. This opens us up to potentially more situations like this with a key conflict that we cannot predict.

Ultimately, if this is the best way to tackle the problem than that is fine as long as we can provide an escape hatch for folks that might need to circumvent the keys that we use.

The simplest suggestion here would most likely be an `initialSelectedRows` prop that took in the array of ids for the rows that one would want initially selected. This way folks could pass their data in and not have to worry about tying in state-related logic to their data. This would also prevent any key collision in the `rows` data structure and would explicitly call out the state information that should be defined for the first render.

**Comment by asudoh** [comment]
Weighing in - Are people interested in having a new prop, which is a function taking row data and returning if the row is selected or not? Thanks!

**Comment by joshblack** [comment]
@asudoh definitely would be a good one, almost like a selector in Redux?

**Comment by asudoh** [comment]
@joshblack The approach of Redux selector seems a good choice. Whether it should take all rows (to return the entire list of selected rows) or it should be per-row approach would be a good discussion, too.

**Comment by joshblack** [comment]
@asudoh just curious, what do you the approach adds versus the `initial*` convention that seems typical for initializing state values?

**Comment by asudoh** [comment]
@joshblack Basically to support the scenario of #823. Another (minor) reason is removing a step for consumers wrt filtering/selecting to generate `initial*`. Anyhow, I was seeking for a way for @David-Yuen and you can agree on. Thanks!

**Comment by marklindsay24** [comment]
@asudoh Absolutely I would like to see this enhancements. In my opinion, using a name like 'initial*' implies this only applies for initializing the section. However, we also need such attribute to reflect the current state of row. Right?

**Comment by joshblack** [comment]
@marklindsay24 for sure! `selectedRows` is available through the `render` prop for this use-case 👍

**Comment by joshblack** [comment]
> Another (minor) reason is removing a step for consumers wrt filtering/selecting to generate initial*

Wouldn't the consumer have to do this in the supplied method, as well? For example:

```jsx
<DataTable getSelectedRows={myGetSelectedRows} ... />

function myGetSelectedRows(rows, props, state) {
  return rows.filter(row => /* ... */);
}
```

I could easily be misunderstanding, though, so let me know!

**Comment by joshblack** [comment]
Gotcha. This is kind of looking forward then when handling slices of data versus having the data all up front?

**Comment by joshblack** [comment]
Yupp! For sure 😄

**Comment by GabrieleBarboni** [comment]
Hi all,
is there currently a way to pre-select rows in DataTable?

**Comment by marklindsay24** [comment]
What is the status of this?
