### ISSUE TITLE
DetailPageHeader depends on function names and renders incorrectly when minified

### ISSUE THREAD

**Issue by nfriedly** [carbon-design-system/carbon-components-react#136]
The `DetailPageHeader` checks the `child.type.name` to identify breadcrumbs and tabs and such. I believe this value comes from [`Function.name`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name) which will be `Breadcrumb` or `Tabs` or whatever when not minified, but they become 1-letter names when minified, which `DetailPageHeader` then cannot identify.

I'm not sure what the best fix is for this; `Function.name` is read-only, but I'm going to try playing with the `displayName` and/or doing an `instanceof` check and send a PR if I find a working solution.

Alternatively, they could just become named params, although that could break existing code unless it accepted either. Ditto for switching them to named exports. Any opinions on either of those options?

**Comment by chrisdhanaraj** [comment]
I think another solution is actually to use the component itself when referencing it - see what the InteriorLeftNav component does

https://github.com/carbon-design-system/carbon-components-react/blob/master/components/InteriorLeftNav.js#L47

So you're not referring to a name, but the actual type itself. Going to do a quick test to verify, but this might be a more clean solution

**Comment by chrisdhanaraj** [comment]
@nfriedly - yep just tested and that seems to work fine; I'll open a PR for this that corresponds to yours

**Comment by nfriedly** [comment]
Oh, ok, yea, I like that version better.
