### ISSUE TITLE
Tooltip Component: Cursor turns to a pointer on the text instead of the icon

### ISSUE THREAD

**Issue by tonydiaz** [carbon-design-system/carbon-components-react#1366]
## Detailed description

> Describe in detail the issue you're having.

On the tooltip component when you hover over the text the cursor turns into a pointer making it look like their is something to click but there isn't

> Is this issue related to a specific component?

Tooltip

> What did you expect to happen? What happened instead? What would you like to see changed?

I don't expect the cursor to change to a pointer when hovering over the text

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

v6.14.2

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Watson Assistant. Already released in production would like it fixed. 

## Steps to reproduce the issue

1. Move mouse over the text of the tooltip 
2. View the cursor change to a pointer making it look like you could click on the text.  

![example](https://user-images.githubusercontent.com/7145340/46118977-fdcc8000-c1d6-11e8-94c4-3144a983d490.gif)

> Please create a reduced test case in code sandbox
> http://react.carbondesignsystem.com/?knob-The%20title%20%28title%29=Section%201%20title&knob-Tooltip%20direction%20%28direction%29=bottom&knob-Trigger%20text%20%28triggerText%29=Tooltip%20label&selectedKind=Tooltip&selectedStory=default%20%28bottom%29&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

## Additional information

* N/A

**Comment by asudoh** [comment]
Thanks @tonydiaz for reporting! I see the React variant's markup is not in-line with vanilla one, but marking the alignment will be a breaking change. Meanwhile, you can add your custom class to the trigger text/icon via `triggerClasses` prop and make the adjustments.

**Comment by asudoh** [comment]
`v10` markup seems to have solved this issue.
