### ISSUE TITLE
Character counter in TextInput

### ISSUE THREAD

**Issue by sibendudey** [carbon-design-system/carbon-components-react#1395]
Use this template if you want to request a new feature, or a change to an existing feature.

If you are reporting a bug or problem, please use the bug template instead.

### Summary

A character counter could be displayed to the bottom right side of the text field which reflect the number of allowed characters in the field.

### Justification

This is a requirement in our project from the UX side. Earlier we made use of ap-components which has this character counter similar to the one in the pic.

<img width="1400" alt="screen shot 2018-10-02 at 2 48 16 pm" src="https://user-images.githubusercontent.com/4667493/46491526-f7db2e00-c7d8-11e8-8b88-0d6e7354cc8b.png">  

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an upcoming release?
Yes, It is related to an upcoming release.  November.

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! We'll see if there is a bigger interest in team/consumers in this area. Meanwhile, you may want to use `onChange()` prop in our `<TextInput>` so you can create your own counter UI and update it.

**Comment by asudoh** [comment]
Let's track the effort in carbon-design-system/carbon-components#1672 for now.
