### ISSUE TITLE
Bug when programmatically changing values for MultiSelect.Filterable and ComboBox

### ISSUE THREAD

**Issue by polgas16** [carbon-design-system/carbon-components-react#1400]
## Detailed description
MultiSelect.Filterable and ComboBox initial values and onChange values are correctly shown in the component but when changing values programmatically, the changes are not rendered correctly and seems to be stuck with the previous values for it (MultiSelect); seems to have been rendered correctly but the underlying value is still the previous one (ComboBox).  

> Is this issue related to a specific component?
MultiSelect, ComboBox

> What did you expect to happen? What happened instead? What would you like to see changed?
Programmatically changing values should be reflected correctly in component.

> What browser are you working in?
Chrome Version 69.0.3497.100 (Official Build) (64-bit)

> What version of the Carbon Design System are you using?
    "carbon-components": "^9.12.2",
    "carbon-components-react": "^6.28.2",
    "carbon-icons": "^7.0.6",

> Please create a reduced test case in code sandbox
https://codesandbox.io/s/l796pl76l9

* Notes
For ComboBox - clicking on the buttons seems to work correctly but try clicking on the combobox itself and click anywhere outside of it without clicking the 'clear selected item' button.

I think the issue is with the internal Selection class

**Comment by asudoh** [comment]
Just to leave a note before being closed - The team's current consensus in this topic is that application should use our presentational components to project application's state. Ones for combo box are `<ListBox*>` found at: https://github.com/carbon-design-system/carbon-components-react/blob/v7.1.0/src/components/ComboBox/ComboBox.js#L258-L312
