### ISSUE TITLE
DatePicker component renders with red outline in Mozilla

### ISSUE THREAD

**Issue by ryshah** [carbon-design-system/carbon-components-react#141]
Component renders fine in Chrome. In Mozilla it seems to be broken. There are bunch of errors in console related to CSS parsing which could be causing the behavior.

<img width="797" alt="screen shot 2017-07-27 at 8 20 40 am" src="https://user-images.githubusercontent.com/13667662/28672249-d79c29f8-72a4-11e7-9a5d-2a57c8da1b53.png">

**Comment by iangfleming** [comment]
@ryshah looks like it renders fine for me in mozilla. Are you sure it's not related to your build? also what browser and components versions are you using?

**Comment by ryshah** [comment]
@iangfleming I can see the issue in storybook as well. Version information

<img width="644" alt="screen shot 2017-07-27 at 10 38 11 am" src="https://user-images.githubusercontent.com/13667662/28679105-c6f4fb8a-72b7-11e7-9632-cd76c39dcb3d.png">

**Comment by iangfleming** [comment]
@ryshah interesting! this only in ESR btw. other Firefox's work fine. Also, it seems to only be a bug with the React version. I don't think it has to do with the CSS errors but it's certainly strange. Our sprint ends tomorrow so we can look into this next week. Thanks for reporting it!

**Comment by galtenberg** [comment]
I don't use ESR and issue still happens...

<img width="758" alt="screenshot 2017-08-23 11 11 14" src="https://user-images.githubusercontent.com/97950/29631450-8196ba18-87f4-11e7-8c04-c97fe941c8bb.png">

**Comment by joshblack** [comment]
I'm going to consolidate this issue along with the other related ones a single implementation task in #304 so that we can tackle them at the same time 😄 

If you have any questions or concerns, feel free to reply on GitHub or in the #carbon-react channel on Slack! In addition, if you believe I'm closing this issue erroneously feel free to re-open with the rationale.

Have a great day!
