### ISSUE TITLE
Question: ToolbarItem with "type=search" onChange"

### ISSUE THREAD

**Issue by dcostantino** [carbon-design-system/carbon-components-react#142]
I am trying to filter a table based on text input in the tooltip item search but not sure how to get input changes, onChange is not invoked. I can add <Search> and have an onChange invoked,  but it does not have the same experience as the TooltipItem search.

**Comment by chrisdhanaraj** [comment]
Yeah looks like that's a bug with this - I'll make a fix for this

**Comment by joshblack** [comment]
Hi there! 👋 

Just to understand the use-case better, is the ask to support an `onClick` handler on the `ToolbarItem` component?

**Comment by marijohannessen** [comment]
Closing this issue due to lack of response from issue creator. Please feel free to re-open if needed.
