### ISSUE TITLE
Question: Date Picker component with Range type is not firing the onChange handler

### ISSUE THREAD

**Issue by swiftfoot** [carbon-design-system/carbon-components-react#143]
If I define a Date Picker component of range type and register an onChange handler, the onChange handler isn't fired if I select the range using the Calendar, only if I type directly in the field.  How am I supposed to capture the start and end date range from this widget in a react-like way, I can go grab from the document id, but I'd really prefer not to? snippet below.  onChange never fires if you pick the range using the UI selector

```
            <DatePicker id="date-picker" datePickerType="range">
              <DatePickerInput
                labelText="Start date"
                placeholder="mm/dd/yyyy"
                onClick={() => console.log('clicked')}
                onChange={() => console.log('startDateChanged')}
                id="date-picker-input-id"
              />
              <DatePickerInput
                labelText="End date"
                placeholder="mm/dd/yyyy"
                onClick={() => console.log('clicked')}
                onChange={() => console.log('endDateChanged')}
                id="date-picker-id-2"
              />
            </DatePicker>
```

More strangeness here, when I edit the dates, if I click on the start field, the calendar shows the end date, not the start date.  I would expect the opposite.    Frankly I would prefer to not pop the underlying calendar interface for ranges unless it's specifically requested by clicking the calendar icon.

Also if I am in the first field and I type a date, and press tab, instead of accepting the date and tabbing me to the end date field, it clears the start date field and shows the calendar underneath approximately in the time range that I typed.  How can I get to the end date field using the tab key.  Thanks!

**Comment by marijohannessen** [comment]
Hi @swiftfoot , thanks for pointing this out. I'll take a look tomorrow and keep you updated!

**Comment by marijohannessen** [comment]
So I'm able to reproduce all the bugs you discovered and I'll try to fix most of it this week - however, I'm not completely sure how long it is going to take yet. I also noticed that `flatpickr` has released a new version of the range calendar that supports two input fields, so I am also going to update this and I hope that this will fix a lot of the issues. I'll keep you updated on the progress, thanks!

**Comment by riya-naico** [comment]
While developing the react app with carbon-components, we faced some issues when we  dynamically add date picker. We resolved issue by using package 'carbon-components-react'.

 Do we need to use package 'carbon-components-react' instead of 'carbon-components'.? What is the standard procedure using carbon design in react?

**Comment by asudoh** [comment]
Hi 👋 if you are using Carbon in a React app, you'd use `carbon-components-react`. Was that your question?

**Comment by riya-naico** [comment]
yes.  so we must carbon-components-react in react
