### ISSUE TITLE
webpack fails with latest carbon components and 5.x carbon icons

### ISSUE THREAD

**Issue by swiftfoot** [carbon-design-system/carbon-components-react#144]
To reproduce, use carbon components in a webpack environment

ERROR in ./~/carbon-icons/dist/carbon-icons.js
Module build failed: Error: ENOENT: no such file or directory, open '/Users/scottsd/Documents/scs-alliance-ui/node_modules/carbon-icons/dist/carbon-icons.js'
 @ ./~/carbon-components-react/cjs/components/Icon.js 23:19-42

 "carbon-components": "^7.17.0",
    "carbon-components-react": "^3.5.9",
    "carbon-icons": "^5.0.6",

**Comment by hellobrian** [comment]
Is this issue still a problem? 
If so, can you copy your `webpack.config.js`?

**Comment by swiftfoot** [comment]
Yes and it's strangely intermittent, here's my webpack.config.js

`// webpack.config.js
const webpack = require('webpack');
const path = require('path');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  entry: path.join(__dirname, 'src'),
  output: {
    path: path.join(__dirname, 'src', 'static'),
    filename: 'js/bundle.js',
  },
  eslint: {
    failOnWarning: false,
    failOnError: false
  },
  plugins: [
    new ExtractTextPlugin('css/bundle.css'),
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
    })
  ],
  module: {
    preLoaders: [
      // Javascript
      { test: /\.js?$/, loader: 'eslint', exclude: /node_modules/ }
    ],
    loaders: [
      {
        test: /\.js/,
        exclude: /(node_modules)/,
        loader: 'babel-loader'
      },
      {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract('css'),
      },
      {
        test: /\.json$/,
        loader: 'json'
      },
    ],
  },
  devtool: 'source-map',
};

if (process.env.NODE_ENV === 'production') {
  module.exports.plugins.push(
    new webpack.optimize.UglifyJsPlugin({
      compress: { warnings: false },
      mangle: true,
      sourcemap: false,
      beautify: false,
      dead_code: true,
    })
  )
}

`

**Comment by joshblack** [comment]
Is there a chance to create a simple repro project that we could use to debug this?

**Comment by swiftfoot** [comment]
I'm not sure why but this has stopped occurring with the latest version of carbon components so we can close

Sent from my iPhone

On Oct 6, 2017, at 2:35 AM, Josh Black <notifications@github.com<mailto:notifications@github.com>> wrote:


Is there a chance to create a simple repro project that we could use to debug this?

**Comment by joshblack** [comment]
Sounds good! Feel free to re-open an issue if you find it coming back 😄
