### ISSUE TITLE
Enhancement: Is there a property for these input components to set them required?

### ISSUE THREAD

**Issue by swiftfoot** [carbon-design-system/carbon-components-react#145]
Can I set a props value on these input components to show them as required?

I can't seem to find a way, specifically I'm looking to conditionally set the DatePickerInput required

**Comment by chrisdhanaraj** [comment]
The input elements let you pass in props as need be - for example, you can pass the required prop like so

`<TextInput required>` and it'll go through

Same with DatePicker

<DatePicker id="date-picker" datePickerType="single">
<DatePickerInput
  className="some-class"
  labelText="Select a date"
  onClick=onClick()
  onChange=onChange()
  placeholder="mm/dd/yyyy"
  id="date-picker-input-id"
  **required**
/>
</DatePicker>

**Comment by swiftfoot** [comment]
There doesn't seem to be any visual indicator that these are required fields, any plans in the future?  Thanks!

**Comment by hellobrian** [comment]
It looks like we use validation styles instead. 

You can add `data-invalid` to apply validation styles on an `input` to indicate that a required field should be filled in.

![image](https://user-images.githubusercontent.com/4185382/28695308-f7e9cb08-72f3-11e7-8dc1-0eb80047c95c.png)

Or if a password needs to match a certain pattern, the same kind of style gets used but with different messaging. 

![image](https://user-images.githubusercontent.com/4185382/28695179-5495425c-72f3-11e7-990e-0dada742e0bb.png)

**Source: [Form Usage - carbondesignsystem.com](http://carbondesignsystem.com/components/form/usage)**
