### ISSUE TITLE
Accessibility: FileUploaderButton can't be accessed via keyboard.

### ISSUE THREAD

**Issue by sheila1227** [carbon-design-system/carbon-components-react#146]
The "Add files" button inside FileUploader component can't be focused via keyboard and doesn't allow user to press enter or space key on it to pop up the file broswer dialog.
<img width="365" alt="screen shot 2017-07-28 at 10 34 01 am" src="https://user-images.githubusercontent.com/9313197/28700276-4399e08c-7381-11e7-88e1-5ff61191f013.png">

Also, when user selects multiple files, the delete icon can't be accessed via keyboard either.
<img width="354" alt="screen shot 2017-07-28 at 10 42 33 am" src="https://user-images.githubusercontent.com/9313197/28700343-c779a2de-7381-11e7-89e1-d80d4900394d.png">

**Comment by hellobrian** [comment]
Fix on the way!
