### ISSUE TITLE
Pass inputref to internal ref in Checkbox and other control element components

### ISSUE THREAD

**Issue by ColbyJohnIBM** [carbon-design-system/carbon-components-react#1463]
### Summary

The `Button` component passes the `inputref` property down to its internal `button` element.
(See here: https://github.com/IBM/carbon-components-react/blob/master/src/components/Button/Button.js#L51)
This allows users to send in a ref and then use it (for focusing, etc.).

It would be useful if other control elements also did the same thing. (The component that we're currently working with is `Checkbox`, but ideally this gets added everywhere applicable.)

### Justification

We'd like to be able to programmatically focus on these control elements within Watson Compare & Comply Tooling UI.

### Specific timeline issues / requests

As soon as possible, these changes are related to our going GA (accessibility).

**Comment by asudoh** [comment]
Hi @ColbyJohnIBM thank you for reporting! Do you want to send us a PR? If so, great if React latest ref API can be used there. If not, you may want to do your own checkbox implementation for now, given your presumable time constraints.

**Comment by silesky** [comment]
This is related to #1768

**Comment by ColbyJohnIBM** [comment]
Does it really make sense to close "stale" issues? Won't that just hide issues that should be eventually fixed?

I'm fine if a person on the dev team decides that this issue (or any issue) is not worth the effort to fix, but it doesn't seem like the default case should be to close an issue just because no one has addressed it in a while.

**Comment by asudoh** [comment]
Addressed by #1859. @ColbyJohnIBM The stalebot thing is similar to other stalebots out there, closing ones with inactivity. As you may have noticed, adding an activity to the issue prevents the issue from being closed. Even if it's closed, a new issue can be created for continued discussion. But good to continue the discussion, probably at #2289 or a new issue.
