### ISSUE TITLE
Floating point issue in NumberInput

### ISSUE THREAD

**Issue by christek** [carbon-design-system/carbon-components-react#1471]
## Floating point issue in NumberInput

Entering 16.67 into NumberInput, then clicking decrement displays 6.670000000000002 (Chrome) 

## Steps to reproduce the issue

1. Go to https://pages.github.ibm.com/cloud-integration-design/ap-carbon-theme/?selectedKind=Accordion&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
2. Choose NumberInput
3. manually enter 16.67
4. click down arrow/decrement
5. NumberInput displays 6.670000000000002

Even though this is how plain JS has floating point issues, this is not what user would expect. Maybe a math library would fix the issue.
https://github.com/IBM/carbon-components-react/issues/new?template=bug-report.md

**Comment by alisonjoseph** [comment]
Also seeing this behavior in our vanilla library (https://github.com/IBM/carbon-components/issues/1313)

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! Though having a way to specify the precision may be an option, it'd be great if apps can seek for user-land solution first - Which is, hooking `onChange`, get the new value from `evt.imaginaryTarget` and set the adjusted value back to the `value` prop. Hope it makes sense!

**Comment by dakahn** [comment]
Closing this one out as solved -- happy to reopen if that's not the case 🏄
