### ISSUE TITLE
Inline Notification title doesn't vertically align with subtitle.

### ISSUE THREAD

**Issue by swiftfoot** [carbon-design-system/carbon-components-react#149]
To see an example visually of this, take a look at this codesandbox:

https://codesandbox.io/s/Oyy533qGR

I locally fixed with this: 
.bx--inline-notification__title {
  line-height: inherit !important;
}

**Comment by hellobrian** [comment]
I'm actually seeing the opposite of what you're seeing.
In both codesandbox and react storybook, the inline notification as-is looks fine.

![image](https://user-images.githubusercontent.com/4185382/28797098-b1183cea-7605-11e7-8053-f56f42925141.png)

But when I add your styles, then the title and subtitles are not vertically aligned:

```css
.bx--inline-notification__title {
  line-height: inherit !important;
}
```

![image](https://user-images.githubusercontent.com/4185382/28797127-d19ed898-7605-11e7-8864-b0b1e2268bb3.png)

There might be something else going on with your code that's causing this side effect.
I'm going to close this issue for now but let me know if you find out any other ways I can replicate what you're seeing.
