### ISSUE TITLE
Style: Overflowmenu focus outline is drawn consistently between firefox and chrome

### ISSUE THREAD

**Issue by sheila1227** [carbon-design-system/carbon-components-react#155]
This issue happens with [OverflowMenu component](http://react.carbondesignsystem.com/?selectedKind=OverflowMenu&selectedStory=basic&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel)
When click on the menu icon, in chrome, outline is drawn correctly around the icon.

<img width="938" alt="screen shot 2017-08-02 at 2 42 58 pm" src="https://user-images.githubusercontent.com/9313197/28861085-e469dae4-7791-11e7-8192-863247e89505.png">

However in firefox, the outline is drawn around the whole component extent rectangle.

<img width="747" alt="screen shot 2017-08-02 at 2 39 50 pm" src="https://user-images.githubusercontent.com/9313197/28861150-298c488c-7792-11e7-8010-fc4c7bce7b83.png">

**Comment by hellobrian** [comment]
Use `floatingMenu` props on the component ([see example](http://localhost:8080/?selectedKind=OverflowMenu&selectedStory=floating%20menu&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel))
