### ISSUE TITLE
Performance issue on PaginationV2 when totalItems number goes large

### ISSUE THREAD

**Issue by codeYuyuan** [carbon-design-system/carbon-components-react#1574]
## Detailed description

> Describe in detail the issue you're having.

The use case is when the `totalItems` gets set to 1 million, the whole pagination will take extremely long time to render(even make browser crash). 

> Is this issue related to a specific component?

PaginationV2
 

> What browser are you working in?

Chrome&firefox

> What version of the Carbon Design System are you using?

6.46.6

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Voice agent with watson, this issue is blocking our load testing. We rolled back to use PaginationV1 to avoid this issue but hope this bug could fixed asap.

## Steps to reproduce the issue

> Please create a reduced test case in code sandbox

https://codesandbox.io/s/j3m1w01p9
The sandbox example sets totalItems to 100000, which already has bad performance now. 

## Additional information

* Screenshots or code
In the source code, it looks like there is a function to render the selectItem  which causes this issue
```renderSelectItems = total => {
    let counter = 1;
    let itemArr = [];
    while (counter <= total) {
      itemArr.push(
        <SelectItem key={counter} value={counter} text={String(counter)} />
      );
      counter++;
    }
    return itemArr;
  };
```

**Comment by codeYuyuan** [comment]
Hi @asudoh, yeah once I rolled back to pagination V1 where it just specify a page number without displaying all page number selection items, it works for my case.

**Comment by kdegrace** [comment]
We also ran into this issue.  We are using PaginationV1 and were prompted to use PaginationV2 in the browser console.  We have a table that can contain millions of items (that we lazy load one page at a time), and it locks up the browser trying to populate that page select element.

**Comment by asudoh** [comment]
Turned out `pagesUnknown` introduced in #116 addresses this problem.
