### ISSUE TITLE
Fix Button Styling

### ISSUE THREAD

**Issue by jzhang300** [carbon-design-system/carbon-components-react#16]
**Context:**

![screen shot 2017-06-12 at 11 31 11 am](https://user-images.githubusercontent.com/1449523/27044373-f20cad68-4f62-11e7-9d5a-1bcbfa7898eb.jpg)

![screen shot 2017-06-12 at 11 36 04 am](https://user-images.githubusercontent.com/1449523/27044492-58a6be56-4f63-11e7-9ee5-e666089526c0.jpg)

---
**Acceptance Criteria:**
- [ ] make `.bx--btn--secondary` be transparent.

**Comment by tw15egan** [comment]
Seems like this might be an older version of the components. `bx--global-light-ui` was phased out in v7, and here is the current source for `bx--btn--secondary`: 

![screen shot 2017-06-12 at 11 43 12 am](https://user-images.githubusercontent.com/11928039/27044776-676f5500-4f64-11e7-9b33-00ca9e018b6b.png)

**Comment by jzhang300** [comment]
@tw15egan ah I see, it started working when I disabled `bx--global-light-ui`.  I think it's still good to set the background-color here anyways for robustness.

**Comment by hellobrian** [comment]
Closing since the `background-color` is set to `transparent` on `.bx--btn--secondary`.
