### ISSUE TITLE
Table always has a x-scrollbar

### ISSUE THREAD

**Issue by lilyclyc** [carbon-design-system/carbon-components-react#161]
![image](https://user-images.githubusercontent.com/30255650/28913787-d4760330-786b-11e7-86bd-50ec38385321.png)
I think it should be width as 100% for the table container

**Comment by hellobrian** [comment]
This is because of react storybook, which is adding a decorator with a fixed width container forcing the x scrollbar. When you use Table, then you'll see it's not there. For example: https://codesandbox.io/s/g52NW01mZ

**Comment by lilyclyc** [comment]
@hellobrian -- 'bx--responsive-table-container' width is 99.9%, but 'bx--pagination' width is 100%. Actually it causes the layout alignment issue.

**Comment by hellobrian** [comment]
So are we talking about a new issue now? 

If so...create a new issue. 

But if you're implying that the 99% width is causing the x-scrollbar to be visible, I will have to disagree with you.

**Comment by lilyclyc** [comment]
OK, I will open a new issue
