### ISSUE TITLE
[Question] DropDownV2 - facing issue with selected value

### ISSUE THREAD

**Issue by vidhi11** [carbon-design-system/carbon-components-react#1610]
## Detailed description

> Describe in detail the issue you're having.
- Facing issue with DropDownV2 component. It shows the previous selected value even though the item list is empty. 

> Is this issue related to a specific component?
- DropDownV2

> What did you expect to happen? What happened instead? What would you like to see changed?
- When ietm list becomes empty, there should no selected value displayed on dropdown. 

> What browser are you working in?
- Mozilla and Chrome

> What version of the Carbon Design System are you using?
- 9.X.X

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
- IBM Hybrid Cloud , yes we having production release on 12/15/18
 
## Steps to reproduce the issue

1. Initially the dropdown items list is empty array. 
<img width="217" alt="image" src="https://user-images.githubusercontent.com/32270454/49536393-fe932980-f88b-11e8-8fee-b00d4e45c332.png">

2. using js logic, we add items list to dropdown.
<img width="208" alt="image" src="https://user-images.githubusercontent.com/32270454/49536422-12d72680-f88c-11e8-90ea-7352ab67429e.png">

3. using js empty the dropdown list. The list will show previously selected item, even though the list is empty array. 
<img width="212" alt="image" src="https://user-images.githubusercontent.com/32270454/49536460-2aaeaa80-f88c-11e8-9797-a33b1f1af47e.png">

Reproduced code: 
https://codesandbox.io/s/oqnk5m9395

**Comment by asudoh** [comment]
Just to leave a note before being closed - The team's current consensus in this topic is that application should use our presentational components to project application's state. Ones for drop down are `<ListBox*>` found at: https://github.com/carbon-design-system/carbon-components-react/blob/v7.1.0/src/components/Dropdown/Dropdown.js#L213-L254
