### ISSUE TITLE
Dropdown Icon: Make defaultText node instead of string

### ISSUE THREAD

**Issue by jokerstudios** [carbon-design-system/carbon-components-react#164]
Could you make defaultText as a node?
Because I would like to parse something like : {<span><Icon name={{icon}}/>text</span>}.
To show an icon on the left side of the dropdown text.

**Comment by hellobrian** [comment]
Sorry but the Dropdown's `defaultText` is only meant to be a `string`. We don't want to make it possible to include additional nodes inside a `DropdownItem`
