### ISSUE TITLE
Server-side rendering broken with newest release

### ISSUE THREAD

**Issue by filipmadejIBM** [carbon-design-system/carbon-components-react#1640]
I have an issue with upgrading to 6.59. We’re doing server side rendering and after upgrade app crashes

`ReferenceError: window is not defined`

`../node_modules/flatpickr/dist/flatpickr.js:1769:11)`

**Comment by asudoh** [comment]
Hi 👋 wondering what version of Flatpickr you have - The version we have in our `dependencies` should have a fix for: https://github.com/flatpickr/flatpickr/issues/1359

**Comment by dakahn** [comment]
@filipmadejIBM 👋 Was your problem resolved, friend?

**Comment by filipmadejIBM** [comment]
@dakahn Yes it was, issue can be closed

**Comment by asudoh** [comment]
@filipmadejIBM Thank you for your response!
