### ISSUE TITLE
Tabbing inside Modal component goes outside of the modal.

### ISSUE THREAD

**Issue by mkunat** [carbon-design-system/carbon-components-react#1664]
Tabbing inside Modal component goes outside of the modal. I believe this happen only for the Modal created dynamically with prop open="true" (related issue: https://github.com/IBM/carbon-components-react/issues/1616)  

Carbon Design System:  6.59.0

**Comment by asudoh** [comment]
Hi 👋 could you try putting a focusable element that come after `<Modal>` (ideally the last of the `<body>`)? If it doesn't solve the problem, could you create a reduced case based on https://codesandbox.io/s/github/IBM/carbon-components-react/tree/master/examples/codesandbox? Thanks!

**Comment by dakahn** [comment]
Closing this out as resolved. Happy to reopen if that's not the case. 🏄
