### ISSUE TITLE
Should iconDescriptions exist for decorative icons?

### ISSUE THREAD

**Issue by diego-codes** [carbon-design-system/carbon-components-react#1695]
## Summary
Are `iconDescription`s relevant for purely decorative ones?

## Relevant information

I'm wondering what the purpose of having `iconDescription` props for icons that are clearly purely decorative. For example, the Select component accepts this props for the arrow icon which again would be purely decorative and should bare no meaning in accessibility tools like screen readers. The context of the Select for a11y tools would be the select element's label.

There are several components in this package that have this property which doesn't make sense for the reasoning above. I'm wondering if I'm missing the purpose for this prop and would love your thoughts on it!

Thanks 😸

**Comment by dakahn** [comment]
closing this out as resolved. Let me know if that's not the case and I can reopen! 🏄
