### ISSUE TITLE
TabInndex property isn't available for OverflowMenuItem component its only available for overflow menu

### ISSUE THREAD

**Issue by reeteshsingh93** [carbon-design-system/carbon-components-react#1696]
## Detailed description

> Describe in detail the issue you're having.

Unable to navigate using keyboard on overflow menu item options which is an accessibility defect. 

> Is this issue related to a specific component?
Yes

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?
firefox, Chrome

> What version of the Carbon Design System are you using?

    "carbon-components": "8.23.1",
    "carbon-components-react": "5.32.0",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Cloud security Advisor

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
> https://codesandbox.io/s/github/IBM/carbon-components-react/tree/master/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by joshblack** [comment]
Hi @reeteshsingh93! 👋 I believe this could be intended, as the menu button should have the tabindex to access the widget and then it handles setting the tab index on the first item when it is expanded.

Is there another behavior that you believe should be supported within this widget that we could help out with?

**Comment by dakahn** [comment]
closing this as resolved -- let me know if that's not the case 🏄
