### ISSUE TITLE
Dropdown is still be clickable even if empty dropdown item

### ISSUE THREAD

**Issue by lilyclyc** [carbon-design-system/carbon-components-react#174]

**Comment by lilyclyc** [comment]
![image](https://user-images.githubusercontent.com/30255650/29103032-e7d90c1e-7cef-11e7-8864-6eae417954ff.png)

**Comment by lilyclyc** [comment]
@hellobrian -- any idea?

**Comment by hellobrian** [comment]
Hey @lilyclyc, sorry this has taken us so long to address.
What's the reason for having an empty dropdown item?

**Comment by lilyclyc** [comment]
@hellobrian -- The dropdown is disabled when there is no any item and only shows the default text like the below with 'No users'. In this case, the dropdown still can be clickable.
![image](https://user-images.githubusercontent.com/30255650/29902279-b04f253e-8e2f-11e7-8b83-855e3a77a84e.png)

**Comment by hellobrian** [comment]
Just to be clear, you're using the `disabled` prop on Dropdown? (see [storybook](http://react.carbondesignsystem.com/?selectedKind=Dropdown&selectedStory=disabled&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel))

Also, we generally want to always have some kind of default text there in the dropdown component.

**Comment by lilyclyc** [comment]
@hellobrian -- Yes, there is a default text and dropdown is disabled. I hope the dropdown can't be clickable in this case.

**Comment by hellobrian** [comment]
The `disabled` prop will prevent the dropdown from being clickable...
This means that the dropdown will not open when clicked and will remain closed.
