### ISSUE TITLE
Write guide on using the beta releases of Carbon Components React

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-components-react#1748]
Now that we're publishing our beta versions in preparation for X, we should have a document that details:

- Why are we publishing early
- What to expect out of the beta versions we are shipping
- How to use the beta versions in your project
- What kind of feedback are we looking for

**Comment by ram-nadella** [comment]
@joshblack this will be super helpful.

Are the react components being pushed to npm already? Couldn't determine based on the tags on the package. (Versions tab at https://www.npmjs.com/package/carbon-components-react)

Also, thank you for sharing context via the Medium posts.

**Comment by asudoh** [comment]
Hi @ram-nadella we ended up with not releasing our betas as frequently as we anticipated at the time this issue was written, because there is an alternate way for you to try out our `v10` code: https://github.com/IBM/carbon-components-react/blob/v6.97.0/docs/experimental.md#application-usage - Hope this helps!

**Comment by kylegach** [comment]
@asudoh — I tried following those docs, but couldn't get it to work. [Here's a very simple repo](https://github.com/kylegach/cra-ejected-carbon-next/commits/master) that uses an ejected CRA.

Any suggestions? Hoping to play with the v10 stuff to help decide whether to use Carbon or not. Thanks!

**Comment by asudoh** [comment]
Hi @kylegach 👋 probably one thing that's worth telling is that [`data` is a option for the underlying engine behind `sass-loader`](https://github.com/webpack-contrib/sass-loader#environment-variables), instead of one for `css-loader`. Hope this helps!

**Comment by kylegach** [comment]
Thanks, @asudoh. I didn't look closely enough at CRA's `getStyleLoaders` indirection. It's working now. 😄 

I've [updated that simple repo](https://github.com/kylegach/cra-ejected-carbon-next/commit/fcb2a4219eb3de5530479914290559d5c6f05f45), in case it benefits others.

**Comment by claycrenshaw** [comment]
@joshblack @asudoh What's the latest on this migration content? Thanks!

**Comment by asudoh** [comment]
@claycrenshaw If I understand your question correctly - This is about beta, and thus will be obsolete once `v10` is shipped. How to use our pre-release code right now can be found at: 
https://github.com/IBM/carbon-components-react/blob/v6.97.0/docs/experimental.md#application-usage

**Comment by claycrenshaw** [comment]
Thanks @asudoh. Is there any react-specific technical migration content (v9 - v10 Production) in the works right now? I thought there was a migration document in the repo but now I can't find it. Thanks! @joshblack

**Comment by asudoh** [comment]
@claycrenshaw It's `migration-to-10.x` files in this repo. @joshblack worked on creating a index content, at #1993.

**Comment by asudoh** [comment]
No longer needed given we have released `v10`.
