### ISSUE TITLE
Migrate existing icon usage to `@carbon/icons-react`

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-components-react#1765]
We should update our existing icon usage in components to start leveraging the components from `@carbon/icons-react`, most likely behind a feature flag. The pattern we should try and use should be the direct import:

```js
import MyIconName from '@carbon/icons-react/es/icon-name/size';
```

If we can't use the `es` entrypoint, then should use `lib`.

Instead of doing this manually, it might be good to try and write a codemod that works with jscodeshift and try it out on our own project to migrate.

**Comment by asudoh** [comment]
Heard that many of this is done as part of #1512, while keeping this open may make sense to catch any remainders as well as `<Icon>` deprecation.

**Comment by mattrosno** [comment]
I believe this is related so I'm going to document here instead of new issue.

```json
"@carbon/icons-react": "^0.0.1-alpha.12",
"carbon-components-react": "^6.99.1",
```

I'm able to:

```javascript
import Search20 from "@carbon/icons-react/es/search/20";
import { Button } from "carbon-components-react";
```

And in a render function:

```javascript
<Search20 />
<Button>Add taco</Button>
```

Both the icon and button render. But, when I use the React icon with button like so:

```javascript
<Button icon={<Search20 />}>Add taco</Button>
```

Browser throws error:

```
Warning: Failed prop type: The prop `icon.viewBox` is marked as required in `Icon`, but its value is `undefined`.
```

I guess I know know if this is Button component bug, Icon component bug, or `@carbon/icons-react` bug. Let me know if I need to refile as new issue.

**Comment by asudoh** [comment]
@mattrosno Support for icons from `carbon-elements` for `<Button>` is tracked in: #1750

**Comment by asudoh** [comment]
The effort is complete - Let's track specific issues, if they are there, in separate issues.
