### ISSUE TITLE
Rendering Tab with loop

### ISSUE THREAD

**Issue by harshinim** [carbon-design-system/carbon-components-react#177]
I am trying to render Tab within a loop and its not working

something like this
```jsx
 return (
      <Tabs style={{ marginLeft: '13.95rem'}}>
        {this.state.templateData.category.map(function(category, index){
          return <Tab label={category.name}
                      key={index}
          ><div style={{ marginLeft: '13.95rem' }}>Content</div></Tab>;
        })}
      </Tabs>
    );
```
I don't see any errors either

**Comment by harshinim** [comment]
I think the code snippet did not get copied properly, here it is

 return (
      <Tabs style={{ marginLeft: '13.95rem'}}>
        {this.state.templateData.category.map(function(category, index){
          return <Tab label={category.name}
                      key={index}
          ><div style={{ marginLeft: '13.95rem' }}>Content</div></Tab>;
        })}
      </Tabs>
    );

**Comment by harshinim** [comment]
Code snippet is not getting copied properly..trying again by splitting it

return (
      <Tabs style={{ marginLeft: '13.95rem'}}>
        {this.state.templateData.category.map(function(category, index){
          return <Tab label={category.name}
                      key={index}

**Comment by harshinim** [comment]
><div style={{ marginLeft: '13.95rem' }}>Content</div></Tab>;
        })}
      </Tabs>

**Comment by harshinim** [comment]
<div style={{ marginLeft: '13.95rem' }}>Content</div></Tab>;
        })}
      </Tabs>

**Comment by harshinim** [comment]
<div style={{ marginLeft: '13.95rem' }}>Content</div></Tab>
        })}
      </Tabs>

**Comment by hellobrian** [comment]
I edited your comments so that it renders your code properly

**Comment by hellobrian** [comment]
This is a pretty common react pattern, try googling for this. Here's what I found for you to get your started:

- https://thinkster.io/tutorials/iterating-and-rendering-loops-in-react
- https://facebook.github.io/react/docs/lists-and-keys.html
