### ISSUE TITLE
A11Y: OverflowMenu - Tabbing through menu items should cycle back to beginning of list

### ISSUE THREAD

**Issue by rob-richards** [carbon-design-system/carbon-components-react#1783]
## Detailed description
Tabbing through menu items should cycle back to beginning of the list.

> Steps to reproduce

With the overflow menu open, tab through the items if there are any.

- Current Behavior: You end up leaving the overflow menu and it stays open.
- Desired Behavior: Tab should bring you back to the first item

**Comment by dakahn** [comment]
The current iteration of the React overflow menu uses a system menu style navigation pattern. Arrow keys cycle through the options (with the functionality you mention). The menu itself is a full tab stop so hitting tab will take you to the next focusable element on the page. 👍
