### ISSUE TITLE
unknownProp warnings

### ISSUE THREAD

**Issue by eddiemonge** [carbon-design-system/carbon-components-react#179]
There are a couple of warnings as shown https://travis-ci.org/carbon-design-system/carbon-components-react#L758 

```
    console.error node_modules/fbjs/lib/warning.js:35
      Warning: Unknown prop `stepMuliplier` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
          in div (created by Slider)
          in div (created by Slider)
          in div (created by Slider)
          in Slider (created by WrapperComponent)
          in WrapperComponent
```

**Comment by chrisdhanaraj** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/6b8b7163-1ec8-4616-82fa-aa467a17af03 "storybook-toolchain-v2"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/b84aaac8-8484-4a1e-902a-ebb526eb7998 "storybook-toolchain-v2") deployed [carbon-components-react](https://github.com/carbon-design-system/carbon-components-react/releases/tag/deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171011-005532 "deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171011-005532") to [Bluemix Design System](https://console.bluemix.net/apps/bc75a101-6472-481c-b48d-3eed1e9703f3?env_id=ibm:yp:us-south "ibm:yp:us-south:chrisdhanaraj_org:Bluemix Design System"), including commit 241a15e00daa60858cdab9a440d23eb24fa473a0
