### ISSUE TITLE
DataTable: filter function doesn't work with 'al'

### ISSUE THREAD

**Issue by jillyj** [carbon-design-system/carbon-components-react#1811]
## Detailed description

> Describe in detail the issue you're having.

When the search text input is 'al', the filter result is not correct. Some rows with no 'al' text are returned. 
> Is this issue related to a specific component?

Yes, DataTable.
> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

Chrome, firefox.
> What version of `carbon-components-react` are you using?

v6.84

## Steps to reproduce the issue

1. Step one
Render DataTable with some data.
2. Step two
Input 'al' in the text input field.
Result:
The rows with no 'al' are returned. (the last 2 rows)
![image](https://media.github.ibm.com/user/7988/files/93000e82-2567-11e9-8aac-2a43ae76cded)

## Additional information
* Notes
  - The filter works with other keywords, but just not 'al'.

**Comment by jillyj** [comment]
Hi, while recreating the issue on sandbox, I found the root cause is that I used checkbox in last column and its value is 'false'. So the filtering filters the rows with checkbox not checked. 
Is there any way that I only filter the first 2 columns? Thanks.

**Comment by asudoh** [comment]
@joshblack Would it make sense to let user define the filter logic coping with boolean value, or accept the PR to make [the default filter logic](https://github.com/IBM/carbon-components-react/blob/v6.61.0/src/components/DataTable/tools/filter.js#L22) ignore boolean value? Thanks!

**Comment by joshblack** [comment]
Yeah! Let's do it 👍 Whatever makes this easier.

cc @aagonzales does this checkbox pattern under extract make sense for data table, btw?

**Comment by aagonzales** [comment]
Yup, seems fine to me!

**Comment by jillyj** [comment]
Thanks for accepting this issue. May I know when will this issue be fixed? Thanks.

**Comment by asudoh** [comment]
Hi 👋 application can implement a [custom filter logic](https://github.com/IBM/carbon-components-react/blob/v6.61.0/src/components/DataTable/README.md#filterrows) coping with boolean value. You can start with a copy of [the default filter logic](
https://github.com/IBM/carbon-components-react/blob/v6.61.0/src/components/DataTable/tools/filter.js#L22) and make it work with boolean. Also as I said, a PR to fix the default filter logic will be nice. Thanks!

**Comment by jillyj** [comment]
Hi, I submitted PR for this issue: https://github.com/IBM/carbon-components-react/pull/1858. Would you please help to review? If the newly added story is not necessary, I can remove it. Thanks.

**Comment by jillyj** [comment]
I tried to use a custom filter logic, but it always reports error...
Here is my trying example: https://codesandbox.io/s/7wj31zzvqj
I just added a function for the custom filter, and print something to see if it's entered.

![image](https://user-images.githubusercontent.com/47232763/52612315-1ad2c880-2ec4-11e9-8fba-f154f8efb4d8.png)

**Comment by jillyj** [comment]
Hi, I found the root cause of the error of custom filter.
If I use curly brackets, and it reported error. If not, it successes. Looks like a bug??
Work case:
![image](https://user-images.githubusercontent.com/47232763/52613247-20caa880-2ec8-11e9-9aad-e326b33a4394.png)

Error case: (but documentation has curly brackets [custom filter](https://github.com/IBM/carbon-components-react/blob/v6.61.0/src/components/DataTable/README.md#filterrows))
![image](https://user-images.githubusercontent.com/47232763/52613312-5f606300-2ec8-11e9-89ad-deeff68d97b9.png)

**Comment by asudoh** [comment]
@jillyj I see the difference between them is that the former returns the filtered value whereas the latter doesn't. Both of them are arrow functions, right?

**Comment by jillyj** [comment]
@asudoh Yeah, you are right!! Thanks!
