### ISSUE TITLE
DataTable: No way to set selectedRows to state

### ISSUE THREAD

**Issue by smchamberlin** [carbon-design-system/carbon-components-react#1879]
Hello, selectedRows in DataTable returns the selected rows from the checkboxes, however I don't believe there is any way (that I know of) to set this to the state of the React component (the external state managed outside of the DataTable).  

This would be a very useful thing if we wanted to do something with those checkboxes outside of the DataTable components, for example, submit the results of those checkboxes to a REST API (which is what I'm trying to do).

I worked for several days to customize my DataTable and override some of the default behavior to get this to work, but seems like there should be native support for it.

Thanks

**Comment by devniel** [comment]
Hi,

One thing that I'm doing to get the selected rows from outside the DataTable is by using refs:

```jsx
<DataTable
 ref={(e) => {this.dataTable = e}}
```

Then, in some click handler:

```js
onSubmit = () => {
    const { rows  } = this.props;
    const selectedRowsIds = this.dataTable.getSelectedRows();
    // get the selected rows using the selectedRowsIds data.
}
```
About updating the state, I didn't found an event that is fired when a row was selected, thinking about updating the state in the `render` after receiving the `selectedRows` property seems crazy.

**Comment by asudoh** [comment]
Hi :wave: @smchamberlin thank you for reporting and thanks @devniel for jumping in! In general changing component's state in this library tends to be done via props, as many of our components have prop -> state sync mechanism. AFAIK data table has some. That said, I'm wondering if you can try setting the new selected state via props. Thanks!

**Comment by smchamberlin** [comment]
Thanks Akira,

I also see that this seems to be the same issue as:
https://github.com/IBM/carbon-components-react/issues/1285

which is still open and also has comments from you -- was there any resolution there ?  

Also, if you look at the code for react-data-table-component (not the carbon version), they describe a simple way to do it with a onTableUpdate function which passes the state.selectedRows to the outside:
https://www.npmjs.com/package/react-data-table-component

Does the carbon version of react DataTable have something like this ?  

I don't know what you mean by "set the new selected state via props".  Can you please give an example of that ?

Thanks.

**Comment by asudoh** [comment]
@smchamberlin I thought the prop -> state sync mechanism covers the selection state, but seems that I was wrong because of #1247 - My apologies. CC @joshblack to see if he wants to give guidelines to contributors to move it forward.

**Comment by smchamberlin** [comment]
@asudoh Is it currently possible to do something like this ? (Pasted from https://www.npmjs.com/package/react-data-table-component)

If not, one workaround might be to use the react-data-table-component and stylize it with CSS to look like carbon data component?

``` 
const handleChange = (state) => {
  // You can use setState or dispatch with something like Redux so we can use the retrieved data
  console.log('Selected Rows: ', state.selectedRows);
};
 
class MyComponent extends Component {
  render() { 
      return (
        <DataTable
          title="Arnold Movies"
          columns={columns}
          data={data}
          selectableRows // add for checkbox selection
          onTableUpdate={handleChange}
        />
    )
  }
);
```

**Comment by asudoh** [comment]
Seems not - My personal recommendation is getting a green light from legal to maintain a fork of this library and make changes you need. Contribution will be great and please get in sync with @joshblack to do so. I don't have a word on 3rd party library usage.

**Comment by joshblack** [comment]
Hi @smchamberlin! 👋 Definitely agreed on all the points that you made in this issue 😄 

For Data Table, a big part of the API over time will be formed by the newer features in React. Things like hooks and context updates will allow consumers to both read and write to state in a way that we can't express in the current API.

As a result, this has left us in a weird position since we want to deliver on features today while still preparing for the future. Definitely understand where your coming from, would love to hear what we could offer in the interim to help make things work out while we wait for some of these exciting changes 😄

**Comment by smchamberlin** [comment]
@joshblack Sent a private email to your IBM account - I am unblocked for now as I made some modifications to track the checkpoint state myself, but I did this on top of the DataTable instead of modifying DataTable code directly, so I don't think I can contribute this back.

**Comment by asudoh** [comment]
Just to leave a note before being closed - The requirement for initial selection (tracked in #1247) has been addressed. For reflecting after-creation-time selection changes, the team's current consensus is that application should use our presentational components to project application's state. Ones for data table are found as `<Table*>` at: https://github.com/carbon-design-system/carbon-components-react/blob/v7.1.0/src/components/DataTable/stories/default.js#L50-L107
