### ISSUE TITLE
Interior Left Nav Bug

### ISSUE THREAD

**Issue by jzhang300** [carbon-design-system/carbon-components-react#19]
**Context**:

![left-nav-bug](https://user-images.githubusercontent.com/1449523/27143021-893de0ea-50f2-11e7-8b52-c5669ecd6657.gif)

Interior Left Nav text can get wonky when you highlight the text.

This seems to only happen in Chrome, and seems to be related to Flexbox.

---

- [ ] Fix text from shifting

**Comment by hellobrian** [comment]
Hmmm, can you submit a gif? If you need software, I use [licecap](http://download.cnet.com/LICEcap/3000-2094_4-75984664.html), which looks a little sparse, but it's legit.

If not, show me or one of the FEDs in the office when you get a free moment.

**Comment by jzhang300** [comment]
Thanks for tool recommendation!

**Comment by jzhang300** [comment]
@hellobrian ok I just updated the original post.

**Comment by chrisdhanaraj** [comment]
Can't reproduce
