### ISSUE TITLE
InlineLoading UX example has no documentation in the storybook

### ISSUE THREAD

**Issue by rcasey92** [carbon-design-system/carbon-components-react#1905]
InlineLoading UX example has no documentation in the storybook

### Steps for reproducing
See storybook page [here](http://react.carbondesignsystem.com/?selectedKind=InlineLoading&selectedStory=UX%20example&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel)

### Screenshots
<img width="1339" alt="screen shot 2019-02-21 at 3 36 08 pm" src="https://user-images.githubusercontent.com/13108734/53196445-7d2b7780-35ee-11e9-8c10-3b9edf767931.png">

**Comment by asudoh** [comment]
CC @loganmccaul AFAIK the "UX example" part you referred to is merely for demonstrating how `<InlineLoading>` would be used in an application, demonstrated in STORY tab at the bottom. You can see more documentation in "Inline loading" tab, along with the KNOBS tab at the bottom. Hope this helps!
