### ISSUE TITLE
MultiSelect component does not support update of initialSelectedItems

### ISSUE THREAD

**Issue by dejunqi2008** [carbon-design-system/carbon-components-react#1912]
Use this template if you want to request a new feature, or a change to an existing feature.

If you are reporting a bug or problem, please use the bug template instead.

### Summary
Currently the `MultiSelect` component does not support update of `initialSelectedItems`, this prevent us from using Redux to control the checked / unchecked status of every dorpdown checkbox of it. By looking at the source code, I believe it would be an easy improve in the `src/internal/Selection.js` .
We can add a `componentDidUpdate` and `setState` to update the state attribute `selectedItems`. 

### Desired UX and success metrics

Describe the full user experience for this feature. Also define the metrics by which we can measure success/failure for the user.

### "Must have" functionality

Highlight any "must have" needs and functionality for the request.

This should not be a full list of functionality; the Carbon team will work with you to define functionality based on the desired UX.

### Specific timeline issues / requests

Do you want this work within a specific time period? Is it related to an upcoming release?

_NB: The Carbon team will try to work with your timeline, but it's not guaranteed. The earlier you make a request in advance of a desired delivery date, the better!_

### Available extra resources

What resources do you have to assist this effort?

_Carbon is a collaborative system. We encourage teams to build components and submit them for integration as either add-ons or core components._

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! As the `initialSelectedItems` tells, this seems to have been intended just for the initial state and up-to-date selection seems not opened up for programmatic control. Opening up `selectedItems` prop and using `getDerivedStateFromProps()` to do prop -> state sync may be one option. It involves a breaking change of property name, but I don't think we want to reuse `initialSelectedItems` prop name for updatable list.

**Comment by asudoh** [comment]
Refs: #992

**Comment by asudoh** [comment]
Refs: #992 FYI @emyarod

**Comment by dejunqi2008** [comment]
@asudoh Thanks, just ask if this is possible to be improved. If not, we can use old fashion way to do it, such as DOM event, though it is not very elegant.

**Comment by dejunqi2008** [comment]
@Georgegriff Close this issue, I no longer need this. Thanks

**Comment by asudoh** [comment]
@sdignum brought up this topic at carbon-design-system/carbon#2891. The current recommendation for this problem space is that application renders our presentational components by themselves, those presentational components can be seen at: https://github.com/carbon-design-system/carbon-components-react/blob/v7.1.0/src/components/MultiSelect/MultiSelect.js#L231-L313
