### ISSUE TITLE
tooltip not able to wrap dropdown list

### ISSUE THREAD

**Issue by lounestor** [carbon-design-system/carbon-components-react#192]
Dropdown example
```javascript
<Dropdown ref='selectingComponent'
                onChange={this.selectedItem.bind(this)}
                selectedText={selectedText} >
        {this.state.resourceList.map((listItem, k) =>  
            <DropdownItem  key={listItem.id}
                           value={JSON.stringify(listItem)}
                           onChange={this.selectedItem.bind(this)}
                           itemText={listItem.text} />
        )}
</Dropdown>
```
Required functionality:
I want be able to wrap my tooltip around this component
I can force triggerText to take a component but but selected text does not get set.

```javascript
<Tooltip className='tooltip'
                     direction="right"
                     triggerText={<DropdownItem key={listItem.id}
                                                value={JSON.stringify(listItem)}
                                                itemText={listItem.text} />}
                     showIcon={false}><p>{listItem.text}</p></Tooltip>
```
can you help with this?

**Comment by joshblack** [comment]
Hi there! 👋 

To help understand the use-case, is it possible for you to share any of the design comps for this implementation? Looking at it from an outside context, it seems like unintended usage, but totally understand if it's a requirement coming from Design 😄

**Comment by marijohannessen** [comment]
@bsonefeld Could you provide some feedback here? I believe the correct way of doing this would be to have a tooltip icon next to the dropdown label and not have the dropdown be the tooltip trigger, but please correct me if I'm wrong!

**Comment by bsonefeld** [comment]
@marijohannessen sounds about right, but without proper comps of the design problem I'm unable to assess what a proper solution would be. @lounestor can you please attach some screenshots of the intended design?

**Comment by lounestor** [comment]
For example i have two items in my dropdown
my dropdown has a fixed width due to design requirments.
Therefore with long names with we cut of with elispses
e.g 
myveryververylongname1 => myvery... 
myveryververylongname2 => myvery..

we need the tooltip to display the full name.

**Comment by marijohannessen** [comment]
@lounestor can you please provide us with a screenshot of the design?

**Comment by marijohannessen** [comment]
Closing this issue due to our inactivity policy. Please feel free to reopen if needed.
