### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by syntaxerror13** [carbon-design-system/carbon-components-react#193]
Hi, can you please add a licence file to the project? Also, am I correct assuming the project is under MIT licence just the file is missing? (package.json indicates MIT, that's why I think so)

**Comment by hellobrian** [comment]
Maybe @chrisdhanaraj can clarify

**Comment by joshblack** [comment]
Gonna re-visit this with @chrisdhanaraj and see if we should use Apache-2.0 like carbon-components currently does.

**Comment by joshblack** [comment]
Moving forward with Apace-2 license, like in carbon-components!
