### ISSUE TITLE
DropdownV2: Usability: support translatable "Open menu", "Close menu" text.

### ISSUE THREAD

**Issue by JessNah** [carbon-design-system/carbon-components-react#1952]
Hovering over the arrow icon on dropDownV2 displays text "Open menu"/"Close menu", would be nice if we could set this text ourselves, so that we can support translations.

**Comment by dakahn** [comment]
Hi! We actually have full internationalization implemented but don't expose that prop in this component yet. Great catch and a much needed improvement. 👍
