### ISSUE TITLE
InteriorLeftNavItem onClick issue

### ISSUE THREAD

**Issue by dcostantino** [carbon-design-system/carbon-components-react#197]
onClick is documented as an event for InteriorLeftNavItem, but because of the stopPropagation call on the parent the onClick is never invoked.

**Comment by chethankumar** [comment]
Any ETA's on when this would be fixed. I am also waiting for it.
Is there a workaround available till its fixed

**Comment by marijohannessen** [comment]
Hi @chethankumar , I'll make sure we tackle this next sprint (starting this Monday) so a fix will be out shortly. Thank you for your patience!

**Comment by tw15egan** [comment]
@chethankumar @dcostantino as a workaround for now, you could use the `Link` component as the `InteriorLeftNavItem`'s child, and place the `onClick` on that. That way, you will be able to trigger something when a nav item is clicked. 

Currently, the `InteriorLeftNavItem` is only allowing an internal `onClick` that is then passed up to `InteriorLeftNav`. As of now, this is the quickest workaround until a refactor of the `InteriorLeftNav` is completed

**Comment by marijohannessen** [comment]
`InteriorLeftNavItem` now requires a child (either an `a` or a `Link`), so you can put the `onClick` on that child to trigger something when a nav item is clicked. Feel free to re-open if you're still experiencing this issue!
