### ISSUE TITLE
Warning about missing the prop "href" of InteriorLeftNavItem

### ISSUE THREAD

**Issue by tim-zhong** [carbon-design-system/carbon-components-react#198]
<img width="502" alt="screen shot 2017-08-22 at 11 37 14 am" src="https://user-images.githubusercontent.com/10435612/29574048-72b8d33a-872e-11e7-893c-ba134530f512.png">

^-- According to the doc, "href" isn't a required property of InteriorLeftNavItem. 
But I'm getting warnings for not defining it.
```
Warning: Failed prop type: The prop `href` is marked as required in `InteriorLeftNavItem`, but its value is `undefined`.
```

Any ideas?
Thanks

**Comment by tw15egan** [comment]
Hm that's odd. It seems like an issue with storybook. In the latest release, `href` and `label` are both required. 

<img width="943" alt="screen shot 2017-08-22 at 2 10 33 pm" src="https://user-images.githubusercontent.com/11928039/29582804-b0b357f4-8743-11e7-9309-2bdf62190f32.png">
