### ISSUE TITLE
Search icon near filter is not functional (using carbon component)

### ISSUE THREAD

**Issue by smural** [carbon-design-system/carbon-components-react#1986]
## Title line template: [Title]: Brief description
The search icon near filter is not functional (using carbon component).
Expect to click the search icon but it seems not be working.

## Environment

> Browser: Google Chrome

## Detailed description

Search icon near filter  is not functional

> What did you expect to happen? The search icon to be functional to click and filter

> What happened instead?The search icon is not functional to clic

<img width="522" alt="screen shot 2019-03-07 at 4 08 25 pm" src="https://user-images.githubusercontent.com/48334158/53989210-7b37dd00-40f3-11e9-847b-e83f1b709b49.png">

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! Seems that the only way to achieve what you want is attaching an event listener to `<body>` (or any DOM element containing the search box) and see if the event comes from the search button. Hope this helps!

**Comment by dakahn** [comment]
Closing this out as resolved 👍 Happy to reopen if we need to.
