### ISSUE TITLE
ProgressIndicator is not being rendered

### ISSUE THREAD

**Issue by hanhansen** [carbon-design-system/carbon-components-react#199]
`<ProgressIndicator />` does not seem to render at all. What properties are required for this to work?

**Comment by tw15egan** [comment]
Hey, you can find a working example of this [here](http://react.carbondesignsystem.com/?selectedKind=Progress%20Indicator&selectedStory=Default&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel), but basically you need something like this. 

```html
<ProgressIndicator currentIndex=3>
   <ProgressStep label="label" description="Step 1: Getting Started with Node.js" />
   <ProgressStep label="label" description="Step 2: More Node.js" />
</ProgressIndicator>
```
