### ISSUE TITLE
DropdownV2 + Textbox misaligned inline-block

### ISSUE THREAD

**Issue by jake-stark** [carbon-design-system/carbon-components-react#1994]
## Detailed description

> Describe in detail the issue you're having.

 I want to display a text box and a dropdown (v2) horizontally aligned in a row on the page.
If the parent component is given style display:inline-block, as well as the two child components (along with a vertical align top style), they are slightly mis-aligned

> Is this issue related to a specific component?

Dropdown V2 + Textbox

> What did you expect to happen? What happened instead? What would you like to see changed?

I expect that the two input boxes are aligned vertically and horizontally 

> What browser are you working in?

Firefox + Chrome

> What version of the Carbon Design System are you using?

^9.83.1

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

None

## Steps to reproduce the issue

1. Step one
Create parent container with display: inline-block style
2. Step two
create two child containers with inline-block style and vertical-align top style

> Please create a reduced test case in CodeSandbox
> https://codesandbox.io/s/github/IBM/carbon-components-react/tree/master/examples/codesandbox

see here: https://codesandbox.io/s/1zj5mm16rl

## Additional information

- Screenshots or code

- Notes

**Comment by asudoh** [comment]
Hi :wave: thank you for reporting! Looking at https://codesandbox.io/s/1zj5mm16rl, the drop down and the text box looks aligned well. Hope the problem has been solved for you, but otherwise, more info will be nice.

**Comment by dakahn** [comment]
Closing this as resolved. happy to reopen if that's not the case 🏄
