### ISSUE TITLE
CarbonComponents Styles

### ISSUE THREAD

**Issue by eddiemonge** [carbon-design-system/carbon-components-react#2]
According to the [Getting Started](https://github.com/carbon-design-system/carbon-components-react/tree/3.x#getting-started), the global styles should be imported from carbon components, however, those have been moved to devDeps and not a dep in the 3.x branch. This is a problem because `npm i carbon-components-react` does not install them. The instructions should be updated to say that it is now a required module if you want to include them, or package that style file into this module's built files.

> Components do not import any of the global styles (font-family, font-size, body color, etc.). As such, you'll need to pull them into your project. One way to accomplish this is to create a SASS file that declares the use of globals and pulls in the global SASS module.

**Comment by hellobrian** [comment]
Hey @eddiemonge, looks like @chrisdhanaraj [updated the readme](https://github.com/carbon-design-system/carbon-components-react/commit/7323a0a1bdb5514a7a1a53524e1cf131ad26c73d), which should address the issues you raised. Thanks again!

>### Getting Started
>
>```
>npm install -S carbon-components-react carbon-components carbon-icons
>```
>
>1. These components require the use of [Webpack](http://webpack.github.io/docs/tutorials/getting-started/) in your project. See our [`webpack.config.js`](/.storybook/webpack.config.js) for an example configuration.
>
>2. Components do not import any of the styles themselves, use the scss or css from `carbon-components` to bring in styling. You can also use the `unpkg` cdn to bring in the styles wholesale - `unpkg.com/carbon-components/css/carbon-components.css` aliases the latest css file.
