### ISSUE TITLE
IDs assignment for Pagination

### ISSUE THREAD

**Issue by flyHe** [carbon-design-system/carbon-components-react#200]
same issue with https://github.com/carbon-design-system/carbon-components-react/issues/125
this issue has been resolved by commit https://github.com/carbon-design-system/carbon-components-react/commit/7ea8ab9e46bc1df76d246db186c645aecbd7bbbe, but issue went back by this commit https://github.com/carbon-design-system/carbon-components-react/commit/241a15e00daa60858cdab9a440d23eb24fa473a0#diff-85a01ef37e019ab9e924c99610a0dad9L178 . The inputId has been changed.Is this necessary in that commit?

**Comment by eddiemonge** [comment]
Put a PR in. Sorry about that 😞

**Comment by chrisdhanaraj** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/6b8b7163-1ec8-4616-82fa-aa467a17af03 "storybook-toolchain-v2"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/b84aaac8-8484-4a1e-902a-ebb526eb7998 "storybook-toolchain-v2") deployed [carbon-components-react](https://github.com/carbon-design-system/carbon-components-react/releases/tag/deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171011-005532 "deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171011-005532") to [Bluemix Design System](https://console.bluemix.net/apps/bc75a101-6472-481c-b48d-3eed1e9703f3?env_id=ibm:yp:us-south "ibm:yp:us-south:chrisdhanaraj_org:Bluemix Design System"), including commit a7d8c707884512c36363b0961e4c90a5dfb31174
