### ISSUE TITLE
MultiSelect.Filterable invalid: true styling bug.

### ISSUE THREAD

**Issue by yasotnik** [carbon-design-system/carbon-components-react#2009]
## Detailed description

> While using `<MultiSelect.Filterable>` component with `invalid={true}` the style of bottom shadow has a bug. Here is couple of screenshots: 

![not focused](https://user-images.githubusercontent.com/5897195/54266139-1955f800-4577-11e9-8027-47fe94424211.png)
Here you can see that red box shadow also has blue color over it.

![focused](https://user-images.githubusercontent.com/5897195/54266345-7ce02580-4577-11e9-9e8c-e7cee98c85e6.png)
You can see it even better when input field used for filtering inside MultiSelect is focused

That's all because of `bx--text-input` style.
**Normal state:** while `bx--multi-select` has `data-invalid="true"`, `bx--text-input` which is inside still has `box-shadow: 0 1px 0 0 #5a6872;` 
**Focus state:** `box-shadow: 0 2px 0 0 #3d70b2;` for `.bx--text-input:focus` which causes the bug.

## Steps to reproduce the issue

1. Open sandbox - https://xrmwxlyo5w.codesandbox.io/
2. Observe the bug
3. ?????
4. You are awesome

**Comment by yasotnik** [comment]
I am not sure what should be the behavior of `filtering input`, should it has shadow etc.
But as a workaround you can use: 

> .bx--list-box[data-invalid] .bx--text-input {
>   box-shadow: none !important;
> }

**Comment by asudoh** [comment]
Seems to be solved in `v10`.

**Comment by dakahn** [comment]
@emyarod this one come up again?

**Comment by emyarod** [comment]
no it can probably be safely closed since this is a v9 issue, but I left it open until the v10 multiselect gets merged in
