### ISSUE TITLE
Progress indicator not working when current index is 0

### ISSUE THREAD

**Issue by hanhansen** [carbon-design-system/carbon-components-react#201]
![screen shot 2017-08-23 at 9 43 36 am](https://user-images.githubusercontent.com/12817107/29618921-9b5a601a-87e7-11e7-883f-70225e5128c2.png)

Would the progress indicator be able to support the above? When I set the currentIndex to 0 with two steps, the entire progress indicator is hidden

**Comment by tw15egan** [comment]
Seems like this is a bug based on this conditional:

![screen shot 2017-08-23 at 10 37 50 am](https://user-images.githubusercontent.com/11928039/29624621-2cd61474-87ef-11e7-9565-4c6df9d2cd02.png)

`0 === false`, so it returns `null`
