### ISSUE TITLE
Slider component not calling onChange

### ISSUE THREAD

**Issue by jlpadilla** [carbon-design-system/carbon-components-react#204]
The Slider component doesn't call the onChange prop when its value is changed.

Other minor issues are:
- `setState()` not being used correctly. [More info](https://facebook.github.io/react/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous)
- Arrow functions shouldn't be used in JSX props. [More info](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md)

**Comment by chrisdhanaraj** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/6b8b7163-1ec8-4616-82fa-aa467a17af03 "storybook-toolchain-v2"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/b84aaac8-8484-4a1e-902a-ebb526eb7998 "storybook-toolchain-v2") deployed [carbon-components-react](https://github.com/carbon-design-system/carbon-components-react/releases/tag/deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171011-005532 "deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171011-005532") to [Bluemix Design System](https://console.bluemix.net/apps/bc75a101-6472-481c-b48d-3eed1e9703f3?env_id=ibm:yp:us-south "ibm:yp:us-south:chrisdhanaraj_org:Bluemix Design System"), including commit fd48c293c4d1bdeb6d787731ea49428334dcd4de
