### ISSUE TITLE
Add to Storybook Demo

### ISSUE THREAD

**Issue by ndelangen** [carbon-design-system/carbon-components-react#208]
Your Storybook looks awesome!!, perhaps you'd like to add it to the examples page: https://storybook.js.org/examples/

Edit here:
https://github.com/storybooks/storybook/edit/master/docs/pages/examples/_examples.yml

**Comment by tw15egan** [comment]
Thanks for the suggestion! SUbmitted a PR: https://github.com/storybooks/storybook/pull/1764
