### ISSUE TITLE
ModalWrapper "Unknown prop" warning

### ISSUE THREAD

**Issue by alisonemiller** [carbon-design-system/carbon-components-react#209]
I see the following error when I pass in `handleSubmit` as props to the `ModalWrapper` component:

```
Warning: Unknown prop `handleSubmit` on <div> tag. Remove this prop from the element.
```

Works as expected when I use `onRequestSubmit` instead.

**Comment by hellobrian** [comment]
Resolved by https://github.com/carbon-design-system/carbon-components-react/pull/217
