### ISSUE TITLE
Interior Left Nav collapse classname issue

### ISSUE THREAD

**Issue by jzhang300** [carbon-design-system/carbon-components-react#21]
`.bx--interior-left-nav-collapse` should be `.bx--interior-left-nav--collapse`

![screen shot 2017-06-13 at 1 44 07 pm](https://user-images.githubusercontent.com/1449523/27098802-6ec8aace-503e-11e7-9e3f-80f38a0724e3.jpg)

---

- [ ] fix collapse modifier classname typo

**Comment by jzhang300** [comment]
Nvm, I found that `.bx--interior-left-nav-collapse` is the different than `.bx--interior-left-nav--collapsed`, which is a little confusing.

**Comment by hellobrian** [comment]
Lol that...is kind of confusing. I'm so sorry.
