### ISSUE TITLE
NumberInput is no longer able to be controlled by a parent component

### ISSUE THREAD

**Issue by JQrdan** [carbon-design-system/carbon-components-react#2106]
## Detailed description

> Describe in detail the issue you're having.

Previously, NumberInput was ‘prop driven’. Prop copied into state and used, thus consistent.
Now, there is a check around min/max value - meaning the provided value from the parent may not be used.
It seems like the behaviour of `value` has changed to be more like `defaultValue` as per other carbon components. Where we use a parent component to drive the value from props, we are now getting inconsistent behaviour where the component is ignoring the props we give in. I.e when a user hits backspace to start typing a a new value, it automatically resets to the minimum value.
Should value be `defaultValue`, and never read again post mount?

> Is this issue related to a specific component?

NumberInput

> What did you expect to happen? What happened instead? What would you like to see changed?

Empty string should be able to be applied and accepted as an input without being overwritten with the minimum value

> What browser are you working in?

All

> What version of the Carbon Design System are you using?

V6.97.2

## Steps to reproduce the issue

See sandbox, hit backspace to try and edit input

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/z62vy7y463

**Comment by emyarod** [comment]
hi @JQrdan thank you for reporting this! it looks like the event target in your sandbox example is either the SVG or the button as that's the element the user is acting on. do you have the most recent version number where the behavior you described was working properly?

**Comment by JQrdan** [comment]
Hi @emyarod we found that this commit is the one that has done the damage for us: 

https://github.com/IBM/carbon-components-react/commit/f96e9308a2067bf8ceb07dde6cb4340fdffe4aa5#diff-5ac9e46851a15ee269762fe6e264ba0b

`State` was removed from the check on line 58 meaning that it treats every new props change as if it is the component being loading for the first time

**Comment by JQrdan** [comment]
Also, in regards with the button presses, we are not spotting that issue in our current build but on the sandbox they are acting strangely 🤔

**Comment by emyarod** [comment]
thanks for looking into the file history @JQrdan, will need to do some more investigation to see what the initial reason for its removal was

**Comment by AngelaChenBJ** [comment]
@emyarod @JQrdan , I am using NumberInput, and I also encountered the problem that when I hit backspace to start typing a new value, it automatically resets to the minimum value, the same behavior as described in above sandbox example.  
The carbon version I am using is: carbon-components-react@^6.60.1: version "6.106.3"
Look forward to hearing your update on this problem. Thanks.

**Comment by asudoh** [comment]
Hi :wave: just to double-check - Is this issue simply requesting for application-provided value directly reflected to the UI without applying min/max?

**Comment by matthew-chirgwin** [comment]
Hi @asudoh , I work with @JQrdan, and to answer your question, yes and no. The `NumberInput` component provided/provides a `value` prop which used to be just copied into component state and then rendered. Recent versions of the NumberInput component (we saw this post V6.97.2) then added this min/max check, and rendered the ajusted value. This means the value we pass to it, and the one which is rendered could be different, and infact block the user from making a change they want. 

In our scenario, we had a NumberInput which which started with a starting value of 5. If the user wanted to change it to 20 (for instance), they might backspace to an empty string to then type the number 2. As is, the min validation check in `getDerivedStateFromProps` rejects the empty string value, and changes it to the min value. In our case the user then got confused/frustrated, and gives up trying to change this value.

Arguably our case could be resolved with an 'isEmptyString' check, or disabling the validation (which was the old behaviour we were expecting). The point that @JQrdan makes though around the use of `value` (ie completely prop driven) vs `defaultValue` (the NumberInput component copies the first value into state, and never reuses the initially provided value post mount) needs some thought/documentation/consistency.  Some components mention this detail, some don't, and in this case, this changing in behaviour wasnt obvious/clear to us, causing this issue.

**Comment by vpicone** [comment]
@matthew-chirgwin thanks for the description that certainly seems frustrating for both the developers and users. We’ve had some discussion around the controlled/uncontrolled nature of our components and are going to be actively working towards assimilating them in that regard. https://github.com/IBM/carbon-components-react/issues/2207

I think this component is a great example of how this behavior can result in buggy component logic and UIs as a result.

**Comment by asudoh** [comment]
@vpicone is right on the general caveat around `gDSFP` and our internal discussion around it. To focus on @matthew-chirgwin's point - I found a bug in our `gDSFP` code where our logic to avoid applying min/max for non-number didn't work for empty space. I guess it led a confusion around `defaultValue` vs. `value` thing - Our `value` has been working to accept application-driven change since very early days of this library IIRC, and never changed since then.

**Comment by asudoh** [comment]
BTW another tip around this topic - The `onChange` fires every time user makes an edit in the input box, even when user may be hitting a backspace, etc. Some distinction around (immediate) UI component state vs. application state (of finished input) may help in this problem space.
