### ISSUE TITLE
Match multiselect to experimental spec

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon-components-react#2109]
Related:

https://github.com/IBM/carbon-components/pull/2181

https://github.com/IBM/carbon-components/pull/2207

https://github.com/IBM/carbon-components-react/issues/1611

depends on:
https://github.com/IBM/carbon-components-react/pull/2090
https://github.com/IBM/carbon-components-react/pull/2093
https://github.com/IBM/carbon-components/pull/2228
https://github.com/IBM/carbon-components-react/issues/2113
https://github.com/IBM/carbon-components/pull/2265

**Comment by emyarod** [comment]
because of the filterable multi select, this will depend on https://github.com/IBM/carbon-components-react/issues/2113

**Comment by laurenmrice** [comment]
not stale
