### ISSUE TITLE
[ComboBox] initialSelectedItem not working properly with dynamic state

### ISSUE THREAD

**Issue by mattdavenport** [carbon-design-system/carbon-components-react#2147]
## Summary
In trying to use the combo box, it seems to respond well with a set of `items` and an `initialSelectedItem` that are defined within the component. However, when fetching these initial values from the state, the component does not seem to actually set them properly. The `inputString` of the child `Downshift` component remains set until the component is clicked or tabbed/blurred through, however the initial item remains set even after inputString is cleared.

## Relevant information
This issue has been replicated in a code sandbox: https://codesandbox.io/s/wn1mwj8z6l

The first `ComboBox` has items and initialSelectedItem set from the state, the second has them set from the constants defined at the top of the file.

**Comment by mattdavenport** [comment]
Just verifying that you do not need any other information from my end. Thanks!

**Comment by mattdavenport** [comment]
Noting this issue is also present on the v10 of the `ComboBox` component.

**Comment by asudoh** [comment]
Hi :wave: my apologies for being late on this. Couldn't figure out what was expected vs. what was what you saw actually from your test case (especially given you have two same data/selection data), but if you simply expected that non-initial change in `initialSelectedItem` gets in effect, it wouldn't happen as the name tells.

We are aware of use cases in our numerous stateful components requiring application-initiated updates, and our internal discussions is leading to a conclusion that we should provide representational components so application can manage the states by their own. For combo box, it's `<ListBox*>` components found at https://github.com/IBM/carbon-components-react/blob/v7.1.0/src/components/ComboBox/ComboBox.js#L258-L312 - Hope this helps!

**Comment by mattdavenport** [comment]
Thanks for the information! I believe I'll just need to rearrange some things to get this component to hold the `initialSelectedItem` via state as I currently have it.

**Comment by mattdavenport** [comment]
I'd like to reopen this, as I've done some further digging and think this may be related to the use of an old version of the `Downshift` component.

To restate the issue (referencing the same codesandbox link from my original comment):
  - There are two versions of `supplierList` defined as items for the two examples of the `ComboBox` component. The issue here is with the `initialSelectedItem`.
  - The first instantiation uses a `supplierList` fetched from the state of the main component we're operating in (fetched async on component mount)
  - The second instantiation uses a locally defined `supplierList` within the component file itself (not fetched from API or external source).

The issue here, is that when tabbing through the form, the `ComboBox` component with the `initialSelectedItem` set from the state-fetched supplierList clears its value when the focus leaves the combobox. It turns out this happens in the `reset` method of the Downshift component. The Downshift prop `selectedItem` is never properly set in the case of passing the list of items through via state vs locally. What I expect to happen is the ComboBox using the state-supplied supplierList should be passed a proper `selectedItem` into its Downshift component similar to how the locally defined version does.

```javascript
  this.reset = function () {
    var otherStateToSet = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};
    var cb = arguments[1];

    otherStateToSet = pickState(otherStateToSet);
    _this4.internalSetState(function (_ref8) {
      var selectedItem = _ref8.selectedItem;
      return _extends({
        isOpen: false,
        highlightedIndex: _this4.props.defaultHighlightedIndex,
        inputValue: _this4.props.itemToString(selectedItem)
      }, otherStateToSet);
    }, cbToCb(cb));
  };
```
In the above code (Downshift component), `var selectedItem` is NULL in my first codesandbox `ComboBox` component, but is the proper item in the second example. Since these are passed to Downshift via ComboBox, I was wondering if you had any more insight here.

I'm wondering if this has something to do with these two issues:
https://github.com/downshift-js/downshift/issues/512
https://github.com/downshift-js/downshift/issues/243

Which were fixed in versions 2 and 3 of the `Downshift` component. If this is not the case, or you have any other ideas for setting both `items` and `initialSelectedItem` via API, would you please comment and/or re-close here?

Thanks!
