### ISSUE TITLE
Modal Wrapper throws unknown prop error on handleSubmit prop

### ISSUE THREAD

**Issue by Flyingcirc-Danger** [carbon-design-system/carbon-components-react#216]
The handleSubmit function that I provide is called, but the following error is also thrown.

![image](https://user-images.githubusercontent.com/7711697/30069927-fc08ba54-922f-11e7-8af6-1ec399708e9d.png)

handleSubmit is listed as a supported prop in the storybook for `Modal Wrapper`

**Comment by chrisdhanaraj** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/6b8b7163-1ec8-4616-82fa-aa467a17af03 "storybook-toolchain-v2"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/b84aaac8-8484-4a1e-902a-ebb526eb7998 "storybook-toolchain-v2") deployed [carbon-components-react](https://github.com/carbon-design-system/carbon-components-react/releases/tag/deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171011-005532 "deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171011-005532") to [Bluemix Design System](https://console.bluemix.net/apps/bc75a101-6472-481c-b48d-3eed1e9703f3?env_id=ibm:yp:us-south "ibm:yp:us-south:chrisdhanaraj_org:Bluemix Design System"), including commit a1a2dae17f31a3cd848bb0b18a2c5150f930eb3d
