### ISSUE TITLE
Focus on first item in overflow menu

### ISSUE THREAD

**Issue by Disha-Bendre** [carbon-design-system/carbon-components-react#2184]
## Detailed description

> Describe in detail the issue you're having.
First menu item is automatically focused, highlighted, and underlined. This styling appears even when hovering over other menu items. 
> Is this issue related to a specific component?
Bug appears for Carbon Overflow Menu
> What did you expect to happen? What happened instead? What would you like to see changed?
Expected behavior: Styling does not appear when clicking on the overflow menu. Style on first menu item _should_ appear when menu is opened using space or enter. 
> What browser are you working in?
Chrome 73.0
> What version of the Carbon Design System are you using?
Latest version of Carbon React Components
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Watson Assistant tooling
## Steps to reproduce the issue

1. Click on any overflow menu item - the first item will be focused/ highlighted/ underlined.
2. Hover over any other item in the menu. The first menu item will still be focused/ highlighted/ underlined.

## Additional information
Bug is visible in the Carbon React docs
http://react.carbondesignsystem.com/?selectedKind=OverflowMenu&selectedStory=basic&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel&knob-Dropdown%20type%20%28type%29=default&knob-Label%20%28label%29=Label&knob-Aria%20Label%20%28ariaLabel%29=Dropdown&knob-Button%20kind%20%28kind%29=primary&knob-Icon%20%28icon%29=none

**Comment by asudoh** [comment]
If I understand correctly what this issue is about - As discussed offline, there is a style for focus as well as a style for hovering-over, and it's intentional.

**Comment by dakahn** [comment]
Closing as resolved! Happy to reopen if that's not the case 🏄
