### ISSUE TITLE
OverflowMenu - it should be possible to disable component using a prop, like others components, e.g. Button

### ISSUE THREAD

**Issue by tomkdgun** [carbon-design-system/carbon-components-react#2194]
### Summary

OverflowMenu - it should be possible to disable component using a prop **disabled**, like in others components, e.g. Button

### Justification

We are not able to easily disable component, to prevent possibility to open it when clicked, and changing the appearance.

**Comment by asudoh** [comment]
Thanks @tomkdgun for reporting - While it sounds to make sense theoretically, would you share the concrete use case behind the notion of "disabled overflow menu"? Thanks!

**Comment by tomkdgun** [comment]
The parent component disables some children base on condition e.g. radio group selection, one of the disabled children component has OverflowMenu with actions assigned.

**Comment by asudoh** [comment]
@IBM/carbon-designers Does the notion of "disabling all components in a region" make sense? Thanks!

**Comment by tomkdgun** [comment]
Closing the issue just because there is no response from designers, is not the solution.

**Comment by aagonzales** [comment]
@tomkdgun so you're wanting to disable the overflow menu from opening at all not just single items inside of the overflow menu?

**Comment by tomkdgun** [comment]
> @tomkdgun so you're wanting to disable the overflow menu from opening at all not just single items inside of the overflow menu?

@aagonzales Yes, similar as button is disabled.

**Comment by aagonzales** [comment]
How would the user know what actions are inside the menu then? I'm not sure we want to allow that pattern. I think the user should open the menu and then just see actions/items themselves are disabled.

**Comment by tomkdgun** [comment]
@aagonzales In our case part of screen(widget) is conditionally disabled (not active). We would like to disable all pointer events, and possibility to focus OverflowMenu button using Tab key.

**Comment by aagonzales** [comment]
This sounds like an edge case. Do you have some screen flows to better show your scenario? At the moment I'm inclined to stay this wont be incorporated into the main library, I'm not sure we want to encourage this pattern. Anything could be in a overflow menu and if a user can't open it to see what's in it seems like poor ux choices (in the general scenario of what an overflow menu is meant for).

**Comment by tomkdgun** [comment]
@aagonzales We already applied workaround for this (custom CSS). You know my point. Do what you think is best.

**Comment by asudoh** [comment]
Closing as we don't think we should encourage this pattern and has a workaround. Anybody please be sure adding thumb-up to the issue description if you believe this should be in Carbon pattern, and add any background as a comment if it's there. Thanks!
