### ISSUE TITLE
v6.114 - FormLabel Icon targets input instead of opening Tooltip

### ISSUE THREAD

**Issue by jasesnider** [carbon-design-system/carbon-components-react#2206]
## Detailed description

> Describe in detail the issue you're having.

When using the FormLabel component with a tooltip, the tooltip icon will target the input field when present because the tooltip is wrapped within the label. The labelID is what targets the input field (a11y). 

If you separate the tooltip from the label, this breaks a11y as the label does not focus on the input field when selected. 

See CodeSandbox for demo. 

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

FormLabel and/or Tooltip if wrapped within a label or FormLabel component.

> What did you expect to happen? What happened instead? What would you like to see changed?

EXPECTED

I expected the label to target the input field on-click.
I expected the tooltip icon to open the tooltip on-click or with keyboard selection on Enter or Spacebar keypress.

ACTUAL

When I click on the tooltip icon, it focuses on the input field because the tooltip is wrapped in the label.

CHANGE

Possibly removing the wrapping of the label around the tooltip and wrap in React.Fragment and inline the tooltip (as child being passed) with the label. 

Let the labelId only pass to the label. Let the Tooltip component be passed as child prop of FormLabel

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

9.91.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Cloud - Genesis UI

## Steps to reproduce the issue

https://codesandbox.io/s/4rw75556o7

In the above link, do the following: 

1. Click on either the first or second tooltip icon. See that they target the input field.

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! I see that the CodeSandbox uses our interactive tooltip, which is meant only for putting interactive contents in tooltip. We are working with our designers on clarifying that: IBM/carbon-components#2307. For your use case I see definition tooltip is more suitable. Hope this helps!

**Comment by jasesnider** [comment]
Hey @asudoh So, I made a few additions checking out TooltipDefinition and TooltipIcon. We do need the info icon like the Tooltip component gives us (as well as the ability to use custom icons).

I added the labels, components and inputs for both the TooltipDefinition and TooltipIcon https://codesandbox.io/s/v6rzjrjp93

But we do have use cases in our UI for the interactive Tooltip component as we have content along with CTAs. It doesn't seem like TooltipDefinition and TooltipIcon gives us that.

Advice?

**Comment by asudoh** [comment]
My recommendation is getting your designer in sync with @IBM/carbon-designers on the use case of form field helper text. I imagine the UI our definition tooltip provides is the most suitable for that, but I may be wrong. If you have an agreement that your application can have a UI that is different from what our component provides, then I recommend you maintain your own component.

BTW not fully certain what you stumbled at with our icon tooltip, but it's worth noting that most of icon tooltip implementation is HTML/CSS. Our React code merely renders the HTML.

**Comment by dakahn** [comment]
Closing this as resolved 🏄
