### ISSUE TITLE
OverflowMenu open attribute does not open menu

### ISSUE THREAD

**Issue by hanhansen** [carbon-design-system/carbon-components-react#221]
`<a onClick={() => this.setState({ overFlowMenuOpen: true })}>{settingsLabel}</a>`

`<OverflowMenu open={this.state.overFlowMenuOpen}><OverflowMenuItem itemText='test'/></OverflowMenu>`

Setting open with a state variable sets the div attribute to open but doesn't add the proper classes to the parent or the <ul>

**Comment by joshblack** [comment]
Hi there! Having a hard time recreating this, it appears that the menu does get `bx--overflow-menu--open` class applied to it here: https://github.com/carbon-design-system/carbon-components-react/blob/master/src/components/OverflowMenu/OverflowMenu.js#L119 based off of state.

Going to close this issue for now, but feel free to re-open if I'm missing a step to reproduce!
