### ISSUE TITLE
AVT 3 - File Uploader: VoiceOver announces the file icon as "provide icon description, image"

### ISSUE THREAD

**Issue by snidersd** [carbon-design-system/carbon-components-react#2229]
## Environment
macOS Mojave version 10.14.2
Chrome version 72.0.3626.96 (Official Build) (64-bit)

## Detailed Description
Navigate using only the keyboard and add a jpg. or .png file
Navigate to the "X" icon
VoiceOver announces, "Provide icon description, image" (see screenshots
<img width="1296" alt="Screen Shot 2019-04-17 at 10 39 56 AM" src="https://user-images.githubusercontent.com/21676914/56304856-a0613780-6104-11e9-933c-5745a157fa2e.png">
)
<img width="405" alt="Screen Shot 2019-04-17 at 11 26 29 AM" src="https://user-images.githubusercontent.com/21676914/56304840-92131b80-6104-11e9-8fd3-f7b62eaa629b.png">

## Expected result:
VoiceOver would announce the purpose of the button, such as "Remove file".

Title needs to be changed so that it matches the purpose of the icon/button.

**Comment by snidersd** [comment]
This issue should remain open until it is fixed and retested.

**Comment by dakahn** [comment]
That attribute is unique to the demonstration. In implementation a more specific description. Like "remove selected file" or "delete PDF" -- there's also the need for globalization which happens in implementation.
