### ISSUE TITLE
AccordionItem Content Consumes Space When Closed, Causing Scrollbars

### ISSUE THREAD

**Issue by justindm234** [carbon-design-system/carbon-components-react#2231]
## Detailed description

> Describe in detail the issue you're having.

Content within a closed AccordionItem consume space on the page, causing scrollbars

> Is this issue related to a specific component?

AccordionItem

> What did you expect to happen? What happened instead? What would you like to see changed?

Closed AccorionItem content should not consume space (display: none); Instead content consume space (visibility: hidden)

> What browser are you working in?

Chrome Win10, Firefox Win10, Edge Win10, Chrome RHEL 7 (Should affect all browsers)

> What version of the Carbon Design System are you using?

7.1.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Release not announced yet

## Steps to reproduce the issue

1. Make an AccordionItem whose content would cause the page to scroll
2. Close the AccordionItem and page still scrolls

https://codesandbox.io/s/nry88p5z3m

**Comment by asudoh** [comment]
Hi @justindm234 thank you for reporting! It appears that the style you pointed out is for enabling the animation. As you may have imagined, you can override the style to work around the issue. Hope it clarifies things.

**Comment by dakahn** [comment]
Closing this as resolved, but happen to reopen if that's not the case 🏄
