### ISSUE TITLE
Dropdown can't use the up and down key to navigate the list

### ISSUE THREAD

**Issue by lilyclyc** [carbon-design-system/carbon-components-react#224]
When enter the dropdown to open it, then try to use the up and down key to navigate the list but not  work at all. And if using the tab key that will work fine.

**Comment by lilyclyc** [comment]
@hellobrian -- any updates?

**Comment by hellobrian** [comment]
I’ll leave this up to the team to decide if or when they want to include this functionality. IMO, using tab key is enough.

**Comment by joshblack** [comment]
We're bringing in some experimental work with Combo boxes that will end up updating the Dropdown to use https://github.com/paypal/downshift which should help resolve this! Will make sure to link this with the PR when it's up 😄

**Comment by joshblack** [comment]
Going to be addressed with the work relevant in #332. Closing this for now, feel free to re-open if the work being brought in through those PRs won't address this issue!
