### ISSUE TITLE
DatePicker in range mode in Vanilla JS vs Any other example

### ISSUE THREAD

**Issue by trusinaj** [carbon-design-system/carbon-components-react#2292]
Hey IBM,

is there a way to make date picker in range mode work in React same way it does in Vanilla JS?
I was checking your Vanilla JS exmaple and it works nice and same way as Flatpicker, but React example and any other have this strange behaviour thats kinda wierd.

Im sorry if there is already thread about this, I couldnt find it. Thanks

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! As the matter of fact, Carbon has different design from what Flatpickr provides out-of-the-box, which requires several non-straightforward tweaks communicating to Flatpickr code. Those have yielded several issues and I believe what you saw is one of them - Good to hear any specifics you have.

We have reported a couple of issues to Flatpickr repo so we can eliminate such non-straightforward tweaks: flatpickr/flatpickr#1684 and flatpickr/flatpickr#1693. We are monitoring those so we can solve those issues.

Closing for now as #1014 seems very close to the subject.
