### ISSUE TITLE
DatePicker should pass openCalendar prop to deeply nested DatePickerInput element

### ISSUE THREAD

**Issue by SpearThruster** [carbon-design-system/carbon-components-react#2311]
When trying to wrap `DatePicker` with `DatePickerInput` using `Formik` form handling library the calendar can't be opened.

```
<DatePicker onChange={onChange} datePickerType="range" dateFormat="The date format (dateFormat in <DatePicker>)">
    <Field
      name={startName}
      render={({ field, form, ...rest }: any) => (
        <DatePickerInput
          name={startName}
          id="date-picker-input-id-start"
          {...field}
          onChange={event => form.setFieldValue(field.name, event.target.value)}
          invalid={!!form.errors[startName]}
          invalidText={form.errors[startName]}
          {...rest}
        />
      )}
    />
    <Field
      name={endName}
      render={({ field, form, ...rest }: any) => (
        <DatePickerInput
          name={endName}
          id="date-picker-input-id-end"
          onChange={event => form.setFieldValue(field.name, event.target.value)}
          invalid={!!form.errors[endName]}
          invalidText={form.errors[endName]}
        />
      )}
    />
```

The problem is here I presume -> https://github.com/carbon-design-system/carbon-components-react/blob/master/src/components/DatePicker/DatePicker.js#L440

You need to recursively traverse all children -> if one of them is a `DatePickerInput` -> pass the `openCalendar` prop to the children.

**Comment by asudoh** [comment]
Hi 👋 thank you for reporting! You are right that our `<DatePicker>` relies on `<DatePickerInput>` being direct child. Such reliance is not only about `openCalendar` thing but also about our logic grabbing from/to `<input>`.

OTOH you'll find that our entire `<DatePicker>` code is almost merely wrapping Flatpickr library. Creating your own sounds the quickest way to meeting your particular requirement for the time being.

**Comment by SpearThruster** [comment]
Hi @asudoh 

Thanks for the feedback. Is this use case something you are willing to support in `carbon-components-react`?

**Comment by asudoh** [comment]
I have come up with some options to support this but none of them are straightforward, especially considering backward-compatibility and API cleanness. That's why I suggested creating your own for the time being.

**Comment by dakahn** [comment]
I'll close this as resolved since it seems like we're not supporting this use case. Thanks all! 🏄
