### ISSUE TITLE
Slider can't slide properly when min is different than 0 

### ISSUE THREAD

**Issue by ereneld** [carbon-design-system/carbon-components-react#233]
Slider component is not sliding and behaving properly when min value is different than 0.  

Calculation should be fix. 

Exp. Trying with min value: 50 , max value: 100, when you slide the value is not changing until you hit the middle area, and there will be gap.

**Comment by tw15egan** [comment]
This seems to be resolved in the latest version of the components, please reopen if you feel this was closed in error.
