### ISSUE TITLE
FileUploader react component uses btn--primary, vanilla component uses btn--secondary 

### ISSUE THREAD

**Issue by keithkade** [carbon-design-system/carbon-components-react#235]
We are using the FileUploader [react component](https://github.com/carbon-design-system/carbon-components-react/blob/master/components/FileUploader.js) and want it to be styled as a secondary button like the [vanilla component](http://carbondesignsystem.com/components/file-uploader/code)

Not sure if the discrepancy was intentional. If so, can we allow overriding via prop?

**Comment by tw15egan** [comment]
Good chance this was intentional, I'll let @bsonefeld answer that from a UX perspective.

**Comment by bsonefeld** [comment]
Hey @keithkade , you can have it styled as a primary or a secondary button, whichever you prefer 👍

**Comment by keithkade** [comment]
We want it styled as secondary. Do you care if we change the react component to always use secondary, or should I make that a settable via prop?

**Comment by tw15egan** [comment]
@keithkade we'd probably want this to be a prop, as some people may still want to use it as a primary button

**Comment by keithkade** [comment]
@tw15egan sounds good. I'll make a PR

**Comment by tw15egan** [comment]
@keithkade thanks! 👍
