### ISSUE TITLE
Notification remained closed after clicking close button

### ISSUE THREAD

**Issue by Kenzku** [carbon-design-system/carbon-components-react#237]
Hej,

if I click close button in notification, the notification will not show again in the same page.

looks like the `state.open` has been set to `false`, unless the page is getting refreshed.

**Comment by marijohannessen** [comment]
Can you provide some more information on how to replicate this bug? Like what type of notification, etc?

**Comment by marijohannessen** [comment]
Closing this issue due to our inactivity policy. Please feel free to re-open if needed.
