### ISSUE TITLE
'ToolbarItem' is not exported from 'carbon-components'.

### ISSUE THREAD

**Issue by zbeedatm** [carbon-design-system/carbon-components-react#2378]
I'm new to react and trying to use the ToolBar component.
Tried following Guide steps but I'm getting the following:

> Attempted import error: 'ToolbarItem' is not exported from 'carbon-components'.

`import Toolbar, {
  ToolbarItem,
  ToolbarTitle,
  ToolbarOption
} from 'carbon-components';`

**Comment by zbeedatm** [comment]
This is how I managed finally:

`//import { storiesOf } from '@storybook/react';
//import { action } from '@storybook/addon-actions';
import { action, decorateAction } from "@storybook/addon-actions"
import Filter16 from '@carbon/icons-react/lib/filter/16';
import {
  Toolbar,
  ToolbarItem,
  ToolbarTitle,
  ToolbarOption
} from 'carbon-components-react';
import {Checkbox, OverflowMenu} from 'carbon-components-react';

const toolbarProps = {
  className: 'some-class',
};

const inputProps = {
  className: 'some-class',
  onChange: action('onChange'),
};`

**Comment by emyarod** [comment]
yup as you discovered, the React components are exported from `carbon-components-react`

just as an FYI, unless you need the legacy components, the project has moved to https://github.com/carbon-design-system/carbon (`@carbon/components` and `@carbon/react`)
