### ISSUE TITLE
Data tables rendering without styles in v10.2.0?

### ISSUE THREAD

**Issue by ppedemon** [carbon-design-system/carbon-components-react#2381]
Hi. Using carbon-components-react `v10.2.0` here. 

Maybe caused by a regression, `DataTable`s are being rendered again without styling:

![image](https://user-images.githubusercontent.com/1747003/58293576-67b81c00-7d9c-11e9-8384-9fa205f5141f.png)

I see the HTML references `v2` CSS classes, e.g. `bx--data-table-v2-container` and `bx--data-table-v2-header`. However, as far as I can see those classes are not provided in the distribution. Thus the rendering above.

If I'm forgetting to import something, please let me know (and sorry in advance).

**Comment by asudoh** [comment]
Hi 👋 the `v7.2.0` release seems to include carbon-components-react#2127, which seems to refer to non-`v2` class. Does it give you some insights?

**Comment by ppedemon** [comment]
> Hi 👋 the v7.2.0 release seems to include carbon-components-react#2127, which seems to refer to non-v2 class. Does it give you some insights?

Sorry, but no. Are you implying I should migrate to the older `v7.2.0` release of carbon-components-react?

**Comment by asudoh** [comment]
There is no `v10` release in our React variant. `v7` version of our React variant corresponds to Carbon `v10`. Hope it clarifies things!

**Comment by ppedemon** [comment]
My mistake! I mixed up `carbon-components-react` and `carbon-components` versions. I see now. Thanks so much.
