### ISSUE TITLE
OrderSummaryHeader --> Dropdown does not seem to respect changes to selectedText

### ISSUE THREAD

**Issue by zeusorion** [carbon-design-system/carbon-components-react#241]
Dropdown does not seem to reflect changes in the `selectedText` prop. I have it set to a `state` prop to change whenever the state in my component changes.

Code Sandbox

https://codesandbox.io/s/pkyp3mx8kx

**Comment by chrisdhanaraj** [comment]
Hmm, I'm probably missing something but it looks liek the selectedText is changing based on your onClick?

**Comment by zeusorion** [comment]
from the sample code in the sandbox on the above link, the `selectedText` should be getting set by `selectedText={this.state.lblFrequency}` on onClick. I've mimicked the changing of the state property `this.state.lblFrequency` on a timeout function. Not sure where the `onClick` that you are referring comes from. My goal is to set/change the DropdownItem by setting the `this.state.lblFrequency`

**Comment by chrisdhanaraj** [comment]
Ahh, I see what's going on - I think you're right, there's some wonkiness with the Dropdown component. You can do something like this though for now utilizing the onCHange

https://codesandbox.io/s/r7oj827jwo

**Comment by chrisdhanaraj** [comment]
But you're right, it's applying its own internal state versus respecting the selectedText prop always. Taking a look at the Dropdown component shows that we probably need to clean that code up

**Comment by zeusorion** [comment]
not following how your proposal helps: You code sample requires/assumes a manual change from the user to the dropdownitems, correct?
What I would like is a way to programmatically set the option without user interaction.

**Comment by zeusorion** [comment]
@chrisdhanaraj any updates on this? Not sure if I followed your proposal--see my last comment above.

**Comment by tonitagd** [comment]
I am also having issues with the selectedText property. This property does not affect the value during render.
Should we expect a fix for this?

**Comment by tw15egan** [comment]
Issue is currently in our backlog, but if you have a quick fix for it we would welcome a PR

**Comment by tonitagd** [comment]
With which version of the carbon-components-react will this change come?

**Comment by tw15egan** [comment]
@tonitagd it was included in the `3.13.3` release
