### ISSUE TITLE
ToolTip: triggerText should not be defaulted to content

### ISSUE THREAD

**Issue by WilliamHolmes** [carbon-design-system/carbon-components-react#242]
Component: **ToolTip**

property | propType | required | default
------------ | ------------- | ------------- | -------------
triggerText | string | no | "'Provide triggerText'"

The required `no` is a little confusing.

If we do not supply the `triggerText` prop, some default text `Provide triggerText` is used.

If you do not want to show this default text, then we either have to supply an empty string OR use styles to hide it. `<Tooltip triggerText={''}>`

IMO: The required field should stay as `no`, and if no `triggerText` prop is passed, no text should be shown.

**UPDATE**
I noticed the same issue for other components such as `Modal`

**Comment by marijohannessen** [comment]
PR open for this https://github.com/carbon-design-system/carbon-components-react/pull/301

**Comment by joshblack** [comment]
Let's close this in favor of #299 and treat that as the umbrella for `defaultProps` behavior. Feel free to re-open if that issue doesn't encapsulate the issue you noted! Both should still be resolved by #301 😄
