### ISSUE TITLE
Tabs: passing selected does not trigger tabs re-selected

### ISSUE THREAD

**Issue by Kenzku** [carbon-design-system/carbon-components-react#243]
If I pass down a number e.g. 1 as a initial value for `selected = 1` in `Tabs`, then later, when I reset the state, e.g. `this.state.selectedTabIndex=2`, the selected tab will not update itself to position 2.

```es6
let items = tabList.map(v =>
        /*Another defect: Carbon defect: Due to Tabs and Tab component needs to be directed connected, otherwise, handleTabClick function cannot be resolved*/
        (
          <Tab label={v} key={v}>
            <MyItem task={task} itemName={v}/>
          </Tab>
        )
      );
      returnContent = (
        <Tabs selected={this.state.selectedTabIndex}>
          {items}
        </Tabs>
      );
```

**Comment by joshblack** [comment]
Looks like this was fixed in https://github.com/carbon-design-system/carbon-components-react/pull/471. Feel free to re-open if this was not the case!
