### ISSUE TITLE
Accessibility of expanded property of Table component

### ISSUE THREAD

**Issue by dcostantino** [carbon-design-system/carbon-components-react#244]
The expand icon on tables does not seem accessible, tab does not tab to the icon in the table to expand the row.

**Comment by chrisdhanaraj** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/6b8b7163-1ec8-4616-82fa-aa467a17af03 "storybook-toolchain-v2"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/b84aaac8-8484-4a1e-902a-ebb526eb7998 "storybook-toolchain-v2") deployed [carbon-components-react](https://github.com/carbon-design-system/carbon-components-react/releases/tag/deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171013-150203 "deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171013-150203") to [Bluemix Design System](https://console.bluemix.net/apps/eedd7692-913e-4285-a4eb-a66e1d1e7c2d?env_id=ibm:yp:us-south "ibm:yp:us-south:chrisdhanaraj_org:Bluemix Design System"), including commit b48a8aa608714b0234f35496ebd271b8e3faf9e2
