### ISSUE TITLE
Search Component - The WAI-ARIA widget with img must have alternate text or label

### ISSUE THREAD

**Issue by JoshDKing** [carbon-design-system/carbon-components-react#247]
The WAI-ARIA widget with img role must have a nonempty alternate text or label.  This occurs in the Search Component.  Violation found when running the Dynamic Assessment Plugin.
<img width="81" alt="screen shot 2017-09-29 at 12 39 11 am" src="https://user-images.githubusercontent.com/22154713/31002267-389cdc3e-a4af-11e7-95b6-de3beacecccc.png">
:
https://aat.w3ibm.mybluemix.net/token/61ceb465-62b2-4b77-b4c4-2c9fcedb9484/a575231d-4929-440a-8215-3b0f77ec2188/archives/2017AugustDeploy//doc/w3/help/en-US/idhi_accessibility_check_g1128.html

**Comment by joshblack** [comment]
Hi there! 👋 

Thanks so much for taking the time to submit an issue, especially for a11y compliance! We really appreciate it 😄 .

To help us figure out what the exact issue is, could you provide some more details about the usage of the Search component, specifically the steps that you took that result in the DAP violation you shared in your post?

**Comment by marijohannessen** [comment]
Closing because of idle issue policy. Please feel free to re-open if needed.
