### ISSUE TITLE
ToolTip Component - The WAI-ARIA widget with img must have alternate text or label 

### ISSUE THREAD

**Issue by JoshDKing** [carbon-design-system/carbon-components-react#248]
The WAI-ARIA widget with img role must have a nonempty alternate text or label. This occurs in the ToolTip Component. Violation found when running the Dynamic Assessment Plugin.
https://aat.w3ibm.mybluemix.net/token/61ceb465-62b2-4b77-b4c4-2c9fcedb9484/a575231d-4929-440a-8215-3b0f77ec2188/archives/2017AugustDeploy//doc/w3/help/en-US/idhi_accessibility_check_g1128.html
<img width="88" alt="screen shot 2017-09-29 at 1 00 46 am" src="https://user-images.githubusercontent.com/22154713/31002672-a8c03a90-a4b1-11e7-80bb-482c37164441.png">

**Comment by marijohannessen** [comment]
Hi! An SVG element can't have an alternative text or label since it is not an image, so instead, it has an `aria-label` and a `title` which makes it fully accessible. This is a great article explaining it further if you're interested in learning more https://css-tricks.com/accessible-svgs/.
