### ISSUE TITLE
Pagination Component - The WAI-ARIA widget with img must have alternate text or label

### ISSUE THREAD

**Issue by JoshDKing** [carbon-design-system/carbon-components-react#249]
The WAI-ARIA widget with img role must have a nonempty alternate text or label. This occurs in the Pagination Component. Violation found when running the Dynamic Assessment Plugin.
https://aat.w3ibm.mybluemix.net/token/61ceb465-62b2-4b77-b4c4-2c9fcedb9484/a575231d-4929-440a-8215-3b0f77ec2188/archives/2017AugustDeploy//doc/w3/help/en-US/idhi_accessibility_check_g1128.html
The three "dots" menu options
<img width="64" alt="screen shot 2017-09-29 at 1 09 37 am" src="https://user-images.githubusercontent.com/22154713/31002962-e62f54a0-a4b2-11e7-9785-f0fd84bcec8e.png">
Both the left and right carot
<img width="146" alt="screen shot 2017-09-29 at 1 09 33 am" src="https://user-images.githubusercontent.com/22154713/31002967-e7914934-a4b2-11e7-9cae-80f8ab7c6cf6.png">
The drop down carot
<img width="49" alt="screen shot 2017-09-29 at 1 09 26 am" src="https://user-images.githubusercontent.com/22154713/31002971-e914c65a-a4b2-11e7-895f-4d1d562812bf.png">

**Comment by marijohannessen** [comment]
Hi! An SVG element can't have an alternative text or label since it is not an image, so instead, it has an `aria-label` and a `title` which makes it fully accessible. This is a great article explaining it further if you're interested in learning more https://css-tricks.com/accessible-svgs/.
