### ISSUE TITLE
Icon does not add keys to paths

### ISSUE THREAD

**Issue by jlengstorf** [carbon-design-system/carbon-components-react#250]
In the Icon component, no `key` prop is added to generated icons, which causes an error.

It happens in [the `svgShapes` function](https://github.com/carbon-design-system/carbon-components-react/blob/master/components/Icon.js#L68-L80).

I'll send a PR shortly.

**Comment by chrisdhanaraj** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/6b8b7163-1ec8-4616-82fa-aa467a17af03 "storybook-toolchain-v2"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/b84aaac8-8484-4a1e-902a-ebb526eb7998 "storybook-toolchain-v2") deployed [carbon-components-react](https://github.com/carbon-design-system/carbon-components-react/releases/tag/deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171011-005532 "deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171011-005532") to [Bluemix Design System](https://console.bluemix.net/apps/bc75a101-6472-481c-b48d-3eed1e9703f3?env_id=ibm:yp:us-south "ibm:yp:us-south:chrisdhanaraj_org:Bluemix Design System"), including commit 1b0ec294d3e04be957eaaeb1f6b7f4a8a7fcf500
