### ISSUE TITLE
InteriorLeftNav passes invalid onClick prop

### ISSUE THREAD

**Issue by jlengstorf** [carbon-design-system/carbon-components-react#252]
A warning is being issued for invalid props in InteriorLeftNav:

```
warning.js?6327:33 Warning: Expected `onClick` listener to be a function, instead got a value of `boolean` type.
    in nav (created by InteriorLeftNav)
    in InteriorLeftNav
```

For some reason, [the toggle function is only added if `!this.state.open`](https://github.com/carbon-design-system/carbon-components-react/blob/master/components/InteriorLeftNav.js#L123). I'm not sure of the history or what this is supposed to do, so my fix may not be correct, but I'm thinking this could be:

```diff
      <nav
        role="navigation"
        aria-label="Interior Left Navigation"
        className={classNames}
-       onClick={!this.state.open && this.toggle}
+       onClick={!this.state.open ? this.toggle : () => {}}
        {...other}
      >
```

If someone wants to confirm, I'll submit the PR.

**Comment by chrisdhanaraj** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/6b8b7163-1ec8-4616-82fa-aa467a17af03 "storybook-toolchain-v2"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/b84aaac8-8484-4a1e-902a-ebb526eb7998 "storybook-toolchain-v2") deployed [carbon-components-react](https://github.com/carbon-design-system/carbon-components-react/releases/tag/deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171011-005532 "deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171011-005532") to [Bluemix Design System](https://console.bluemix.net/apps/bc75a101-6472-481c-b48d-3eed1e9703f3?env_id=ibm:yp:us-south "ibm:yp:us-south:chrisdhanaraj_org:Bluemix Design System"), including commit ff69e0af707d8107ea8c170d88b2bd7b2a99fe69
