### ISSUE TITLE
Allow Checkbox label to be an element or string

### ISSUE THREAD

**Issue by dcostantino** [carbon-design-system/carbon-components-react#254]
Remove the error from type checking of the labelText of a checkbox if it is an element. To allow icons or svg to be part of checkbox text.

**Comment by valZho** [comment]
+1 ... I would add, that this allows "strings" with internal links or styling, too.

**Comment by joshblack** [comment]
Should be implemented as of v5.6.0 when the PropType was updated to be `node`!

https://github.com/carbon-design-system/carbon-components-react/commit/1924e19abd52e4127c0044a4b10bed8b5b120665
