### ISSUE TITLE
FloatingMenu doesn't calculate the position correctly with scrollbar

### ISSUE THREAD

**Issue by ycao56** [carbon-design-system/carbon-components-react#257]
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/16092291/31181941-91961572-a8f0-11e7-9b09-2e0ebdd47a66.png">

**Comment by marijohannessen** [comment]
Can you please provide some steps we can take to replicate this issue? Thanks!

**Comment by marijohannessen** [comment]
Closing this issue due to our inactivity policy. Please feel free to re-open if needed.
