### ISSUE TITLE
DatePicker with calendar 'single' fires onChange with an empty array instead of the selected date

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-components-react#260]
If I create a DatePicker of the single type to allow selection from a calendar, the onChange event that fires contains an empty arguments as its value instead of an actual event.

To reproduce see the storybook link below.  Clear the events section and use the calendar to pick a date.  Notice the onChange event is an empty array.

See this link: 
http://react.carbondesignsystem.com/?selectedKind=DatePicker&selectedStory=single%20with%20calendar&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel

**Comment by joshblack** [comment]
Thanks for taking the time to write out the steps to reproduce! Super helpful.

Confirmed that the issue exists, will try and get this prioritized for a bug fix.

**Comment by marijohannessen** [comment]
Resolved in https://github.com/carbon-design-system/carbon-components-react/pull/419
