### ISSUE TITLE
Server-side rendering broken with newest release

### ISSUE THREAD

**Issue by jmeis** [carbon-design-system/carbon-components-react#262]
Running `npm run test-ssr` is broken on the current branch.

```
/Users/jmeis/Desktop/carbon-components-react/node_modules/flatpickr/dist/flatpickr.js:60
    animate: window && window.navigator.userAgent.indexOf("MSIE") === -1,
             ^

ReferenceError: window is not defined
    at /Users/jmeis/Desktop/carbon-components-react/node_modules/flatpickr/dist/flatpickr.js:60:14
    at Object.assign.i (/Users/jmeis/Desktop/carbon-components-react/node_modules/flatpickr/dist/flatpickr.js:3:82)
    at Object.<anonymous> (/Users/jmeis/Desktop/carbon-components-react/node_modules/flatpickr/dist/flatpickr.js:6:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

The issue is that `flatpickr` released some breaking changes on a minor version. Setting `flatpickr` to an absolute version resolves the issue. Will submit a PR to fix this.

**Comment by joshblack** [comment]
Closed by #263

**Comment by germanattanasio** [comment]
@joshblack Can we make `npm run test-ssr` be part of Travis? @nfriedly wrote that test to prevent this library from breaking server-side rendering.

**Comment by joshblack** [comment]
@germanattanasio I believe it's a part of the CI process already: https://github.com/carbon-design-system/carbon-components-react/blob/master/package.json#L9

I think this issue came about due to a transient dependency publishing a breaking change within a minor version. To help prevent this in the future, I'm trying to recommend freezing package versions so we don't run into this issue again.

Let me know if I'm mistaken/misinterpret what you're asking! 😄

**Comment by chrisdhanaraj** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/6b8b7163-1ec8-4616-82fa-aa467a17af03 "storybook-toolchain-v2"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/b84aaac8-8484-4a1e-902a-ebb526eb7998 "storybook-toolchain-v2") deployed [carbon-components-react](https://github.com/carbon-design-system/carbon-components-react/releases/tag/deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171011-005532 "deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20171011-005532") to [Bluemix Design System](https://console.bluemix.net/apps/bc75a101-6472-481c-b48d-3eed1e9703f3?env_id=ibm:yp:us-south "ibm:yp:us-south:chrisdhanaraj_org:Bluemix Design System"), including commit 28439973b4f1d22f204b6cc425be71fc80bc2b37
