### ISSUE TITLE
OverflowMenu pop-up positioning

### ISSUE THREAD

**Issue by jzhang300** [carbon-design-system/carbon-components-react#27]
![screen shot 2017-06-14 at 12 54 31 pm](https://user-images.githubusercontent.com/1449523/27146938-a74982c0-5100-11e7-8eac-e57496e3d913.jpg)

I believe the positioning of the OverflowMenu pop-up used to be smarter in where to position the pop-up, but now positioning is off.

**Comment by hellobrian** [comment]
I haven't been able to reproduce this issue. 
If this is still an issue, can you reproduce here in codesandbox (link below), then we can re-open this:

[![Edit Carbon React Starter](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/Kr4zVEkBr)
