### ISSUE TITLE
The Iconography page does not load the icons

### ISSUE THREAD

**Issue by slc7035** [carbon-design-system/carbon-components-react#270]
![image](https://user-images.githubusercontent.com/2317818/31390654-79919f58-ada2-11e7-840f-5dfcb1d25f70.png)

**Comment by eddiemonge** [comment]
This should be opened on the [Carbon Components](https://github.com/carbon-design-system/carbon-components) repo or more likey the [Design System Website](https://github.com/carbon-design-system/design-system-website)

**Comment by joshblack** [comment]
Thanks so much for taking the time to report this issue! While I don't have access to the system that serves the icons, I'll make sure to bug @chrisdhanaraj to fix this 😄

**Comment by chrisdhanaraj** [comment]
This has been fixed, thanks for the report! As a sidebar, as @eddiemonge mentioned, design system website bugs should go to that repo https://github.com/carbon-design-system/design-system-website
