### ISSUE TITLE
Dropdown height is greater than TextInput

### ISSUE THREAD

**Issue by AsthaJain1** [carbon-design-system/carbon-components-react#271]
As per carbon components, both should be 2.5rem. Dropdown appears to be 42px that is 2.625rem.

![image](https://user-images.githubusercontent.com/21059894/31404354-cf56cf40-adc9-11e7-9625-e7b08f25cd7a.png)

**Comment by miramurali23** [comment]
<span className="bx--slider__range-label">{max}{maxLabel}</span>
have to put a space between {max} and {maxLabel}

**Comment by eddiemonge** [comment]
This needs to be fixed in https://github.com/carbon-design-system/carbon-components as its using the CSS from there.

**Comment by joshblack** [comment]
Moved over to carbon-components https://github.com/carbon-design-system/carbon-components/issues/355
