### ISSUE TITLE
Slider input field accepts letters and numbers...for usage we only want input field to accept numbers

### ISSUE THREAD

**Issue by miramurali23** [carbon-design-system/carbon-components-react#278]
Hello, everyone! As of now, the carbon slider input field accepts letters..I am working on fixing this...but if anyone could help me that would be great!

**Comment by miramurali23** [comment]
<img width="502" alt="screen shot 2017-10-12 at 2 57 31 pm" src="https://user-images.githubusercontent.com/11800028/31516306-c00885ca-af5d-11e7-97dd-d99214ca6cfa.png">

**Comment by miramurali23** [comment]
<img width="502" alt="screen shot 2017-10-12 at 2 57 31 pm" src="https://user-images.githubusercontent.com/11800028/31516318-cf5a06fc-af5d-11e7-84df-139537be936a.png">

**Comment by miramurali23** [comment]
Thanks for the response TJ, am working on it, but if anyone else feels like they could quickly fix this issue feel free to work on this as well :)

**Comment by jamesvclements** [comment]
Hey I opened a [PR](https://github.com/carbon-design-system/carbon-components/pull/367) on Carbon Components for this. Styles had to be added to remove the increment decrement arrows so I figured it had to be done there

**Comment by tw15egan** [comment]
Just going to keep this open until the changes are reflected in this repo
