### ISSUE TITLE
BreadcrumbItem component should accept react-router Links

### ISSUE THREAD

**Issue by oliverodaa** [carbon-design-system/carbon-components-react#279]
We recently added the `<Breadcrumb>` component to our app. It initially worked fine, until we implemented `react-router`.

We would like the `<BreadcrumbItem>` component to work with `react-router` links, and not strictly `<a>` tags.

-------

We have code something like this:
```
import { Link } from 'react-router-dom';
import { Breadcrumb, BreadcrumbItem } from 'carbon-components-react';

...

<Breadcrumb>
  <BreadcrumbItem>
    <Link to="/documents">All documents</Link>
  </BreadcrumbItem>
</Breadcrumb>
```

Which causes the following warning:

```
Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
    in a
    in Link
    in a
    in Link
    in div
    in BreadcrumbItem
    in div
    in Breadcrumb
```

**Comment by oliverodaa** [comment]
I suggest something like this to fix it:
```
const BreadcrumbItem = ({ children, className, href, ...other }) => {
  const classNames = classnames('bx--breadcrumb-item', className);
  return (
    <div className={classNames} {...other}>
      {
        href ?
        (<Link href={href}>children</Link>) :
        (children)
      }
    </div>
  );
};
```

**Comment by joshblack** [comment]
Thanks for reporting! @oliverodaa 😉 

Definitely agree that this is needed, will try and brainstorm the best way to allow outside routers to hook into the breadcrumb item so that the warning isn't generated 👌

**Comment by oliverodaa** [comment]
Awesome! In order to get these changes into my project (we use NPM), I'll need to wait for the next release, right? Is the #carbon-react Slack channel the best way to hear about new releases?

**Comment by tw15egan** [comment]
@oliverodaa Should be bundled in with the latest `v5.7.3` release: https://github.com/carbon-design-system/carbon-components-react/releases 👍

**Comment by acao** [comment]
the latest release does not seem to contain an actual `react-router-dom` `<Link />` component, but rather uses a carbon `<Link />` which is just an anchor element.

can we have a `withLink` prop that expects a function or component, so one could provide a component in place of the `<Link />` anchor element?

**Comment by oliverodaa** [comment]
@acao I read that file just now. If I'm understanding it correctly, in the case where `href` is undefined or `typeof children !== 'string'`, then `children` gets rendered, not inside of any kind of `<Link>`. That would achieve what you want, I think, since you can put whatever you want in `children`.

**Comment by acao** [comment]
Ohhh!!! Very clever, I see now, thanks for the rapid response!
