### ISSUE TITLE
DetailPageHeader's Status Text has no spacing

### ISSUE THREAD

**Issue by jzhang300** [carbon-design-system/carbon-components-react#28]
![screen shot 2017-06-14 at 1 46 25 pm](https://user-images.githubusercontent.com/1449523/27149044-f2cbd912-5107-11e7-886a-cea855a587bc.jpg)

The `.bx--detail-page-header-status-text` element is missing spacing from the status icon for some reason.

---

- [ ] figure out where inconsistency is between Carbon Components and Carbon React.

**Comment by hellobrian** [comment]
I just took a look at this and I'm actually not sure why the React component has no spacing but the Vanilla component does. We may just have to add an empty space between the icon and statusText.

```jsx
<div style={statusStyles} className="bx--detail-page-header-status-icon" />
{' '}
<span className="bx--detail-page-header-status-text">
  {statusText}{statusContent}
</span>
```
