### ISSUE TITLE
Upgrade to React@16

### ISSUE THREAD

**Issue by eddiemonge** [carbon-design-system/carbon-components-react#280]
Upgrade to React@16

- [ ] react
- [ ] react-dom
- [x] react-test-renderer
- [ ] react-addons-css-transition-group (???)
- [x] Enzyme
- [ ] enzyme-adapter-react-16

Update test setup to use enzyme adapter

**Comment by joshblack** [comment]
Good call, will try and bump this up in priority.

I have work for updating the test suite for enzyme@3, just am waiting for reviews for #258 and #265 and then will create that PR.

**Comment by joshblack** [comment]
Just an update, #258 and #265 are merged and am now making the PR for the enzyme updates.

**Comment by joshblack** [comment]
PR for update to enzyme #282

**Comment by sppatel** [comment]
Do you think this effort will be completed by 4Q?

**Comment by joshblack** [comment]
@sppatel for sure! Right now the biggest blocker has been enzyme not supporting React 16 portals, so we need to find a solution in the meantime to get over this hurdle.
