### ISSUE TITLE
Default values for gauage component are always visible

### ISSUE THREAD

**Issue by vidyakhadsareibm** [carbon-design-system/carbon-components-react#281]
Default values for amount and total (75 out of 100GB) are always visible. There was a requirement to hide those values because we dont have valid data to be displayed right now.

<img width="1564" alt="screen shot 2017-10-12 at 3 55 42 pm" src="https://user-images.githubusercontent.com/32777878/31559898-1f8c6ab2-b007-11e7-9335-ed2042fc950d.png">

**Comment by tw15egan** [comment]
@vidyakhadsareibm, this issue deals with the `carbon-addons-data-viz-react` repo, so I'm going to move this issue over there.

**Comment by tw15egan** [comment]
Issue moved to [carbon-design-system/carbon-addons-data-viz-react #38](https://github.com/carbon-design-system/carbon-addons-data-viz-react/issues/38) via [**ZenHub**](https://www.zenhub.com/)
