### ISSUE TITLE
Cannot grab selected date from DatePicker component in Firefox

### ISSUE THREAD

**Issue by chr1stinayan** [carbon-design-system/carbon-components-react#286]
For the DatePicker component, I'm using `onChange={() => {this.onChange()}}`to call the onChange  function and `event.target.dateObj` to grab the selected date. This works perfectly in chrome and edge, but in firefox the `event` object isn't supported and is parsed as `undefined`. If I do `onChange={(e) => {this.onChange(e)}}` to pass in an event object it's still undefined, and also doesn't work in chrome. The native `event` object isn't supported in Firefox (using version 56.0).

**Comment by apollomusa** [comment]
@chr1stinayan hey, did you end up working this one out or finding a workaround? Still experiencing this issue

**Comment by chr1stinayan** [comment]
@apollomusa I updated to the latest version and that seems to have the fix

**Comment by chr1stinayan** [comment]
@apollomusa I'm still having this issue with firefox

**Comment by joshblack** [comment]
Should be fixed when #419 is merged!

**Comment by apollomusa** [comment]
Thanks @joshblack! Any ETAs in place for the merge?

**Comment by joshblack** [comment]
If you @apollomusa or @chr1stinayan want to help verify if it fixes this issue, we can merge in ASAP 😄

**Comment by apollomusa** [comment]
@joshblack tested and good news, we have data returning `onChange` now with the #419 PR
