### ISSUE TITLE
secondary label for checkbox

### ISSUE THREAD

**Issue by weishang** [carbon-design-system/carbon-components-react#288]
HI all, 

This is going to be more of a question than a feature request. 

So in my case, I would like to add a secondary label to the checkbox, e.g., 

O {TEXT_LABEL} {SECONDARY_TEXT_LABEL}
(* can't type square so I am using a circle above to represent the box). 

The secondary label can be a number (count associated items), tags. etc. 

So in the code, it would be another line of 
`<span className="bx--checkbox-secondary-label-text">{secondaryLabelText}</span>` 

I understand if this is not going to be considered, what would be a good way to achieve the same effect without much hacking? My goal is to have a 'hook' to the secondary text so that I can apply css as desired. 

Thank you!

**Comment by tw15egan** [comment]
We could probably solve this and other issues like this one by changing the `PropType` from `string` to `node`
