### ISSUE TITLE
DropdownItem exposes onClick but is useless with Dropdown

### ISSUE THREAD

**Issue by eddiemonge** [carbon-design-system/carbon-components-react#29]
DropdownItem's docs and code has onClick as a prop but it isn't really. Dropdown's onChange is used instead.

From @chrisdhanaraj:
> Still onChange - it's designed to mimic select/textinput/other inputs

DropdownItem does actually have onClick and uses it. However, Dropdown overwrites it with its own event handler rendering anything the user puts pointless

**Comment by joshblack** [comment]
Hi there! 👋 

Thanks so much for reporting this issue. I went ahead and added a simple PR for this in #272, let me know if it doesn't address everything that you've mentioned, or if the behavior doesn't match what you're expectation is for this component!
