### ISSUE TITLE
Invalid default behavior for optional props in components

### ISSUE THREAD

**Issue by codymwalker** [carbon-design-system/carbon-components-react#299]
## Detailed description

Several components have optional text attributes props of type string. However, if you do not provide a value for these props, the default value is 'Provide a heading' and 'Provide a label', respectively. If these props are to be truly optional, the default should be an empty string as to not inject these placeholders into components that are not using the optional props.

> Is this issue related to a specific component?
The following components all appear to have optional props with a non-empty string default:
* Modal
* TimePickerSelect
* TextArea
* DatePickerInput
* Checkbox
* ToolbarSearch
* RadioButton
* Search
* FormGroup
* FileUploader
* ProgressIndicator

Interestingly enough, the `TextInput` component does use an empty string as the default prop value.

> What did you expect to happen? What happened instead? What would you like to see changed?
I would expect the default values to be an empty string.

> What version of the Carbon Design System are you using?
7.x.x

## Steps to reproduce the issue

1. Import a `Modal` component
2. Provide a `modalHeading` prop, but do not provide a `modalLabel` prop.

## Additional information

![image](https://user-images.githubusercontent.com/6432098/32227993-46621860-be23-11e7-8887-fcc7d20602ea.png)

```
<Modal id='loggingModal' open={this.state.isModalOpen} passiveModal modalHeading='Response Details' onRequestClose={this.closeModal} >
```

**Comment by tw15egan** [comment]
This was a legacy a11y addition because we were getting violations for not providing default `labelText`. Since then, we've realized that these default text strings are cumbersome and can be handled by project teams to avoid a11y issues (labels must contain text, etc..), but haven't had the time to get around to fixing these. They will be addressed in a coming sprint

**Comment by alisonjoseph** [comment]
Going through the components now and removing the default text, noticed some components have `iconDescription` should this also be changed to an empty string, I could see the argument for leaving this one? thoughts?

**Comment by tw15egan** [comment]
I think `iconDescription` is being used for populating the `title` attribute in the `svg`, so we should keep these for a11y reasons
