### ISSUE TITLE
Performances dramatically decline in v4.0.4

### ISSUE THREAD

**Issue by Kenzku** [carbon-design-system/carbon-components-react#305]
If you just go to your story book:

http://react.carbondesignsystem.com/?selectedKind=Modal&selectedStory=transactional&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel

open modal, you can see text is not loaded straight forward.

The same thing happens to our product after changed to the latest version.

**Comment by Kenzku** [comment]
Also, slightly happens in v3.14.0

**Comment by joshblack** [comment]
Going to close this in preference for this issue in the core repo here: https://github.com/carbon-design-system/carbon-components/issues/405

Feel free to re-open though if you feel like that issue doesn't address your concerns!
