### ISSUE TITLE
[RFC] Tables v2 API Design

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-components-react#307]
This issue will be used for the API Design of the [Tables v2](http://carbondesignsystem.com/components/data-table/code) work introduced in Carbon v8.

Any and all feedback is welcome! 😄

**Comment by jzhang300** [comment]
```

**Comment by joshblack** [comment]
A stab at trying to see what a component might "look" like in JSX:

![screen shot 2017-11-06 at 12 23 14 pm](https://user-images.githubusercontent.com/3901764/32457054-4729e29a-c2ed-11e7-979d-98333929eb31.png)

Given the following tabular data:

```js
const data = [
  {
    name: 'Load Balancer 1',
    protocol: 'HTTP',
    something: 80,
    rule: 'Round Robin',
    attached_groups: 'Maureen\'s VM Groups',
    status: 'active',
  },
  {
    name: 'Load Balancer 2',
    protocol: 'HTTP',
    something: 80,
    rule: 'Round Robin',
    attached_groups: 'Maureen\'s VM Groups',
    status: 'active',
  },
  {
    name: 'Load Balancer 3',
    protocol: 'HTTP',
    something: 80,
    rule: 'Round Robin',
    attached_groups: 'Maureen\'s VM Groups',
    status: 'active',
  },
  {
    name: 'Load Balancer 4',
    protocol: 'HTTP',
    something: 80,
    rule: 'Round Robin',
    attached_groups: 'Maureen\'s VM Groups',
    status: 'active',
  },
  {
    name: 'Load Balancer 5',
    protocol: 'HTTP',
    something: 80,
    rule: 'Round Robin',
    attached_groups: 'Maureen\'s VM Groups',
    status: 'active',
  },
];

<DataTable>
  {({
    // Can be set in `DataTable` as props, also might contain state info
    getToolbarProps,
    // Mirrors `Pagination` component props, also might contain state info
    getPaginationProps,

    // Method that is given a table header
    sortBy,

    rows,
  }) => (
    <Toolbar {...getToolbarProps()} />
    <Table>
      <TableHead>
        {Object.keys(rows[0]).map(header => (
          <TableHeader key={header} sortable={true} onClick={sortBy(header)}>
            {header}
          </TableHeader>
        ))}
      </TableHead>
      <TableBody>
        {rows.map((row, i) => (
          <TableRow isSelected={row.isSelected} isExpanded={row.isExpanded}>
            {Object.values(row).map(cell => (
              <TableCell>
                {cell}
              </TableCell>
            ))}
          </TableRow>
        ))}
      </TableBody>
    </Table>
    <Pagination {...getPaginationProps()} />
  )}
</DataTable>
```

Trying to mirror some principles from Paypal's [downshift](https://github.com/paypal/downshift) library. Might be the internal way we organize these things, versus external, but figured I'd take a stab at this.

**Comment by joshblack** [comment]
Trying to think of the cases in which someone would use this, let me know if I'm missing any obvious ones 😅 

- Developer wants to just pass in their data and be done
- Developer wants fine-grained control over things like:
  - What is sortable
  - How are things sorted
  - Whether or not the ghost bar appears
  - What appears in a ghost bar
  - What appears in a toolbar and how do you react to interactions on specific nodess
  - How do I sort by multiple columns (might not be supported?)
  - How do I asynchronously load in each page of data

**Comment by joshblack** [comment]
From an initial perspective, it seems like `DataTable` should be responsible for:

#### Coordination of Pagination

- A prop representing the total number of pages
- A prop for page size
- A prop for handling changing page size?
- A prop for fetching the next page and returning the new list, i.e.
  - `onNextPage = ({ currentPage, nextPage, prevPage, items }) => items`
  - `onPrevPage = ({ currentPage, nextPage, prevPage, items }) => items`
  - This prop + state of the component should change what rows are passed into the child method

#### Coordination of row state

- Each row should be configured to be expandable, selectable, or both
- Each row should be flagged as being expanded, selected, or both

#### Coordination of data actions

I would assume that we would need to support actions from the toolbar like:

- Given a filter control, how can I manipulate the collection of items so that only those that match the filter are shown
- CRUD actions around a specific item, namely:
  - Creating a row
  - Editing a row
  - Removing a row
  - Editing a cell in a row

**Comment by jzhang300** [comment]
@joshblack @marijohannessen What's the current status of the v2 Data Table implementation?

**Comment by joshblack** [comment]
Hi @jzhang300! Data Tables v2 are on the dock for our current sprint, I think @marijohannessen is tackling getting initial visual parity and then we'll add in behavior piecewise.

**Comment by joshblack** [comment]
Closing this now as we start working more on the functionality for Data Table!
