### ISSUE TITLE
More DetailPageHeader issues

### ISSUE THREAD

**Issue by jzhang300** [carbon-design-system/carbon-components-react#31]
## More issues with DetailPageHeader

Z-index with top nav is incorrect for some reason:

![screen shot 2017-06-14 at 5 07 39 pm](https://user-images.githubusercontent.com/1449523/27156757-2992e172-5124-11e7-975f-29db8cd496b7.jpg)

I did get this to work when I changed the z-index of DetailPageHeader from 6000 to 5000 somehow fixes this...

---

DetailPageHeader doesn't adjust when LeftNav is toggled:

![screen shot 2017-06-14 at 5 07 43 pm](https://user-images.githubusercontent.com/1449523/27156744-1b94d602-5124-11e7-923d-aaff8393d3ee.jpg)

---

DetailPageHeader's padding is not the same as the padding of regular content:

![giff](https://user-images.githubusercontent.com/1449523/27156839-9151489e-5124-11e7-92fa-2126c93cac11.gif)

This is because as a `position: fixed` element, the 5% padding refers to the browser window, not its containing element, despite having a width of `calc(100% - 200px)`.

I think the current DetailPageHeader component needs to be wrapped in another container, and that container needs to be `position: fixed; width: `calc(100% - $whatever-left-nav-width)` and everything inside of DetailPageHeader just needs to be static.

**Comment by eddiemonge** [comment]
Nice detail. It might be better to open these as separate issues though.

**Comment by joshblack** [comment]
bump @jzhang300! Or should I bug you on Slack? 😛
