### ISSUE TITLE
NumberInput custom spinner's event context should be on the input instead of the svg

### ISSUE THREAD

**Issue by mven** [carbon-design-system/carbon-components-react#311]
## Detailed description

using the `onClick()` method on the `<NumberInput />` component , the target is referencing the svg that had been clicked, instead of the `input`, something that that the "stock" spinner provides.

> Is this issue related to a specific component? 

`<NumberInput />`

> What browser are you working in? 

Chrome latest

> What version of the Carbon Design System are you using? 

v7

**Comment by joshblack** [comment]
Should be addressed in recent releases. Feel free to re-open if that's not the case!
