### ISSUE TITLE
Tooltip component triggered by div instead of text

### ISSUE THREAD

**Issue by hanhansen** [carbon-design-system/carbon-components-react#315]
Is there a way to trigger the tooltip component by hovering over a div instead of the triggerText?

**Comment by asudoh** [comment]
Tooltip opens on hovering over the icon IIRC. @hanhansen Do you want to make a inheritance of Tooltip that changes its [state](https://github.com/carbon-design-system/carbon-components-react/blob/24aa775/src/components/Tooltip/Tooltip.js#L46) upon event fired from another element? Or if you want to use [React composition pattern](https://reactjs.org/docs/composition-vs-inheritance.html) I guess the open/closed state can be exposed as props.

**Comment by hanhansen** [comment]
controlling `open` with a state does not seem to work

**Comment by asudoh** [comment]
@hanhansen Sorry I may have needed more explanation - You need `.getTriggerPosition()` beforehand: https://github.com/carbon-design-system/carbon-components-react/blob/24aa775/src/components/Tooltip/Tooltip.js#L45

**Comment by hanhansen** [comment]
@asudoh, that's okay. I found a work around for constrolling `open` with state.
