### ISSUE TITLE
Date Picker revamp

### ISSUE THREAD

**Issue by marijohannessen** [carbon-design-system/carbon-components-react#331]
## Overview

The `DatePicker` component is a bit buggy and needs some more love.

- [x] DatePicker with single calendar fires `onChange` with an empty array instead of the selected date https://github.com/carbon-design-system/carbon-components-react/issues?page=1&q=is%3Aissue+is%3Aopen
- [ ] Switching months in the single date picker makes it lose the `bx--date-picker` class https://github.com/carbon-design-system/carbon-components-react/issues/261
- [x] Cannot grab selected date in Firefox https://github.com/carbon-design-system/carbon-components-react/issues/286

**Comment by psachs21** [comment]
I've already fixed the first one on my branch, i'll take a look at the other two at the same time.

**Comment by chr1stinayan** [comment]
Is there a fix for #286? Still seems to be an issue after updating to the latest version.

**Comment by tw15egan** [comment]
@chr1stinayan a new release should be out in a few minutes with this fix!

**Comment by marijohannessen** [comment]
@psachs21 Thank you so much for helping out with this, much appreciated! 👍

**Comment by tw15egan** [comment]
Seems like these have been resolved
