### ISSUE TITLE
Handle to close a modal programmatically 

### ISSUE THREAD

**Issue by chethankumar** [carbon-design-system/carbon-components-react#343]
## Detailed description

Describe in detail the issue you're having. Is this a feature request (new component, new icon), a bug, or a general issue?

feature request or could be a bug

> Is this issue related to a specific component?

yes, modals

> What did you expect to happen? What happened instead? What would you like to see changed?

A way to programmatically close the modal so that I could close it using some other control or based on some other condition.

I am not sure if handleClose prop is supposed to help in this. If it is indeed supposed to do it, probably an example of how to do it could help.

> What browser are you working in?

chrome

> What version of the Carbon Design System are you using?

carbon-components: 8.1.8
carbon-components-react: 4.1.2

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Working on IBM App Launch service on bluemix

**Comment by asudoh** [comment]
Hi IIUC the code @chethankumar the open/closed state can be changed by [the `open` prop](https://github.com/carbon-design-system/carbon-components-react/blob/9aea808/src/components/Modal/Modal.js#L18). In case if you are concerned about [our vanilla repo](https://github.com/carbon-design-system/carbon-components), too - You can call [`modal.hide()`](https://github.com/carbon-design-system/carbon-components/blob/f748b2c/src/components/modal/modal.js#L107).

**Comment by chethankumar** [comment]
@asudoh The **open** prop does close and open the modal, but if it is set to false, the click of the trigger button won't open the modal again.

So, currently its as if you can either do it by the open prop or by the click of the trigger button. But, I don't seem to figure out to make it work with both.

**Comment by asudoh** [comment]
@chethankumar Would you mind sharing your code that demonstrates the problem you described, e.g. on CodePen? Thanks!

**Comment by joshblack** [comment]
Hi there @chethankumar!

Do you have some concrete examples for the situations where you would need:

> A way to programmatically close the modal so that I could close it using some other control or based on some other condition.

In addition, any API suggestions for what you would anticipate would be super helpful to make sure we're on the same page 😄

**Comment by chethankumar** [comment]
So, this is what I was trying to implement.
I have a modal wrapper which itself renders a trigger button. Clicking on this, I can open the modal.
And the close button on the top right corner will close it.
All good till here.
Now, I have a bunch of buttons in the modal. I am not using the default 2 buttons provided by the wrapper as I need more of them.
Now, onClick on these buttons, I would like to close the modal.

I tried to use the open prop of the modal, to close the modal on click of these buttons.
But, when I do that, the next time I click on the trigger button, the modal doesn't open since the open prop is set to false.

It would be lot helpful if the trigger button and the close button overrides the open prop.

**Comment by robinchoii** [comment]
Anybody know how to remove the "x" icon from the modal ?

**Comment by tw15egan** [comment]
@robinchoii for UX reasons, we recommend _not_ hiding the `x` from the modal. For more info: http://www.carbondesignsystem.com/components/modal/usage

**Comment by asudoh** [comment]
Hi - Got a better handle on this this issue as I was looking at another stuffs - As far as I see:

* `<Modal>` lets you fully control the open/closed via prop, and let you handle close button by youself (via `onRequestClose` prop) - In other words, `<Modal>` itself does *not* close itself when X button is clicked
* `<ModalWrapper>` is an example controlling `<Modal>` by maintaining open/closed state

That said, if you need more than a simple trigger button/modal combination you may want to something similar to `<ModalWrapper>` by yourself.

Closing this issue for now - Feel free to re-open if anybody has any further thoughts!
