### ISSUE TITLE
[ClickListener] IE11: Unable to get property 'contains' of undefined or null reference

### ISSUE THREAD

**Issue by nicoxxie** [carbon-design-system/carbon-components-react#344]
We(IAM) are seeing this error message from ClickListener.js on IE.  Probably needs to do a check before calling .contains() 

See how React is doing it: https://zhenyong.github.io/react/docs/more-about-refs.html

![screen shot 2017-11-15 at 11 29 09 am](https://user-images.githubusercontent.com/17915105/32857772-9fb4a440-ca0e-11e7-88d4-b722a771ad23.png)

Unable to get property 'contains' of undefined or null reference
File: main-bundle-6369fb459875a1f35b05.js, Line: 25, Column: 18507

**Comment by stefanrue** [comment]
I'm running into exactly the same problem. Is there any update or outlook on when it is getting fixed?

**Comment by joshblack** [comment]
Should be addressed in #430!
