### ISSUE TITLE
Provide a way to set date value programmatically in DatePicker component.

### ISSUE THREAD

**Issue by sandhya-r-reddy** [carbon-design-system/carbon-components-react#350]
We want to update the date  programmatically for certain use-cases. For example, if user selects Last 6 days from drop-down, we can change dates to match that selection. However, there is no easy way to do this right now.
We are accessing internals of DatePicker components to achieve that. It would be great if these classes provide some mechanism to achieve that (via props or state).

> Is this issue related to a specific component?
DatePicker

> What did you expect to happen? What happened instead? What would you like to see changed?
Expected-In case we need to update the date, we need to send the new value to the component and component should handle the change.
Happening- In order to update the date, we have to use the cal instance, in our code.

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
Latest

**Comment by tw15egan** [comment]
Looks great! Thanks for helping out and adding in these features 🎉 👍 ✅
