### ISSUE TITLE
DatePicker (range) onChange can be fired when using mouse selection 

### ISSUE THREAD

**Issue by ilovepumpkin** [carbon-design-system/carbon-components-react#352]
## Detailed description

Describe in detail the issue you're having. Is this a feature request (new component, new icon), a bug, or a general issue?

The range DatePicker's onChange is never fired if I use mouse to select dates. It could be fired when I typing the value directly in the text inputs. 

> Is this issue related to a specific component?

DatePicker 

> What did you expect to happen? What happened instead? What would you like to see changed?

Since I want to trigger another action right after user select a date, onChange should be fired. Now it is never fired. 

> What browser are you working in?

Chrome. 

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
7.19.2

## Steps to reproduce the issue

1. add a range type DatePicker and with onChange defined
2. Select range dates using mouse

## Additional information

* Screenshots or code
* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.

**Comment by asudoh** [comment]
@ilovepumpkin Does the problem still reproduce for you? Quickly tried this scenario in our dev env and `onChange()` fires for clicking on a date in the dropdown, even with range one.

**Comment by ilovepumpkin** [comment]
Yes, works now. Close this bug, please. Thanks!
