### ISSUE TITLE
DatePicker's calendar is not scrolling(Remaining static)

### ISSUE THREAD

**Issue by AbhishekVG** [carbon-design-system/carbon-components-react#357]
## Detailed description
 I'm using DatePicker component and this component is taking window object as a reference to move on scrolling
But in my case i have kept DatePicker in sidebar which has it's own scroll.
When scrolling the side bar the input of DatePicker only is moving and the calendar popup is remaining static
When the outer part (outside the sidebar) is scrolled,then only the calendar is moving.
I want the calendar to work even in sub scrolls(scroll inside scroll).
i.e. How to make this work in side bar which has it's own scroll

## Steps to reproduce the issue(I'm using ReactJS here)

1. Step one: Place the component inside this div
          <div style={{height: '450px',overflow: 'scroll}}>
             <div style={{height: '1000px'}}>
                  ---place the datepicker comp here---
             </div>
          </div>

2. Step two:Click on the DatePicker Input area

3. Step three: Scroll(The calendar popup will remain static,where as inputarea will move)

Initially
![Initially](https://user-images.githubusercontent.com/24239960/33005166-ab2c705c-cdea-11e7-86c3-b273bf914a78.PNG)
After Scrolling(Calendar remain static)
![afterscrolling](https://user-images.githubusercontent.com/24239960/33005165-ab01f818-cdea-11e7-84d2-73adcf8150a5.PNG)

**Comment by tw15egan** [comment]
@marijohannessen probably has the most knowledge in this area

**Comment by marijohannessen** [comment]
Hi @AbhishekVG , I've tried debugging this today without any luck so I ended up asking the creator of `flatpickr`. I'll keep you updated here once I get a response!
