### ISSUE TITLE
InteriorLeftNav doesn't pass down the activeHref props to its children items

### ISSUE THREAD

**Issue by ashpc** [carbon-design-system/carbon-components-react#36]
When we pass an **activeHref** props to the InteriorLeftNav component, it gets replaced by  window.location.pathname  and this causes the initial load to not highlight the selected item.

Expected: When activeHref is passed as  a props it should be propagated to the children as well and not overwritten by window.location.pathname.

**Comment by joshblack** [comment]
Hi there! 👋 

Thanks so much for taking the time to report this issue! However, I'm having a hard time tracking this down. To help us figure out what's causing this, can you provide steps to reproduce the issue that you're hitting while using the `InteriorLeftNav` component?

**Comment by marijohannessen** [comment]
Closing this issue due to lack of response from issue creator.

**Comment by ashpc** [comment]
Looks like this has been resolved.
