### ISSUE TITLE
How to control open and close of InteriorLeftNav

### ISSUE THREAD

**Issue by ehdsouza** [carbon-design-system/carbon-components-react#365]
There is no way to control what the initial status for the   `InteriorLeftNav` is. We want to have either:
1 . An `open` property that we can use to manage the initial render and therefore render the leftnav closed by default
2. Have `open()` and `close()` methods that can be use to close or open the left nav from the parent component.

I can contribute with a PR as long as I know what do you want me to do. 👼 

> Is this issue related to a specific component?

InteriorLeftNav

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Watson Console: https://console.ng.bluemix.net/watson

**Comment by joshblack** [comment]
Definitely agreed that this is something that should be controlled when the component initially mounts. Typically, it seems like the pattern is something around the lines of `defaultOpen` if you want to just set it once and forget it after the component mounts, or transform it into a controlled component with an `isOpen` prop.

I'm totally down for either pattern, do you have some examples of an API that your team expects from this component? Maybe we can go back-and-forth to make sure an API works for both groups and then build it 🚀

**Comment by ehdsouza** [comment]
We can have either way. Was thinking of going with `defaultOpen` and having the `open()` and `close()` methods to control the activity (Something similar to `open` property in the `InteriorLeftNavList`)

Let me know if I can go ahead in contributing a PR for this.

**Comment by joshblack** [comment]
Just to refine the requirements, I think if someone wants to control when the nav is open then the component should become a controlled component, so that whatever value is passed in for `open` will be the state of the nav. Then we as the library can provide a hook, like `onChange`, so that a consumer using the component can react to some interaction and update the state accordingly.

For example:

```jsx
class CustomComponent extends React.Component {
  state = { isOpen: false };

  handleOnChange = () => this.setState({ isOpen: !this.state.isOpen });

  render() {
    return (
      <InteriorLeftNav
        open={this.state.isOpen}
        onChange={this.handleOnChange
        // ...other props
      />
    );
  }
}
```

How do you feel about something like that?

**Comment by ehdsouza** [comment]
@joshblack I think this pattern looks brilliant! :)

**Comment by tw15egan** [comment]
ILN is no longer in this repo, so closing this. Feel free to reopen on [carbon-addons-cloud-react](https://github.com/carbon-design-system/carbon-addons-cloud-react) if the issues still exists
