### ISSUE TITLE
NumerInput no longer passes the event param

### ISSUE THREAD

**Issue by mven** [carbon-design-system/carbon-components-react#369]
I've been using `NumberInput` in various ways (shown below) and I've had access to the event object passed by the `onChange` prop. However with the newest version (4.2.2), the param is now `undefined`. v4.2.2 includes the following PR: https://github.com/carbon-design-system/carbon-components-react/pull/362 which looks like it directly affects `NumberInput` code. 
Just for testing, I rolled back to 4.2.1 and the event param is properly being assigned and I'm able to use it as such.

Example code of how I've been using `NumberInput`

```javascript
<NumberInput
  ...
  onChange={this.updateQuantity}
  ...
/>

// or

<NumberInput
  ...
  onChange={(e) => this.updateQuantity(e)}
  ...
/>
```

**Comment by joshblack** [comment]
Thanks for reporting this! Definitely is an issue with the latest release, seems like it's trying to pass in `evt` which is defined in both the handler itself, and in the callback for `setState` which is what is causing `undefined` to be passed in.

Will label it/prioritize a fix in our sprint, thanks again!

**Comment by mven** [comment]
Awesome, thanks!
