### ISSUE TITLE
Prop names are not consistent

### ISSUE THREAD

**Issue by eddiemonge** [carbon-design-system/carbon-components-react#371]
Across components, prop names are not consistent. As an example, NumberInput uses `label` and TextInput uses `labelText`

**Comment by joshblack** [comment]
Agreed! I'm working on a document now for standardizing naming conventions for props in our codebase that we'll publish in the wiki 😄 

For now, could actually use this issue as a discussion place to see what other groups expect. 

Some of the patterns that I've come across include:

### Boolean props

An example of this might be `open`, I believe we should transition the current set of boolean props to `isBoolean`, e.g. `isOpen` versus `open`.

In addition, we might have props like `hideLabel` which we should update to `shouldHideLabel` just to make the pattern above.

### Default props

There are certain props that are useful to set the initial value of a component when it mounts, but that a consumer wouldn't care about after that initial mount. We should have consistent naming around these props, some examples could include:

- `default<PropName>`, like `defaultChecked`
- `initial<PropName>`

### Label props

When working with form elements, we should support a couple cases for labels. I think the ideal path here is just to have a generic `label` prop that can take in a string or React node as a value, versus using `labelText`.

### Icon props

This one has come up in a couple places, I think right now things are very specific/pedantic without having flexibility so we should take a look at how we do these props. This could potentially be consolidated into a "icon" object that looks like:

```js
type IconProp = {|
  name: string,
  description: string,
  className?: string,
|};
```

### Spread props

Right now, a lot of the components spread props onto the root node in the component. We should talk about standardizing this, and seeing if we could instead switch to explicitly passing props versus blanket passing everything.

---

I'm sure other patterns will arise, but figured I'd drop some initial thoughts just to get the conversation going 😄

**Comment by tw15egan** [comment]
Agreed. I think our focus in one of the next major releases should be standardizing prop names across the components. Would be very helpful to see what others expect the naming conventions to follow 👍

**Comment by asudoh** [comment]
Ping @emyarod to see if this area is of his interest.

**Comment by emyarod** [comment]
yep @asudoh, and I think this will have some overlap with #1662 as well

**Comment by joshblack** [comment]
Umbrella under #1918 maybe?

**Comment by emyarod** [comment]
yes let's consolidate these issues and update the stats on prop usage frequency in #1918
