### ISSUE TITLE
Update devDependencies to use Babel v7

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-components-react#375]
As the title suggests, this issue is to update our internal dependencies on Babel to v7 so that we can leverage the new fragment syntax made available in the newest v7 packages.

**Comment by eddiemonge** [comment]
I've tried it and it hasn't been the easiest thing to do yet.

**Comment by joshblack** [comment]
@marijohannessen I think we need to hold off on this until the storybook interop is better 😞
