### ISSUE TITLE
A11Y:[Catalog] The WAI-ARIA widget with img role must have a nonempty alternate text or a label in Create a Cloud Foundry App page

### ISSUE THREAD

**Issue by icemanlily** [carbon-design-system/carbon-components-react#377]
===== ENVIRONMENT =====
IBM CI 162 Checkpoint Violation: 4.1.2 Name, Role, Value
IBM Guidance: http://www-03.ibm.com/able/guidelines/ci162/name_role_value.html
Test Tool Type: DAP

===== DEFECT DESCRIPTION =====
A widget with an img role can contain captions and descriptive text, as well as multiple image files that when viewed together give the impression of a single image. An img represents a single graphic within a document, whether or not it is formed by a collection of drawing objects. In order for elements with a role of image to be perceivable, authors MUST provide alternative te

=====STEPS TO REPRODUCE =====
1> Login IBM Cloud with ID and password
2> Click Catalog
3> Click ASP.NET Core Cloudant Starter

===== EXPECTED RESULT =====
Pls check the followed link for detail:
https://aat.w3ibm.mybluemix.net/token/a80a8d09-7f5a-480a-adcc-7e22f77482b0/c19cc7e4-e2e6-4475-89d7-533c2bc34979/archives/2017AugustDeploy//doc/w3/help/en-US/idhi_accessibility_check_g1128.html

![image](https://user-images.githubusercontent.com/6970471/33353953-5e99061c-d4eb-11e7-8a8d-95a6c7d48cdd.png)

**Comment by tw15egan** [comment]
Hi, since SVG's don't have the alt attribute, it uses title and aria-label instead to make sure it's accessible - therefore this component is not violating any rules. This incorrect violation will be fixed in an upcoming release to DAP. Please see https://css-tricks.com/accessible-svgs/ for further information
