### ISSUE TITLE
<Tooltip> TypeError: Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by StefanDoersam** [carbon-design-system/carbon-components-react#384]
## Title line template: [Title]: 

**For each <Tooltip> component on a web page an exception is thrown**
when the web page is reloaded

client.js:82
TypeError: Cannot read property 'getBoundingClientRect' of null
Tooltip.js:36
    at Tooltip._this.getTriggerPosition (c:\...........\node_modules\carbon-components-react\es\components\Tooltip.js:36:1)
    at c:\..........\node_modules\carbon-components-react\es\components\Tooltip.js:54:1
TypeError: Cannot read property 'getBoundingClientRect' of null

## Detailed description

Here is the code snippet which causing the error;

				<TableRowExpanded expanded={toggleState} colSpan={6} key={`er${index}`}>
					<div className="ic4sap--table-expanded-row">
						<table>
							<tbody>
								<tr className="ic4sap--table-expanded-row-attribute-table">
									<td className="ic4sap--table-expanded-row-attribute-name-with-tooltip">
										{getToolTip(tooltips.TT_SERVICE_PACKAGE_TRIGGER_TEXT_ATTRIBUTE, tooltips.TT_SERVICE_PACKAGE_LABEL, tooltips.TT_SERVICE_PACKAGE_TEXT)}
									</td>
									<td className="ic4sap--table-expanded-row-attribute-value">
										<Tooltip direction='top' triggerText={triggerText} showIcon={false}>
											<p className='bx--tooltip__label'>
												aaaaaaa
											</p>
											<p>
												bbbbbbbbb
											</p>
										</Tooltip>
									</td>
									<td className="ic4sap--table-expanded-row-table-separator" />
									<td className="ic4sap--table-expanded-row-attribute-name-with-tooltip">
										<td className="ic4sap--table-expanded-row-attribute-value">
											<Tooltip direction='top' triggerText={triggerText} showIcon={false}>
												<p className='bx--tooltip__label'>
													aaaaaaa
											</p>
												<p>
													bbbbbbbbb
											</p>
											</Tooltip>
										</td>
									</td>
									<td className="ic4sap--table-expanded-row-attribute-value">{getDisplayValue(system.base_saps, NULL_DISPLAY_CHARACTER)}</td>
								</tr>
								<tr className="ic4sap--table-expanded-row-attribute-table">
									<td className="ic4sap--table-expanded-row-attribute-name-with-tooltip" />
									<td className="ic4sap--table-expanded-row-attribute-value" />
									<td className="ic4sap--table-expanded-row-table-separator" />
									<td className="ic4sap--table-expanded-row-attribute-name-with-tooltip">
										<td className="ic4sap--table-expanded-row-attribute-value">
											<Tooltip direction='top' triggerText={triggerText} showIcon={false}>
												<p className='bx--tooltip__label'>
													aaaaaaa
											</p>
												<p>
													bbbbbbbbb
											</p>
											</Tooltip>
										</td>
									</td>
									<td className="ic4sap--table-expanded-row-attribute-value">{getDisplayValue(system.additional_saps, NULL_DISPLAY_CHARACTER)}</td>
								</tr>
							</tbody>
						</table>
						<br />
						<Link to={`/system/${system._id}`}>More details</Link>
					</div>
				</TableRowExpanded>

> Is this issue related to a specific component?
yes: Tooltip

> What did you expect to happen? What happened instead? What would you like to see changed?
No exception thrown

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
    "carbon-components": "7.19.1",
    "carbon-components-react": "3.14.0",

## Additional information
Please contact  @joshblack  he has already some info about this bug,

## Add labels
bug

**Comment by StefanDoersam** [comment]
Is there any hint for a workaround for this issue?
I am asking because not all tooltips on a page are throwing this exception.
Many Thanks!

**Comment by joshblack** [comment]
Hi @StefanDoersam!

I definitely think the check you mentioned in our slack conversation would be appropriate here. I think one thing the original implementation doesn't take into account is that if you inline the `ref` callback, then the `ref` callback will be called twice, once with `null` and another with the reference itself. Full explainer [here](https://reactjs.org/docs/refs-and-the-dom.html#caveats)

To fix this, we just need to align with the suggestions in the React docs themselves.

**Comment by StefanDoersam** [comment]
Hi Josh,
is there any outlook when this issue will be fixed?
Many Thanks!

**Comment by joshblack** [comment]
Hi @StefanDoersam! Have a PR [here](https://github.com/carbon-design-system/carbon-components-react/pull/403) for it. Let me know if that also works for your initial bug that you reported 😄

**Comment by StefanDoersam** [comment]
Hi Josh, many Thanks for your great support!
What do you mean with "initial bug" 

Regards
Stefan
