### ISSUE TITLE
[Component] Combobox, MultiSelect, etc. variants

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-components-react#386]
This issue is for building out the following table of components, using work from the [`downshift`](https://github.com/paypal/downshift) library.

| Component | Selection mode | Type | Filterable | Status |
|-------------|----------------|-------|---------|:----:|
| Dropdown | Single | Default | No | ✅|
| Inline Dropdown | Single | Inline | No | ✅ |
| MultiSelect | Multi | Default | No | ✅ |
| Inline MultiSelect | Multi | Inline | No | ✅ |
| Combobox | Single | Default | Yes | ✅  |
| MultiSelect Combobox | Multi | Default | Yes | ✅ |

**Comment by psachs21** [comment]
@joshblack I was looking for something to start contributing to and this is one of the things that our current library does that I was hoping to replace. Do we have any designs available on these? I'd love to spend some time making these, if not just to get into the flow of this repo. I could probably hack some designs together but that's obviously not ideal.

**Comment by joshblack** [comment]
Hi @psachs21! These are currently being tackled in: https://github.com/carbon-design-system/carbon-components-react/pull/332

Preview link: https://goo.gl/Z5VZPp

**Comment by psachs21** [comment]
@joshblack Ah awesome, I didn't see the PR. I'll take a look there to see if it meets what we need. Thanks!
