### ISSUE TITLE
Tooltip: Add Better Positioning

### ISSUE THREAD

**Issue by DmitriWolf** [carbon-design-system/carbon-components-react#390]
## Feature Request: Improve Positioning

- The components should be able to appear to the right, left, above, and below the point of origin. 
- The triangle should be able to be offset from the center of the component.

This improvement is for the IBM Genesis product.

### Current Behavior:

The component can be positioned above or below the point of origin.
The triangle is centered on the correct side.

### Desired Behavior:

The component can be positioned above or below the origin, or also to the left and right.
The Triangle on the component can be offset from center so it can be more to the top/ bottom or left/right.

**Comment by joshblack** [comment]
Hi @DmitriWolf  👋  Thanks so much for taking the time to make this issue 😄

Definitely agreed that this would be incredibly useful! Let me just include some designers on this thread as an FYI to make sure this is an intended use-case for Carbon, and then we can prioritize it as necessary.

cc @carbon-design-system/design just wanted to make sure this pattern was supported in terms of the visual spec of this component

**Comment by tw15egan** [comment]
This functionality should already be provided, but perhaps it didn't make it over to the React version. In the vanilla version, you can change the direction of the tooltip by using the `data-tooltip-direction` attribute. 

Please see [this link](http://www.carbondesignsystem.com/components/tooltip/code) for more info

**Comment by tw15egan** [comment]
I just tested this on the React side of things, and it seems like this functionality is already available via the `direction` prop. @DmitriWolf can you confirm this works on your end?

**Comment by tay-aitken** [comment]
Yes this is supposed design. Please see the last example under the placement section on the tooltip style tab: http://carbondesignsystem.com/components/tooltip/style

**Comment by DmitriWolf** [comment]
@tw15egan @tay-aitken 
You can see [on this line](https://github.com/carbon-design-system/carbon-components-react/blob/master/src/components/Tooltip/Tooltip.js#L12) that only the top and bottom are allowed. 

Tooltip uses [Floating Menu](https://github.com/carbon-design-system/carbon-components-react/blob/master/src/internal/FloatingMenu.js) for the actual information box, and it seems to [allow top, bottom, right, and left](https://github.com/carbon-design-system/carbon-components-react/blob/master/src/internal/FloatingMenu.js#L10), so maybe this will be easy. 

Also, let's not forget the second part of this request, which is to allow an offset for the triangle so it can be off-center.

**Comment by tay-aitken** [comment]
@DmitriWolf what is your use case for this request? Do you have a visual example so I can make sure we are envisioning the same thing?

**Comment by DmitriWolf** [comment]
@tay-aitken Replying via internal PM.

**Comment by tay-aitken** [comment]
Thanks for clarifying! We do not support having the triangle offset from the center as it is currently not a use case that fits a majority of our users, though it might be something we adopt in the future (based off our roadmap) as we build out the data vis more. For now I would just override the css for `bx—tooltip:before` by adjusting the left property.

**Comment by tw15egan** [comment]
That functionality (having the actual tooltip be placed on the left / right / top / bottom)  is currently built-in and supported by the component, just needed to update the `PropTypes` that were accepted to match the Vanilla version. 

Also, I added a `menuOffset` prop that will let you move the entire tooltip as it pertains to the tooltip icon. If you'd also like to move the actual triangle on the tooltip around, I'd just override `.bx--tooltip:before` using CSS.

**Comment by DmitriWolf** [comment]
@tw15egan  
Thank you for your [work on your PR](https://github.com/carbon-design-system/carbon-components-react/pull/392). I left a couple of comments after running it locally. 

Please correct me if I'm wrong. What I'm hearing from your comment above is that the functionality is **_not_** currently supported, and you need to update the `PropTypes` that are accepted (as you do in your PR). That makes me think this issue should remain open until that gets merged in.

**Comment by DmitriWolf** [comment]
@joshblack This can be closed as it has been merged.
## However
There is an issue I discovered, outlined [here](https://github.com/carbon-design-system/carbon-components-react/issues/410).
