### ISSUE TITLE
Accessibility errors in interior left nav component

### ISSUE THREAD

**Issue by blakesteve** [carbon-design-system/carbon-components-react#397]
## Detailed description

Hi, below are what I believe to be errors within the bluemix/ibm cloud header that I've found using the DAP chrome plugin.

I've run these tests in prod on the dev console.

Errors found:
==

The WAI-ARIA widget with img role must have a nonempty alternate text or a label. (6 of these errors occur)
```<svg class="left-nav-list__item-icon bx--interior-left-nav__icon" fill-rule="evenodd" height="8" name="chevron--down" role="img" viewBox="0 0 12 8" width="12" aria-label="display sub navigation items" data-reactid="13"><title data-reactid="14">display sub navigation items</title><path d="M10.6 0L6 4.7 1.4 0 0 1.4l6 6.1 6-6.1z" data-reactid="15"></path></svg>```

Minimum contrast of 4.44 with its background is not sufficient to meet WCAG AA requirements for text of size 14px and weight of 400. (nav drawer arrow)
```<svg class="bx--interior-left-nav-collapse__arrow" fill-rule="evenodd" height="12" name="chevron--left" role="img" viewBox="0 0 8 12" width="8" aria-label="close/open iln" data-reactid="39"><title data-reactid="40">close/open iln</title><path d="M7.5 10.6L2.8 6l4.7-4.6L6.1 0 0 6l6.1 6z" data-reactid="41"></path></svg>```

## Steps to reproduce the issue

1. Navigate to a web app using the collapsible left nav component
2. Run the DAP chrome extension (available in the chrome web store)

Let me know if further clarification is needed!

**Comment by tw15egan** [comment]
The first issue is attributed to `svg` using the `title` attribute to fulfill this accessibility requirement. The DAP tool currently reports a false positive with this. Please see https://css-tricks.com/accessible-svgs/ for more info.

The second error is also regarding text contrast, which does not apply to the `svg` element in question. I'm going to close this issue, but feel free to reopen if you believe this is not correct.
