### ISSUE TITLE
ModalWrapper doesn't support `disabled` property

### ISSUE THREAD

**Issue by jhpedemonte** [carbon-design-system/carbon-components-react#398]
## Detailed description

ModalWrapper does not support passing a `disabled` property to the rendered Button. This would allow setting the state of the button to not be clickable,.

## Steps to reproduce the issue

1. Create a `ModalWrapper` with `disabled: true`.
2. Notice that rendered button is not disabled and fully functional.

**Comment by tw15egan** [comment]
Whoops, slight oversight. WIll get a PR up to fix this.
