### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by eddiemonge** [carbon-design-system/carbon-components-react#4]
i think the build version of the 3 beta is copying directories to itself multiple times, specifically in the dist/package folder. There are multiple levels deep of the dist files repeating themselves

**Comment by hellobrian** [comment]
Not sure if anyone replied to you directly, the build has been revamped recently. All the distributable files are now in [`es` and `cjs` folders](https://unpkg.com/carbon-components-react@3.0.1/); no more dist.
