### ISSUE TITLE
Bug: Some components use window and that breaks server-side rendering

### ISSUE THREAD

**Issue by germanattanasio** [carbon-design-system/carbon-components-react#40]
Components like `InteriorLeftNav` have references to a `window` object, but that object doesn't exist in server-side.
See all the references to `window` [here](https://github.com/carbon-design-system/carbon-components-react/search?l=JavaScript&q=window&type=&utf8=%E2%9C%93)

When I try to render my server-side I get:
```
ReferenceError: window is not defined
```

There are 2 solutions I know for this kind of problem:
 1. Use [`window-or-global`](https://www.npmjs.com/package/window-or-global) to make sure that window is defined.
 1. Check that `window` is defined or simply remove references to it.

**Comment by chrisdhanaraj** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/6b8b7163-1ec8-4616-82fa-aa467a17af03 "storybook-toolchain-v2"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/b84aaac8-8484-4a1e-902a-ebb526eb7998 "storybook-toolchain-v2") deployed [carbon-components-react](https://github.com/carbon-design-system/carbon-components-react/releases/tag/deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20170707-200832 "deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20170707-200832") to [Bluemix Design System](https://console.bluemix.net/apps/1a30065f-cef2-4933-ba3f-3ff6669a0abd?env_id=ibm:yp:us-south "ibm:yp:us-south:chrisdhanaraj_org:Bluemix Design System"), including commit e8faa8c0be6da847c28e61013074bb70efe99aa2
