### ISSUE TITLE
Is there any way to reset range DatePicker ? 

### ISSUE THREAD

**Issue by ilovepumpkin** [carbon-design-system/carbon-components-react#402]
## Detailed description

Describe in detail the issue you're having. Is this a feature request (new component, new icon), a bug, or a general issue?

Now I need to reset DataPicker (range type) - it means after I select a date range, I need to reset it to the initial state without re-rendering the component. 

> Is this issue related to a specific component?
DatePicker/DatePickerInput

> What did you expect to happen? What happened instead? What would you like to see changed?

`<DatePickerInput
    labelText="Start date"
    onChange={this.handleDateChange}
    onClick={this.handleFromToClick}
    placeholder="mm/dd/yyyy"
    id="fromDate"
    value={this.state.startDate}
    />`
Now I bind a property value with a property "startDate" in local state, by reset startDate value in local state, the input text is gone, but in the popup, the date range is still there. The expected behavior is there should be a way to "completely" reset the component - the date range in popup should be reset as well. 

![image](https://user-images.githubusercontent.com/11310645/33873118-abade346-df54-11e7-975e-3763af57d600.png)

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

7.26.10

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Yes. It is better to be fixed ASAP.

## Additional information

* Screenshots or code
* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.

**Comment by joshblack** [comment]
Hi @ilovepumpkin! 👋  Thanks so much for taking the time to make this issue 😄

While I'm unsure about the specifics of this issue, I'll make sure to include the relevant team members who can answer this.

cc @marijohannessen

**Comment by joshblack** [comment]
Following up on this, since `DatePicker` is basically wrapping [`flatpickr`](https://chmln.github.io/flatpickr/) under the hood I would explore that tool to see if it has the functionality you're expecting.

Also will bump @marijohannessen to see if she has any thoughts, too!

**Comment by marijohannessen** [comment]
Hi @ilovepumpkin , this definitely seems like a bug on our end. I will try and get to it by the end of next week, and I'll keep you updated here. Thanks!
