### ISSUE TITLE
[ContentSwitcher]: Doesn't respect Switch selected prop

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-components-react#409]
## Detailed description

Describe in detail the issue you're having. Is this a feature request (new component, new icon), a bug, or a general issue?

ContentSwitcher currently respects the `selectedIndex` prop. Although if this is not used, and instead the `selected` prop is used on the containing `Switch` components, the proper class is not applied.

Ideally, if ContentSwitcher is not given a selectedIndex, it's containing `Switch` components should render selected if given the prop `selected=true`.

I'm unsure how to treat edge cases of both `selectedIndex` being used as well as applying `selected` to a `Switch`.

I'm developing in Chrome, v^4.2.0 of this library.

## Steps to reproduce the issue

1. Do not set `selectedIndex` on `ContentSwitcher`
2. Add `selected='true'` to one containing `Switch` component
3. Set `selected='false'` on all the other `Switch`es
4. View that the proper class of selected is not applied to `Switch`es with `selected='true'`

**Comment by joshblack** [comment]
Hi @tay1orjones! 👋  Thanks so much for taking the time to make this issue 😄

Definitely is a bug on our end, will try and get this prioritized but will also welcome any contributions that you feel like would help resolve this!

**Comment by joshblack** [comment]
So looking back at this now, I think the goal here should be to use `ContentSwitcher` as the main driver of selection. Trying to derive state from the children `Switch` components here would cause us to have to `setState` in render which seems like a negative cost given that `selectionIndex` can already satisfy this use-case.

Closing this for now, feel free to re-open to continue the conversation! Could easily have missed something 🙂

**Comment by asudoh** [comment]
Just to add a note that this is the same as #1394 and has been fixed.
