### ISSUE TITLE
broken Pagination component missing prop change action

### ISSUE THREAD

**Issue by nicoxxie** [carbon-design-system/carbon-components-react#42]
ON IE Win 7
![72cc29be-51d5-11e7-9f3e-5c5a5bcd0d3c](https://user-images.githubusercontent.com/17915105/27301597-6171094c-54f9-11e7-8465-92d2b5283c5b.png)

How it should be: On Chrome (page number is manually hidden)
![screen shot 2017-06-19 at 2 13 15 pm](https://user-images.githubusercontent.com/17915105/27301625-7d0f7e40-54f9-11e7-8827-4e8b5459d183.png)

Update: 
The broken styles I opened issue on https://github.com/carbon-design-system/carbon-components/issues/201

But this javascript is outdated compare to the bluemix-component-react repo, i.e. missing `pageSize` prop changes? https://github.ibm.com/Bluemix/bluemix-components-react/blob/master/components/Pagination.js#L57

**Comment by eddiemonge** [comment]
@nicoxxie try it now with the fixes from https://github.com/carbon-design-system/carbon-components-react/commit/6309334b578a28c660a47f46d1693d01a9c0f538 ?

**Comment by nicoxxie** [comment]
@eddiemonge we tried with the latest release it still is broken

**Comment by nicoxxie** [comment]
https://github.com/carbon-design-system/carbon-components-react/pull/70
