### ISSUE TITLE
[OverflowMenu]: Menu always in DOM even when not open

### ISSUE THREAD

**Issue by snrubnomis** [carbon-design-system/carbon-components-react#420]
## Detailed description

The OverflowMenu always puts the menu in the DOM even when the menu is closed.  This is true for both normal and floating menu.  This causes performance issues when OverflowMenu is used multiple times.

> Is this issue related to a specific component?

OverflowMenu

> What did you expect to happen? What happened instead? What would you like to see changed?

The menu should only be put in the DOM when the open.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

carbon-components 8.1.8
carbon-components-react 4.2.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Watson Conversation

## Steps to reproduce the issue

1. Use an OverflowMenu
2. Use the browser debugger to inspect the DOM, and notice that the menu is always there

**Comment by marijohannessen** [comment]
Thanks for making this issue @snrubnomis ! This is something that would be great to have for sure! We don't have the resources to get to this right away, but we will add it to our backlog. We would also love any contributions back to this repo with a fix.
