### ISSUE TITLE
Question: Need the sort state of a DataTableHeader to be passed in from the Redux store

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-components-react#428]
## Detailed description
I'd like to use the new DataTable, but we have requirements that the initial sort state of a table be passed in as external properties.  We also keep track of the table's current sort state in the Redux store, so that as we are switching between routes, the sort state is preserved.   Additionally for large tables with paging I'll need this sort parameter passed to my parent component in a callback so that I can pass it along with my fetch statement to the backend.

Because the DataTable is keeping track of it's own sort (and sorting) in it's own local state I can't figure out exactly how I could use it with it's current implementation.

> Is this issue related to a specific component?
DataTable

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
latest

## Steps to reproduce the issue
See this live link for an example of how I'm using the previous Carbon table with this pattern (login with your IBM ID)
https://connection-service.mybluemix.net/explore

Sort descending, then click on an action in the table to drill down, then go back to the previous page to see the previous sort is preserved.

## Additional information
Popup the redux debugger to see the states of the table under the tableReducer.

**Comment by joshblack** [comment]
Hi @swiftfoot! Thanks so much for taking the time to make this issue 😄 

The idea behind the first release of DataTable was just to get visual parity, with some minor functionality supported. Your use-case is definitely one that we would like to support, and should be in an upcoming release.

If you have a specific request for the interface you'd like us to support, I'd go ahead and comment on #307 to help us be aware of consumer requirements. I think a hope here is to support usage similar to how the [Downshift](https://github.com/paypal/downshift) library does things, with respect to controlled vs uncontrolled props and exposing an `onChange` hook that we'll be called with each internal state change.

Feel free to let us know if this doesn't work for your use-case!

**Comment by scottdickerson** [comment]
this one will be fixed by the refactor in PR #562 thanks!
