### ISSUE TITLE
[A11y] The label element's 'for' attribute reference an invisible input element generated by FileUploader component

### ISSUE THREAD

**Issue by iBryan99** [carbon-design-system/carbon-components-react#431]
## Detailed description

The label element's 'for' attribute must reference a non-null, non-empty unique ID in another valid form element such as an input, select or textarea, keygen, etc. Refer to the html specification for complete list of valid elements. When the 'for' attribute does not reference a corresponding unique ID in another valid form element, user agents do not have enough information to determine these essential relationships.

> Is this issue related to a specific component?

Yes, the FileUploader component.

> What browser are you working in?

Chrome.

> What version of the Carbon Design System are you using?

3.8.10

## Add labels

a11y

**Comment by joshblack** [comment]
Hi @iBryan99! 👋  Thanks so much for taking the time to make this issue 😄

I'm having a hard time understanding what behavior is causing this issue, could you provide some steps to reproduce this error? That'd help us out a ton!

**Comment by iBryan99** [comment]
@joshblack 
The problem is the 'for' attribute referenced a input element which is not visible.
But I'm not sure how to fix this, which should be by design I think...

**Comment by joshblack** [comment]
Totally! Like I mentioned earlier, if you can provide a code example, snippet, or steps for reproduction we can help isolate why that's happening and try and help out 😄
