### ISSUE TITLE
OverflowMenuItem with Icon

### ISSUE THREAD

**Issue by apollomusa** [carbon-design-system/carbon-components-react#434]
I am using the `OverflowMenuItem` component and want to show both an `<Icon />` and text - so I have something like this: 

```
<Link to={linkURL}>
  <Icon name={icon} fill="black" description={linkText} />
  <p>{linkText}</p>
</Link>
```

It's erring with: ` Failed prop type: Invalid prop `itemText` of type `object` supplied to `OverflowMenuItem`, expected `string`.`

What's the way around this to include an Icon in the Menu items?

**Comment by joshblack** [comment]
Hi @apollomusa! 👋  Thanks so much for taking the time to make this issue 😄

Currently, `OverflowMenuItem` doesn't support generic `children` as far as I'm aware, although this could definitely be a change that we can support if adheres to design constraints.

cc @carbon-design-system/design does combining text with an icon in an Overflow Menu Item adhere to our design system?

**Comment by bsonefeld** [comment]
Definitely depends on the situation! @apollomusa do you have a screenshot of the intended design? If you're trying to use an icon, I would definitely recommend specific sizing guidelines be set in place (they would have to be pretty small to fit in with the height of each text item).

**Comment by apollomusa** [comment]
followed Carbon design principle with no Icon
