### ISSUE TITLE
ModalFooter isn't triggering onRequestSubmit when primary button is clicked

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-components-react#440]
## Detailed description
Bug where the ModalFooter isn't triggering onRequestSubmit function when the primary button is clicked.  To reproduce, create a ModalFooter with a primary button and pass a function as it's onRequestSubmit property.  Click the button and notice the onRequestSubmit function is never called.
Check the code you can see line 268 in ComposedModal should be calling the onRequestSubmit property directly since there's no local method this.onRequestSubmit

https://github.com/carbon-design-system/carbon-components-react/blob/b3dde29bf9fddd1ba73ee74d10619621b70c4b41/src/components/ComposedModal/ComposedModal.js#L268

**Comment by joshblack** [comment]
Hi @swiftfoot! 👋  Thanks so much for taking the time to make this issue 😄

Definitely an issue on our end, I went ahead and labelled it a bug, sized it, and moved it to our backlog so we can add it to our sprints. We'll also accept any contributions to fix it, as well!
