### ISSUE TITLE
DataTable Storybook: Documentation Improvements

### ISSUE THREAD

**Issue by jzhang300** [carbon-design-system/carbon-components-react#441]
## Detailed description

![screen shot 2018-01-03 at 5 27 40 pm](https://user-images.githubusercontent.com/1449523/34544347-6d7c97a8-f0ab-11e7-91d3-1e31613e43ba.jpg)

* `<BasicDataTable>` is confusing because it's not a real component you use, though it appears like so in Storybook
* Understanding the entirety of DataTables is overwhelming to a new user.  It took me at least 2 hours to understand how to use it.

## How to fix this

In the Storybook, I think the DataTable story should be more explicit in how to use all the different features starting with the most basic to the most complex.

So the DataTable-story may look like this:
```
Basic DataTable
DataTable with Toolbar
DataTable with Multiselection
DataTable with Pagination
DataTable with Sorting by Column
DataTable with All Features
```

By specifically demonstrating each use case, the initial learning curve of how to use this component can decrease from 2 hours to 10 minutes.

**Comment by joshblack** [comment]
@jzhang300 thanks for the feedback! I think we can definitely incorporate these into future iterations of DataTable 😄

**Comment by joshblack** [comment]
Should be completed by this README: https://github.com/carbon-design-system/carbon-components-react/tree/master/src/components/DataTable#datatable-component and corresponding storybook stories 👍
