### ISSUE TITLE
Is there an advanced table component? 

### ISSUE THREAD

**Issue by ilovepumpkin** [carbon-design-system/carbon-components-react#45]
I have check out the storybook - http://react.carbondesignsystem.com/ , looks like the current table component is quite simple - no sorting, no filtering and no pagination. Certainly I do see the Search and Pagination component. Is there an advanced table component which support sorting/filtering/pagination out of box ?

**Comment by hellobrian** [comment]
We have a [nested table](http://react.carbondesignsystem.com/?selectedKind=Table&selectedStory=Nested%20Table&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel)  which can be paired with the `Toolbar` and `Pagination` components. 
Unfortunately, sorting/filtering/pagination functionality is not available out of the box.

**Comment by ilovepumpkin** [comment]
okay, thank you!

**Comment by tw15egan** [comment]
@ilovepumpkin I put together an example of sorting on Codepen if you'd like to take a look: https://codepen.io/tjegan/pen/PjjyVN

**Comment by hellobrian** [comment]
We should add a link to that codepen to the site. 
And eventually just add the live example with sorting too.
You're a hero, @tw15egan

![cheer-tj](https://user-images.githubusercontent.com/4185382/27646588-a12f1c3a-5bee-11e7-81dd-09f53c095c43.gif)

**Comment by ilovepumpkin** [comment]
WOW, it's cool! @tw15egan , thank you!
