### ISSUE TITLE
MultiSelect : Element type is invalid : expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

### ISSUE THREAD

**Issue by prakashchandrabarnwal** [carbon-design-system/carbon-components-react#452]
## Detailed description

Describe in detail the issue you're having. Is this a feature request (new component, new icon), a bug, or a general issue?

error:  expected a string (for built-in components) or a class/function (for composite components) but got: undefined. I guess we have forget to export MultiSelect from lib/index.js

> Is this issue related to a specific component?
MultiSelect

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
"carbon-components": "^8.2.0",
 "carbon-components-react": "^5.6.0",
 "carbon-icons": "^6.2.0"

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
import {MultiSelect} from 'carbon-components-react'

inside render function: 
<MultiSelect
      label="Label"
      items={[{id: "option-1", text: "Option 1"}, {id: "option-2", text: "Option 2"}, {id: "option-3", text: "Option 3"}]}
      itemToString={(item)=>console.log("test",item)}
      onChange={({target})=>console.log("change",target.value)}
    />

* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.

**Comment by asfordmatt** [comment]
There doesn't appear to be an export for MultiSelect here:
https://github.com/carbon-design-system/carbon-components-react/blob/d9a065730acac09b72c8d7c25385e674bfe3d909/src/index.js

**Comment by joshblack** [comment]
What @asfordmatt said, it's currently not being exported. There are a couple more components we want to add in until we officially export MultiSelect, in the meantime you can always import the component directly by doing:

```
import MultiSelect from 'carbon-components-react/lib/components/MultiSelect';`
```
