### ISSUE TITLE
MultiSelect : TypeError: Cannot read property 'localeCompare' of undefined

### ISSUE THREAD

**Issue by prakashchandrabarnwal** [carbon-design-system/carbon-components-react#461]
## Detailed description
UI is crashing with Cannot read property 'localeCompare' of undefined, probably related to sorting logic.
Describe in detail the issue you're having. Is this a feature request (new component, new icon), a bug, or a general issue?

> Is this issue related to a specific component?
MultiSelect

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
    "carbon-components": "^8.2.2",
    "carbon-components-react": "^5.6.2",
    "carbon-icons": "^6.2.0"

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information
    https://github.com/carbon-design-system/carbon-components-react/issues/452

* Screenshots or code
   import MultiSelect from 'carbon-components-react/lib/components/MultiSelect';

  inside render function : 
   <MultiSelect
       label="Label"
       items={[{id: "option-1", text: "Option 1"}, {id: "option-2", text: "Option 2"}, {id: "option-3", text: 
      "Option 3"}]}
       itemToString={(item)=>console.log("item",item)}
       onChange={({target})=>console.log("change",target.value)}
     />  

* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.

**Comment by joshblack** [comment]
Hi @prakashchandrabarnwal! 👋  Thanks so much for taking the time to make this issue 😄

I think you're right, the issue lies in this part of the code:

```
  // Otherwise, we either have two selected items, or two un-selected items, so
  // we just do a string comparison to see which comes first.
  return itemToString(itemA).localeCompare(itemToString(itemB));
```

Typically, this would correspond to `itemToString` returning `undefined` for a given option that you've provided. So I would make sure to verify that you're providing an `itemToString` method that works for each of the items you pass in 😄

**Comment by joshblack** [comment]
Going to close this for now, feel free to re-open if this isn't what you're original issue was referring to!

**Comment by prakashchandrabarnwal** [comment]
Hi @joshblack! Please tell how to use this component, UI is still crashing with the same TypeError even if i do not provide `itemToString` 

`<MultiSelect
      label="Label"
      items={[{id: "option-1", text: "Option 1"}, {id: "option-2", text: "Option 2"}, {id: "option-3", text: "Option 3"}]}
      onChange={({target})=>console.log("change",target.value)}
    />` 
As per storybook `items` and `label ` are required. What should be correct format of items

**Comment by joshblack** [comment]
Will follow up on Slack!

**Comment by matuagarwal** [comment]
Thanks @joshblack for your help on this !
We are not able to use this component yet.
