### ISSUE TITLE
MultiSelect DropDown items are not coming in proper order

### ISSUE THREAD

**Issue by prakashchandrabarnwal** [carbon-design-system/carbon-components-react#475]
## Detailed description
MultiSelect DropDown items are not sorted, items are coming in random order if we provide 
`{Array(59).fill().map((e, i) => {return { text:(i+1).toString(), value:i+1 }})}` to items. 

Describe in detail the issue you're having. Is this a feature request (new component, new icon), a bug, or a general issue?
MultiSelect

> Is this issue related to a specific component?
MultiSelect

> What did you expect to happen? What happened instead? What would you like to see changed?
There should be a custom sort props or props that enable or disable sorting feature

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
"carbon-components": "^8.4.0",
"carbon-components-react": "^5.8.0",
"carbon-icons": "^6.2.0"

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
<img width="1007" alt="screen shot 2018-01-12 at 9 29 23 pm" src="https://user-images.githubusercontent.com/20160628/34885434-fd8a93b8-f7e5-11e7-89ae-283950ce40f3.png">
<img width="1194" alt="screen shot 2018-01-12 at 9 31 08 pm" src="https://user-images.githubusercontent.com/20160628/34885449-0a565456-f7e6-11e7-91fa-195fa70fc9d3.png">

* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.

**Comment by matuagarwal** [comment]
@joshblack request you to check this issue.

**Comment by joshblack** [comment]
Hi @matuagarwal! 👋  Thanks so much for taking the time to make this issue 😄

This definitely seems like an issue in the default `sort` algorithm where we use `localCompare`. This should definitely be updated to include numbers, and we should offer up a prop for a consumer to handle sorting manually.

Labelling it as a bug for now and will pick it up in a sprint soon 😄

**Comment by joshblack** [comment]
Numeric option should be supported in this line: https://github.com/carbon-design-system/carbon-components-react/blob/master/src/components/MultiSelect/tools/sorting.js#L13

Going to close this since I believe this is resolved, feel free to re-open if needed!
