### ISSUE TITLE
Verify i18n support for Carbon Components

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-components-react#477]
We should make sure that all of our components lends themselves to i18n, not only for strings that are rendered to the screen but also for attributes like ARIA labels, and have a documented example for each component in Storybook.

This issue is for the following:

- [ ] Identifying components that can't follow common i18n patterns
- [ ] Updating these components
- [ ] Adding stories for components for i18n

**Comment by alisonjoseph** [comment]
@joshblack should we move this to carbon/issue to make sure it gets tracked in future sprint planning?

**Comment by joshblack** [comment]
Yupp! Definitely makes sense to me 👍
