### ISSUE TITLE
Data Table: Pagination

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-components-react#488]
This issue is for the implementation of the API Design for pagination for a DataTable. This includes:

- [ ] Creating the initial API design for how paginating a table will work
- [ ] Collecting feedback from sponsor teams on design
- [ ] Initial implementation of Pagination support
- [ ] Added storybook story for pagination
- [ ] Added tests for new behavior

**Comment by psachs21** [comment]
Looking at the current table implementation API, it would be difficult to just add a pagination example. The primary issue being that the current sorting API (on DataTable) makes the assumption that it has all the rows available to it. So if pagination needs to work with filtering/sorting, we need hooks to bypass the default sorting/filtering functionality.

One idea i have is to provide an optional prop, called `getRows` which will be called whenever the component needs to figure out the rows it needs to display. Arguments to this function could be filter/sorting states which could be used in conjunction with paginated state to allow for a fully customizable behaviour. I can put this together as a PR if this seems like the avenue we want to go down.

```jsx
<DataTable
  getRows={({ filter, sort }) => [...sortedAndFiltered]}
  headers={headers}
  render={({ rows }) =>... }
/>
```

In this example, render will be called with rows that are already prefiltered by the `getRows` call.

**Comment by psachs21** [comment]
So I've got a fix for sorting, and filtering, but selection is proving to be annoying and brings up the question, how do we want the checkbox in the header to behave with paging?

- When clicking the checkbox in the header, should all items in all pages be selected?
- Should only the current page be selected?
- How to represent the checkbox when all items on the current page are selected but nothing on other pages?

**Comment by joshblack** [comment]
Hey @psachs21! Sorry for disappearing on this issue, unfortunately some other efforts prevented our attention from being focused on this thread. Just wanted to say thanks for outlining this stuff already, am taking a look now and wanted to add some additional thoughts as well.

> The primary issue being that the current sorting API (on DataTable) makes the assumption that it has all the rows available to it.

Totally does. Like you mentioned, we need to be able to support when the table is loaded in-memory client-side in addition to only available from the remote source.

I really like the idea that you had for `getRows`, and I think it can easily be extended to include pagination-related props as well.

> how do we want the checkbox in the header to behave with paging?

Yeah, I agree. This one feels very non-obvious as to what is correct in this situation. I would expect that if the user clicks on that, that all items would be considered selected. I'm unsure how to communicate this through a batch action, though.

My immediate thought is that if we're working with a remote data source, we need to support the notion of `remoteRowCount` to specify how many items are indeed in this collection. When the select all mark is checked, then that means that all items should be considered selected. When the batch action button is clicked, then this remote row value should be passed as an argument for teams to read form. When the user initiates a change to the next page, the items should appear selected even though they were just loaded in.

---

**Comment by psachs21** [comment]
I'm a little bit concerned with my initial `getRows` idea, mostly because for the usual remote use case, if the filters/sorting is asynchronous, getRows would also need to be asynchronous. But if we're down with that, I think it could work. As long as getRows is only called at most once per filter/sort action.

**Comment by psachs21** [comment]
Are we then putting the pagination component within the datatable component? If that's the case, it will eliminate some of the APIs we'd need.

I am concerned about maintaining the pages inside of the datatable though. Say page 1 contains [A, B, C], the user changes to page 2, we load in [D, E, F] (now data table has [A, B, C, D, E, F]), and then the user returns to page 1.
If the backend has changed to have page 1 = [0, A, B, C], our datatable component won't know about it. And won't be able to get it. Maybe that's not a usecase we consider, but I think it's something to think about.

**Comment by joshblack** [comment]
Closing in favor of: https://ibm.biz/BdZnS7
