### ISSUE TITLE
Can you do class bx--tooltip__trigger adjustable as it done for bx--tooltip?

### ISSUE THREAD

**Issue by TatyanaBol** [carbon-design-system/carbon-components-react#492]
I can't change bx--tooltip__trigger class only for one specific tooltip. All changes effect on all tooltips. 
When I add my class bx--tooltip__trigger.myClass it doesn't effect.

**Comment by asudoh** [comment]
@TatyanaBol Do you mean you want to change look and feel of specific trigger button?

**Comment by TatyanaBol** [comment]
yes, I would want to change style of specific tooltip so that it this does not affect any other tooltip.
In case of bx--tooltip I created class .bx--tooltip.myClass.
In case of bx--tooltip__trigger it doesn't work
Thanks
