### ISSUE TITLE
Enhancement: Visual indicator that Select is currently invalid

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-components-react#493]
## Detailed description

The TextInput does a great job allowing me to specify an invalid message and have it render underneath the component.

![image](https://user-images.githubusercontent.com/6663002/35004272-0629b1c6-fab5-11e7-9e48-efd15e63d31e.png)

I would like a similar visual indicator added to the Select input as I am using non-selectable Placeholder text for my initial value, but want to visually show the user that they need to select this before they are allowed to submit the form.   You can see here that my form knows it's invalid, however nothing visually indicates to the user that it's a problem with the "Select an event" Select widget.
![image](https://user-images.githubusercontent.com/6663002/35004378-77290dcc-fab5-11e7-9e2e-715ed3048582.png)

As its simplest implementation you could take an invalid prop like the TextInput and just render the message underneath if passed.

> Is this issue related to a specific component?
Select

## Add labels
enhancement

**Comment by tw15egan** [comment]
Closing in favor of https://github.com/carbon-design-system/carbon-components-react/issues/1017, which will be resolved with https://github.com/carbon-design-system/carbon-components-react/pull/1019
