### ISSUE TITLE
If Select has never been selected (i.e. the selected option is hidden from the list) the dropdown shows the first entry selected

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-components-react#494]
## Detailed description
To me this is a bug (maybe a matter of UX opinion is needed).  
To reproduce, hide the first option in the list (i.e. placeholder usecase)
You can see an example in the default storybook for the Select widget
http://react.carbondesignsystem.com/?selectedKind=Select&selectedStory=enabled&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel

Notice when you pop out the drop down for the very first time that the (unselectable) "Category 1" option is marked with a check box.
![image](https://user-images.githubusercontent.com/6663002/35005838-6c2972e0-faba-11e7-8716-0eef8ddb1405.png)

This seems very strange to me since the user has never interacted with this Select widget before.  To me, the checkbox should only render if the user has actually selected something previously.  It appears that this first option is marked selected simply because it's the first in the list.

> Is this issue related to a specific component?
Select

## Add labels
bug?

**Comment by tw15egan** [comment]
I think it is just default html5 UX being applied here, see https://codepen.io/tjegan/pen/zpmbmo. Something will always be given the `selected` parameter
