### ISSUE TITLE
Dropdown in a Modal: needs styling improvements

### ISSUE THREAD

**Issue by emmafull** [carbon-design-system/carbon-components-react#506]
## Detailed description

> Is this issue related to a specific component?

Yes. Dropdown and Modal.

> What did you expect to happen? What happened instead? What would you like to see changed?

When the dropdown menu is clicked, it expands in the modal without a visible change on the screen. The modal becomes scrollable to get the menu in view (might not be obvious to inexperienced users). The menu is also positioned where the left side and bottom seem cut off, missing the outline. It would be an improvement if either the Modal automatically scrolled so the menu is in view, or that the Modal would grow to the length needed to show the menu. A good solution would show the dropdown menu without additional user interaction after clicking the menu. It would look nicer if the outline was on all sides on the menu, or it was removed.

> What browser are you working in?

Chrome v64

> What version of the Carbon Design System are you using?

"carbon-components": "^7.8.0",
"carbon-components-react": "~3.10.1"

## Steps to reproduce the issue

1. Implement a Dropdown menu inside of a Modal. I saw the behavior when the Dropdown is positioned as the last component in the Modal.
2. Expand the dropdown menu.
3. Notice the modal does not expand or scroll to show the menu.
4. Scroll down in the modal to see the dropdown menu.
5. Notice the left and bottom sides of the menu are missing the outline.

## Additional information

<img width="299" alt="dropdown-in-modal" src="https://user-images.githubusercontent.com/11358963/35108145-5f3cb130-fc38-11e7-85ce-a8980f085fe1.png">

**Comment by tay-aitken** [comment]
@emmafull did you create a PR to fix this issue by any chance?

**Comment by tay-aitken** [comment]
Closing for now due to inactivity. Feel free to re-open.
