### ISSUE TITLE
Can Toggle act more like a form component with an onChange prop?

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-components-react#510]
I'm using Toggle within a Redux Form, and it assumes that every element is firing a change event that looks like a browser "event".  Unfortunately the only event available from Toggle is the onToggle event, and it sends the parsed value instead of the full event.  This causes issues with the Redux-Form wrapper when I try and listen to it's changes

## Detailed description

Can we leave the onToggle event as is, but support firing an additional onChange event that sends the whole event upstream so redux-form can notify me?

> Is this issue related to a specific component?
Toggle

## Add labels
enhancement

**Comment by joshblack** [comment]
Hi @scottdickerson! 👋  Thanks so much for taking the time to make this issue 😄

Definitely is a fair enhancement, will try and get it prioritized! In the meantime, would welcome any kind of contributions for this from outside teams, as well.
