### ISSUE TITLE
allow user to pass a custom svg icon to CardContent

### ISSUE THREAD

**Issue by chovy** [carbon-design-system/carbon-components-react#515]
CardContent component currently only supports carbon icons. We would like to pass our own svg markup to the component and have it rendered.

**Comment by asfordmatt** [comment]
We have a similar requirement, but want to be able to use a custom icon in any Carbon component that takes a icon prop. I have a proposal for that, but it needs the custom icons to be loaded already, such as via `svg-sprite-loader`, so you can refer to them like this:
```
<svg><use xlink:href="#myicon"></use></svg>
```
The Icon component would then look for a prefix in the iconName such as ‘xlink’ and if found generate the above svg. I can work on a PR for that if you think it would be generally useful.
