### ISSUE TITLE
Failed to execute 'removeEventListener' on 'EventTarget' line 150

### ISSUE THREAD

**Issue by monte-hayward** [carbon-design-system/carbon-components-react#527]
## Detailed description

componentWillUnmount results in JS error:
Uncaught TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.

> Is this issue related to a specific component?

yes. DatePicker

> What did you expect to happen? What happened instead? What would you like to see changed?

Component unmounts without error

> What browser are you working in?
chrome

> What version of the Carbon Design System are you using?

5.9.2 and 5.11.0 exhibit the issue.
5.6.2 uses cal.destroy(), and does not have the issue

## Steps to reproduce the issue

1. add date picker to a form
2. use a react prop to hide and show form
3. load page
4. show form
5. hide form

## Additional information

Uncaught TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.
    at DatePicker.componentWillUnmount (DatePicker.js:150)
    at callComponentWillUnmountWithTimer (react-dom.development.js:8732)
    at HTMLUnknownElement.callCallback (react-dom.development.js:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:581)
    at invokeGuardedCallback (react-dom.development.js:438)
    at safelyCallComponentWillUnmount (react-dom.development.js:8739)
    at commitUnmount (react-dom.development.js:8865)
    at commitNestedUnmounts (react-dom.development.js:8901)
    at unmountHostComponents (react-dom.development.js:9184)
    at commitDeletion (react-dom.development.js:9234)
componentWillUnmount @ DatePicker.js:150
callComponentWillUnmountWithTimer @ react-dom.development.js:8732
callCallback @ react-dom.development.js:542
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
safelyCallComponentWillUnmount @ react-dom.development.js:8739
commitUnmount @ react-dom.development.js:8865
commitNestedUnmounts @ react-dom.development.js:8901
unmountHostComponents @ react-dom.development.js:9184
commitDeletion @ react-dom.development.js:9234
commitAllHostEffects @ react-dom.development.js:9926
callCallback @ react-dom.development.js:542
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
commitRoot @ react-dom.development.js:10015
performWorkOnRoot @ react-dom.development.js:11017
performWork @ react-dom.development.js:10967
batchedUpdates @ react-dom.development.js:11086
batchedUpdates @ react-dom.development.js:2330
dispatchEvent @ react-dom.development.js:3421

```html
          <FormGroup legendText="Date Created">
            <DatePicker id="date-picker" onChange={dateRange.bind(this)} datePickerType="range">
              <DatePickerInput
                className="some-class"
                labelText="From"
                onClick={noop}
                onChange={noop}
                placeholder="mm/dd/yyyy"
                id="date-range-start"
              />
              <DatePickerInput
                className="some-class"
                labelText="To"
                onClick={noop}
                onChange={noop}
                placeholder="mm/dd/yyyy"
                id="date-range-end"
              />
            </DatePicker>
            <a onClick={dateRange}>clear</a>
          </FormGroup>
```

**Comment by marijohannessen** [comment]
Thanks for creating this issue! We'll try and get to it asap. We also welcome contributions if you figure out how to fix it in the meantime!

**Comment by maosenchen6ix** [comment]
Experiencing the same here

**Comment by marijohannessen** [comment]
This should be fixed in the latest release [v5.16.4](https://github.com/carbon-design-system/carbon-components-react/releases/tag/v5.16.4). Can you try and update to this and see if that resolves it? Thanks!

**Comment by maosenchen6ix** [comment]
@marijohannessen Just confirmed that updating to `v5.16.4` solves this issue

**Comment by marijohannessen** [comment]
Great! Closing this issue then 😄
