### ISSUE TITLE
Search component placeholder and label won't allow for i18n

### ISSUE THREAD

**Issue by apollomusa** [carbon-design-system/carbon-components-react#530]
We are using https://github.com/yahoo/react-intl to i18n our repo. 

When using the `<Search />` component the following props: 

- `labelText`
- `placeHolderText`

Won't allow us to i18n the component which looks like: 

```
labelText={<FormattedMessage id="table.from" />}
placeHolderText={<FormattedMessage id="table.from" />}
```

As the `propTypes` only allow for `String` and not `Object`.

Please adjust the propTypes to allow for Objects as well

**Comment by asudoh** [comment]
Created a PR: https://github.com/carbon-design-system/carbon-components-react/pull/541 The placeholder is an attribute so cannot be React nodes, though.
