### ISSUE TITLE
Pagination is using includes feature, but includes is not supported by IE 11

### ISSUE THREAD

**Issue by bjakob01** [carbon-design-system/carbon-components-react#533]
## Detailed description
The IE 11 cannot render a table with pagination - the IE throws an exception: "SCRIPT438: Object doesn't support property or method 'includes'" 

The reason for this problem is, that Pagination.js uses .includes
>>>>>
...
return _ret = (_temp = (_this = _possibleConstructorReturn(this, (_ref = Pagination.proto || Object.getPrototypeOf(Pagination)).call.apply(_ref, [this].concat(args))), _this), _this.state = {
page: _this.props.page,
pageSize: _this.props.pageSize && _this.props.pageSizes.**includes**(_this.props.pageSize) ? ....
...
<<<<<

For this carbon rect component, the following browser list is defined:
"browserslist": [
   "ie >= 9",
   "last 2 versions",
   "safari >= 7"
 ],

If IE is supported, then includes must not be used and must be replaced by e.g. indexOf, or the missing includes feature must be implemented by a polyfill

> Is this issue related to a specific component?
I detected this problem just in Pagination component

> What did you expect to happen? What happened instead? What would you like to see changed?
I want to have the includes replaced by e.g. indexOf or polyfill must be implemented for includes

> What browser are you working in?
IE 11

> What version of the Carbon Design System are you using?
"carbon-components-react": "3.14.0",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
continuous

## Steps to reproduce the issue

1. Step one
set pagination properties: ... pageSize: this.state.pageSize
2. Step two
render pagination with IE 11

**Comment by joshblack** [comment]
Hi there! 👋  Thanks so much for taking the time to make this issue 😄

We currently only offer support for the latest version and previous versions of major browsers, in addition to Firefox ESR. However, this issue can easily be resolved by adding the appropriate polyfill for `Array#includes`. Hope that helps!
