### ISSUE TITLE
A11Y: label in SelectableTile should not have a presentation role

### ISSUE THREAD

**Issue by shijinupc** [carbon-design-system/carbon-components-react#539]
## Detailed description

> Describe in detail the issue you're having. Is this a feature request (new component, new icon), a bug, or a general issue?

label in SelectableTile should not have a presentation role

> Is this issue related to a specific component?

Tile

> What did you expect to happen? What happened instead? What would you like to see changed?

label in SelectableTile should not have a presentation role

## Additional information
<img width="1280" alt="6ed5c9dc-01ed-11e8-8c58-a6bbefb7b0a8" src="https://user-images.githubusercontent.com/8380554/35422762-49d9b114-0285-11e8-8de0-1e13df62028c.png">

**Comment by tw15egan** [comment]
@shijinupc, thanks for taking the time to create an issue! Should this be removed, or replaced with a different rule?

**Comment by shijinupc** [comment]
Please just remove it if you don't have any other concerns, and you can refer to https://www.w3.org/TR/html-aria/#docconformance for more info.
