### ISSUE TITLE
Tooltip simple does not allow word-wrap: break-word;

### ISSUE THREAD

**Issue by mandie12** [carbon-design-system/carbon-components-react#542]
<img width="423" alt="screen shot 2018-01-26 at 11 46 52" src="https://user-images.githubusercontent.com/5472918/35438502-ade246fe-028e-11e8-9ee5-937cd55d60d6.png">

Tooltip simple does not allow word-wrap: break-word; on Chrome

**Comment by tw15egan** [comment]
Can you try `white-space: pre` on the `:before` element? And make sure you have a space after the period. This should then format correctly.

**Comment by tw15egan** [comment]
Issue moved to [carbon-design-system/carbon-components #529](https://github.com/carbon-design-system/carbon-components/issues/529) via [**ZenHub**](https://www.zenhub.com/)

**Comment by mandie12** [comment]
Hi,

Thanks for your help. This doesnt seem to work for me:
![screen shot 2018-01-29 at 16 47 59](https://user-images.githubusercontent.com/5472918/35522496-6963d2a8-0514-11e8-917f-15972de0ccb4.png)

**Comment by tw15egan** [comment]
In your HTML, can you hit `enter` after the first line? Like this: 

![screen shot 2018-01-29 at 11 06 45 am](https://user-images.githubusercontent.com/11928039/35523471-8e05213c-04e4-11e8-9a19-ed319b19d44c.png)

**Comment by mandie12** [comment]
Hi TJ,
I am using locale messages in my project. So I will not know the size of the text as it changes for each language, therefore putting the text on a new line will not be possible. I can see in the other tooltip component it wraps the text automatically. Would that be an option for tooltip simple?
Thanks,

**Comment by tw15egan** [comment]
Since it's just using a data attribute + `content: attr(data-tooltip-text);`, it won't work unless you set a specific width + change `white-space` to something other than `nowrap`. Is using the regular `Tooltip` component not an option?
