### ISSUE TITLE
Update CodeSnippet to allow reference to <pre>

### ISSUE THREAD

**Issue by krbrewer** [carbon-design-system/carbon-components-react#55]
The pre tags inside of CodeSnippet contain the content that a user would expect to see copied when they click the copy button. As of now there is no direct way to reference this node element while setting up a copy function.

**Comment by hellobrian** [comment]
Apologies, this issue got lost under more recent issues. Will mark this as a bug

**Comment by joshblack** [comment]
Hi there! 👋 

Thanks so much for reporting this issue. I went ahead and opened up a PR #273 for this, let me know if it doesn't address your needs or doesn't match the behavior you expect!
