### ISSUE TITLE
PaginationV2 page menu label blank when there are no items

### ISSUE THREAD

**Issue by jrpomeroy** [carbon-design-system/carbon-components-react#553]
![image](https://user-images.githubusercontent.com/18622709/35580651-43feed86-05af-11e8-9d50-35385e9d28b0.png)

The drop down menu label is blank. Probably this should just not be displayed if there are no pages to choose from. Or at least say "0" and be disabled.

**Comment by aagonzales** [comment]
Agreed that pagination bar should not appear if there is zero data to display. @tw15egan not sure if this is a component or product side implementation change.
