### ISSUE TITLE
DataTable search and action buttons have different heights

### ISSUE THREAD

**Issue by jrpomeroy** [carbon-design-system/carbon-components-react#554]
![image](https://user-images.githubusercontent.com/18622709/35581050-5228d6be-05b0-11e8-91cb-108a4881f5cc.png)

In the DataTable header it looks weird that the Search input is 32px high and the action button is 40px high. Maybe these should be the same height.

**Comment by joshblack** [comment]
Hi @jrpomeroy! 👋  Thanks so much for taking the time to make this issue 😄

I think this is definitely a mistake on our end, if you examine the example of a Data Table on this page: http://carbondesignsystem.com/components/data-table/code does it match your expectation?

**Comment by aagonzales** [comment]
Both the search field and button should be 32px tall as designated in both the component code sample and the design spec in the kit. Which version of the Carbon component are you using? Not sure why the larger button is showing up for you.

**Comment by tw15egan** [comment]
If you're using the React version, you should just be able to add the `small` prop to the Button. I will update the stories to reflect this change as well
