### ISSUE TITLE
DataTable sort icon smaller when column header wraps

### ISSUE THREAD

**Issue by jrpomeroy** [carbon-design-system/carbon-components-react#555]
![image](https://user-images.githubusercontent.com/18622709/35581773-74ca33e6-05b2-11e8-8477-724420120ebd.png)

When the column header label wraps the sort icon gets smaller.

**Comment by marijohannessen** [comment]
@aagonzales should the column header labels be able to wrap? do we have guidelines around this?

**Comment by joshblack** [comment]
Bump @aagonzales if you have time to give input about this 🙂

**Comment by aagonzales** [comment]
(sorry sometimes I don't get notified from public github)

Column headers can wrap but no more than two lines. The headers should also be left aligned and not centered. Actually, they should be aligned the same way the content in the column is aligned. We allow right alignment for numbers.

**Comment by aagonzales** [comment]
Side note: there's actually another visual bug with tables headers. It looks like there's `letter-spacing` applied and there shouldn't be.

**Comment by joshblack** [comment]
Going to move this over to `carbon-components` for style fixes!

**Comment by joshblack** [comment]
Issue moved to [carbon-design-system/carbon-components #720](https://github.com/carbon-design-system/carbon-components/issues/720) via [**ZenHub**](https://www.zenhub.com/)
