### ISSUE TITLE
NumberInput onChange produces unhelpful event

### ISSUE THREAD

**Issue by giltohar** [carbon-design-system/carbon-components-react#566]
I am using NumberInput and am trying to use the onChange property to update the state when the user updates input. For most input based react components, event.target.value or event contain the value, but in this case I'm not sure how to derive the value from the event produced. 

I tried reproducing the issue in Sandbox, https://codesandbox.io/s/nwn6mozxnp. And you can see the issue when the function, handleCellCount, logs event.

> What version of the Carbon Design System are you using?

In my project, we use 5.17.1, and i believe the same in the codesandbox.

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

The project is part of the CFaaS offering that we are developing.

## Steps to reproduce the issue
the sandbox link above

**Comment by asudoh** [comment]
I see the Sandbox link assigns a return value of a function as an event handler: `onChange: this.handleCellCount()`. Given that, `handleCellCount()` is called from `render()` instead of the event being fired, which may have looked like the event object being lost. I guess the author of the issue wanted to assign the function directory as the event handler instead, like `onChange: this.handleCellCount`.

**Comment by giltohar** [comment]
the same occurs even if my function is embedded in the jsx, the event information is still unhelpful and doesn't indicate value

**Comment by giltohar** [comment]
also, i don't think i have permissions to reopen the issue

**Comment by asudoh** [comment]
Just in case if my last comment was unclear - `onChange: this.handleCellCount()` should be replaced with `onChange: this.handleCellCount`. Hope this helps. Thanks!

**Comment by giltohar** [comment]
I get the same event it seems, regardless of whether i add the () at he function call or not...

**Comment by asudoh** [comment]
Just in case, I was suggesting that assigning `handleCellCount` function ref to `onChange` instead of the result of `handleCellCount()` call. This link should demonstrate what I meant: https://codesandbox.io/s/v0yk7qzn3

**Comment by giltohar** [comment]
The logs produced in the console from console.log(event) in your example are the same as mine, they don't contain the value of the NumberInput??

**Comment by asudoh** [comment]
What I saw is different - It shows a proxy object which is a synthetic event React creates:

![chrome](https://user-images.githubusercontent.com/1259051/35942716-e625be50-0c99-11e8-9473-8a75bbd173de.png)

It’d be great if you have comparable screenshot/movieshot - Thanks!

**Comment by giltohar** [comment]
I'm not sure you understand. I got the same event. My issue is not that i don't get an event, it's that i don't how to extract the value of the NumberInput component from the event. I added a text input to the sandbox, and if you notice its triggered event, contains the value!
https://codesandbox.io/s/kk88lvwx8v

**Comment by asudoh** [comment]
Great that you articulated what you meant! Didn’t know recent change there made the event firing asynchronous.
