### ISSUE TITLE
Enhancement: Allow Switch within Content Switcher to display an Icon and Text

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-components-react#585]
## Detailed description
Currently the <Switch> component within a <ContentSwitcher> only accepts a text prop.  Would like an enhancement to also support an icon prop (and iconClass prop) to allow rendering an img next to the text prop

> Is this issue related to a specific component?
Switch

> What did you expect to happen? What happened instead? What would you like to see changed?
![image](https://user-images.githubusercontent.com/6663002/35937349-91f8a952-0c0b-11e8-82d8-1752e30094aa.png)

> What browser are you working in?
chrome

> What version of the Carbon Design System are you using?
5.17.1

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
no

## Add labels
enhancement

**Comment by marijohannessen** [comment]
@bsonefeld is this something you think we should add to the component?

**Comment by bsonefeld** [comment]
Yeah, I think this looks like a nice enhancement!
