### ISSUE TITLE
SelectableTile - should not be able to select multiple tiles

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon-components-react#586]
**Currently:**
![tiles](https://user-images.githubusercontent.com/11928039/35941368-97d2e336-0c17-11e8-8767-a479aa80cf13.gif)

**To Be:**
Can only select one, will probably need a wrapper component like `RadioButtonGroup`

**Comment by alisonjoseph** [comment]
Are we adding this as an option to only select one, or changing the default behavior completely, and if so, would that possibly break this for someone using it as is?

**Comment by marijohannessen** [comment]
Good question, do you think we could add it as a variation @bsonefeld ?

**Comment by alisonjoseph** [comment]
I had to create two new components since it requires a `TileGroup` as a wrapper almost exactly how radio button groups work. We could deprecate the `SelectableTile` in a future version if we don't want to offer that pattern?

**Comment by bsonefeld** [comment]
I would like it to be a variation.. so: 

Selectable Tile (styled with radio buttons) 
Multi-select Tile (styled with checkboxes)

**Comment by alisonjoseph** [comment]
I think that naming makes the sense, however, currently the `SelectableTile` uses checkboxes so I don't think we can switch that without it being a breaking change. I have this built out and named `RadioTile` which lives inside a `TileGroup` component, but I definitely don't love that name.

**Comment by bsonefeld** [comment]
So the current `Selectable Tile` uses checkboxes under the hood but it's styled as a radio button?

**Comment by alisonjoseph** [comment]
@bsonefeld Yes, it uses a checkbox under the hood. The styling for both (radio or checkbox) is the same, the only difference is if you can select one or multiple. 

I think for now we are going to name it RadioTile and make a change in v9 to fix the naming conventions.
