### ISSUE TITLE
In Chrome, TextInput component with type "email" is not highlighted in red when invalid email address format is input

### ISSUE THREAD

**Issue by ilovepumpkin** [carbon-design-system/carbon-components-react#59]
As you can see, in Firefox it works well. 

Chrome
![image](https://user-images.githubusercontent.com/11310645/27421680-0c27cbe4-575e-11e7-90bc-70b93b69099e.png)

Firefox
![image](https://user-images.githubusercontent.com/11310645/27421715-249651be-575e-11e7-8eb5-72a370944345.png)

**Comment by tw15egan** [comment]
This seems to be the [default browser behavior](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email) for each. Chrome will validate on submit, but it will not apply any styles on blur.

If you'd like to add data validation on blur, you can add the `data-invalid` attribute on the input and add some js to handle the addition/removal based on your needs. [Here](http://www.carbondesignsystem.com/components/form/code) is the documentation for that

**Comment by ilovepumpkin** [comment]
okay, thank you!
