### ISSUE TITLE
How to customize theme? [proposed label] question discussion

### ISSUE THREAD

**Issue by lukasz-dobosz-c** [carbon-design-system/carbon-components-react#590]
Is there a way to customize theme other than overwriting css manually? If not there are some plans or ideas in order to address that?
[proposed Label] question

**Comment by tw15egan** [comment]
Hey, have you checked out themes.carbondesignsystem.com? You can also take a look at [this repo](https://github.com/carbon-design-system/carbon-themes) for an example style sheet on how to override our styles. Hope this answers your question!
