### ISSUE TITLE
a11y audit: Footer a11y fixes

### ISSUE THREAD

**Issue by marijohannessen** [carbon-design-system/carbon-components-react#611]
### Detailed description

- [ ] A 'contentinfo' role is not permitted without the presence of a 'main' role
![screen shot 2018-02-14 at 2 41 59 pm](https://user-images.githubusercontent.com/5447411/36227040-62921cae-1195-11e8-8a29-f649c472d952.png)

**Comment by tw15egan** [comment]
This is being caused by storybook and the `Container` not having a `role="main"`. I'll add this to the storybook container so that we do not encounter these flags in the future
