### ISSUE TITLE
a11y audit: OrderSummary a11y fixes

### ISSUE THREAD

**Issue by marijohannessen** [carbon-design-system/carbon-components-react#617]
### Detailed description

- [x] A WAI-ARIA widget must have an accessible name (applies to `bx--dropdown` and `bx--dropdown-list`)
![screen shot 2018-02-15 at 2 29 26 pm](https://user-images.githubusercontent.com/5447411/36279416-aa58938e-125c-11e8-8305-c910f25bc578.png)

- [x] All content must reside within a WAI-ARIA landmark or labelled region role.
![screen shot 2018-02-15 at 2 30 26 pm](https://user-images.githubusercontent.com/5447411/36279481-e3aca6de-125c-11e8-9d7b-ef6b951d7068.png)

- [ ] Certain ARIA roles must contain particular children
![screen shot 2018-02-15 at 2 31 38 pm](https://user-images.githubusercontent.com/5447411/36279522-fd610fb6-125c-11e8-945d-6daa955f4ca2.png)

- [x] Keyboard interaction: It tabs through the dropdown even when it's closed

**Comment by tw15egan** [comment]
@marijohannessen not sure how to resolve the 3rd (I also can't get it to appear). The dropdown currently has `role="option"`, and if I switch it to `role="menuitem"`, I get an error about `aria-selected is invalid with role="menuitem"`.

<img width="724" alt="screen shot 2018-03-02 at 2 43 00 pm" src="https://user-images.githubusercontent.com/11928039/36920942-0b6e26bc-1e28-11e8-88a1-d9550b422a1c.png">
