### ISSUE TITLE
Toolbar checkbox becomes unchecked after click

### ISSUE THREAD

**Issue by ivanshen** [carbon-design-system/carbon-components-react#628]
## Detailed description

I am using the toolbar overflow menu with checkbox here. 
http://react.carbondesignsystem.com/?selectedKind=Toolbar&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

When I open the overflow menu and click a filter by checkbox and the overflow menu closes, every checkbox in overflow menu always becomes unchecked when I open it again. I can see this problem on the demo react carbon  website too.

> What browser are you working in? I see this in Chrome.

> What version of the Carbon Design System are you using?
I am using the latest version of carbon.

**Comment by codeYuyuan** [comment]
The onChange property for checkbox seems to only listen the changes on other attributes instead of listening to the onClick behavior
Here is an example https://codesandbox.io/s/lq93vxo39

**Comment by joshblack** [comment]
cc @asudoh if you have any thoughts here! Seems like some kind of event propagation issue.
