### ISSUE TITLE
[File Uploader] Need a way to clear inputs

### ISSUE THREAD

**Issue by loganmccaul** [carbon-design-system/carbon-components-react#632]
## Detailed description

The File Uploader component currently keeps track of the file names that were uploaded in an internal state. The internal state can currently only be cleared by clicking on the remove icon tied to each uploaded file. However, we need the parent component to be able to clear the internal state.

We are using the File Uploader in a modal and we want to be able to clear the uploaded files when we hide the modal. Therefore the File Uploader component needs to expose a way to reset it's internal state.

> Is this issue related to a specific component?
File Uploader

**Comment by marijohannessen** [comment]
Fixed in #633
