### ISSUE TITLE
PaginationV2: weird line style with pageInputDisabled true

### ISSUE THREAD

**Issue by nicoxxie** [carbon-design-system/carbon-components-react#637]
![screen shot 2018-02-21 at 10 51 50 am](https://user-images.githubusercontent.com/17915105/36493443-3f575910-16f5-11e8-8a82-d98b48480d5e.png)

There is this line between the carets, think this may need extra padding?

**Comment by tw15egan** [comment]
@carbon-design-system/design what is the intended design here when the page input has been disabled? Right now it is just adding a `|` with no padding. Should this entire area just been removed? Or should we increase the padding?

**Comment by bsonefeld** [comment]
So there's only one page of data to show? 

I think the small select would still show but just be disabled (50% opacity).

**Comment by tay-aitken** [comment]
Should there even be pagination if there is only one page. I figured it would show up when there are two or more pages worth of content.

**Comment by nicoxxie** [comment]
@bsonefeld @tay-aitken page input should not depend on what page you are on, if the backend does not support filter by page number pageInputDisabled is set to false.

**Comment by aagonzales** [comment]
I don't think it was ever built but in the kit we do have this defined in the pagination section on the component page.
![image](https://user-images.githubusercontent.com/11670886/36508503-837231ce-1722-11e8-9368-770cd0f47eea.png)
