### ISSUE TITLE
Object.values isn't transpiled to be compatible with Node 6

### ISSUE THREAD

**Issue by jyxia** [carbon-design-system/carbon-components-react#638]
> Is this issue related to a specific component?

TableHeader.js and this [line](https://github.com/carbon-design-system/carbon-components-react/blob/e7cb836d369031278f0d4487ce2a61509d0ffb14/src/components/DataTable/TableHeader.js#L93)

> What did you expect to happen? What happened instead? What would you like to see changed?

`Object.values` got transpiled

> What browser are you working in?

Node 6

> What version of the Carbon Design System are you using?

8.9.2

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Cloud subscriptions

**Comment by joshblack** [comment]
Hi @jyxia! 👋 Unfortunately, `Object.values` isn't something that is transpiled by babel. Instead, you'll have to provide a polyfill for the environment to get this to work in all environments. There are packages like `core-js` or `babel-polyfill` that can help out with this 😄

**Comment by jyxia** [comment]
I'm a surprised though. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values), `Object.values` isn't supported by IE at all, and in the babel configuration, `ie >= 11` is listed there. If babel didn't transpile it correctly, how does it support IE >= 11?

**Comment by joshblack** [comment]
You're totally right, `Object#values` is an ES2017 proposal feature and isn't supported in some of our target browsers.

However, if you examine the `babel-preset-2017` package [here](https://github.com/babel/babel/blob/master/packages/babel-preset-es2017/src/index.js), you'll notice that it doesn't provide a transform for this language feature. 

SImilary, if you search the supported babel packages [here](https://github.com/babel/babel/tree/master/packages), you'll see that there is no transform available at all in Babel for this language feature.

However, using `babel-polyfill` and `babel-preset-env` will polyfill your environment based on usage. In the case of running in Node, that's where `core-js` will come in to help polyfill the environment.

Hope that helps! Let me know if I'm misunderstanding something here 😄

**Comment by jyxia** [comment]
Nice, well explained. A good research too. 👍

**Comment by joshblack** [comment]
Of course! Cheers 🍻

**Comment by asfordmatt** [comment]
Hi @joshblack I just wanted to add a 'me too' to this issue - we also need to support Node 6 and so this change broke us, and we had to spend some time adding the polyfill across a number of repos, and also upgrading Cypress to work with this. It would be great if you could give a heads up for any similar breaking changes in the future? Maybe even worth bumping the major version?

**Comment by joshblack** [comment]
Hey @asfordmatt! Definitely fair 😅 if it helps, in response we've decided to try to surface a polyfill package for teams to use: https://github.com/carbon-design-system/carbon-polyfill with the goal being that updates to the packages that require polyfill updates will be bumping their peerDependency on this polyfill package.

If you would like to help validate this package, it would be very useful for us! If you're interested, just DM me on Slack 😄
