### ISSUE TITLE
Request: Add 'small' class option to ModalWrapper trigger Button

### ISSUE THREAD

**Issue by ColbyJohnIBM** [carbon-design-system/carbon-components-react#641]
## Detailed description

> Describe in detail the issue you're having. Is this a feature request (new component, new icon), a bug, or a general issue?

Feature request: allow 'small' class to be passed down from the ModalWrapper component to the trigger [Button](https://github.com/carbon-design-system/carbon-components-react/blob/master/src/components/ModalWrapper/ModalWrapper.js#L99) component (similar to what was done [here](https://github.com/carbon-design-system/carbon-components-react/pull/346) with the 4 kinds)

> Is this issue related to a specific component?

Yes, ModalWrapper.

**Comment by joshblack** [comment]
Hi @ColbyJohnIBM! 👋  Thanks so much for taking the time to make this issue 😄

Definitely seems like a fair feature request. Adding it to our backlog of items, but will also accept PRs to add in this behavior in the meantime!
