### ISSUE TITLE
Editing states for Data Table

### ISSUE THREAD

**Issue by bsonefeld** [carbon-design-system/carbon-components-react#644]
Build out the Editing states for Data Table. 

Design issues for reference: (internal)
* [Full edit mode](https://github.ibm.com/Bluemix/carbon-issues/issues/318)
* [Inline editing](https://github.ibm.com/Bluemix/carbon-issues/issues/385)

**Comment by joshblack** [comment]
Hey! Could you add the design specs to the issues themselves? 

Inline Editing: #489
Full edit mode: #498

**Comment by bsonefeld** [comment]
@aagonzales ☝️

**Comment by joshblack** [comment]
Oh sorry, just realized that those links weren't box links. Are they just to map the public issues to internal issues?

**Comment by aagonzales** [comment]
Do you want me to re-document them here? @bsonefeld @joshblack

**Comment by joshblack** [comment]
No sweat! I went ahead and added a spec link to both issues 😄 Closing as dup.
