### ISSUE TITLE
Request: Interior Left Navigation Title

### ISSUE THREAD

**Issue by depietronick** [carbon-design-system/carbon-components-react#656]
Following new specifications laid out by the Console Design team, the Interior Left Nav will contain a title and icon for "World" views within IBM Cloud.

Guidelines and visual specs here: https://github.ibm.com/Bluemix/console-design-kit/wiki/Interior-Left-Navigation

![interior-left-nav-style-1](https://user-images.githubusercontent.com/36895500/36742938-9e7dc04c-1bae-11e8-8369-448c7b898611.png)

**Comment by asudoh** [comment]
Issue moved to [carbon-design-system/carbon-addons-cloud #34](https://github.com/carbon-design-system/carbon-addons-cloud/issues/34) via [**ZenHub**](https://www.zenhub.com/)
