### ISSUE TITLE
Interior Left Navigation Selected State

### ISSUE THREAD

**Issue by depietronick** [carbon-design-system/carbon-components-react#658]
## Detailed description

Interior left navigation items are deselected when the page the user sees isn't the same as the interior left nav link.

> Is this issue related to a specific component?

Interior Left Navigation

> What did you expect to happen? What happened instead? What would you like to see changed?

Deselected ILN link appearance after leaving the page the user is on. ILN guidelines and behaviors: https://github.ibm.com/Bluemix/console-design-kit/wiki/Interior-Left-Navigation

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Cloud console

**Comment by asudoh** [comment]
Issue moved to [carbon-design-system/carbon-addons-cloud #33](https://github.com/carbon-design-system/carbon-addons-cloud/issues/33) via [**ZenHub**](https://www.zenhub.com/)
