### ISSUE TITLE
How to import css for carbon-design-system/carbon-components-react

### ISSUE THREAD

**Issue by nidhiag** [carbon-design-system/carbon-components-react#68]
Hi,
I want to use the latest version of bluemix-components-react. which are available at the https://github.com/carbon-design-system/carbon-components-react
can you please explain me how to import styles for that.

```jsx
import {Tooltip, Link} from 'carbon-components-react';

import React from 'react';

class BxTooltip extends React.Component {

constructor(props) {

    super(props);

};

render() {

    return (<div style={{marginTop: "2rem"}}>

        <Tooltip triggerText="" showIcon={true}>

        <p className="bx--tooltip__label">

        Tooltip label

    </p>

    <p>

    tooltip content

    </p>

    </Tooltip>

    </div>);

}

};
export default BxTooltip;
```

**Comment by hellobrian** [comment]
In [Getting Started](https://github.com/carbon-design-system/carbon-components-react#getting-started) docs on README.md:

![image](https://user-images.githubusercontent.com/4185382/27645546-f1ed5cc0-5beb-11e7-85ec-f6cbfc137bb2.png)

There are a handful of ways to import styles. To help you out better, can you tell me some details about your project?

- Did you use `create-react-app` for your project? 
- Do you have autoprefixer setup as a build step? 
- Do you have SCSS compiling setup as a build step?

**Comment by nidhiag** [comment]
We are not using create-react-app, autoprefixer.
We are using SCSS in our code.
Please share the detailed example , on how to import the styles from carbon-components.

**Comment by hellobrian** [comment]
If you're using webpack, there are a few options:
- Import SCSS files directly into your react components using [sass-loader](https://github.com/webpack-contrib/sass-loader) 
- Compile your SCSS so that your CSS files are co-located with your react components and import CSS files with [css-loader](https://github.com/webpack-contrib/css-loader)
- Use CDN as a temporary solution: https://unpkg.com/carbon-components@7.13.1/css/carbon-components.min.css

**Comment by nidhiag** [comment]
We already using the sass-loader and css-loader , but styles are not getting in until we manually use require. I am sharing the webpack.config file . Please help here how to get those styles.

/* global __dirname */

var path = require('path');

var webpack = require('webpack');
var CopyWebpackPlugin = require('copy-webpack-plugin');
const autoprefixer = require('autoprefixer');

var dir_js = path.resolve(__dirname, 'src/client');
var dir_html = path.resolve(__dirname, 'src/client');
var dir_build = path.resolve(__dirname, 'build');
require('es6-promise').polyfill();

module.exports = {
    entry: [path.resolve(dir_js, 'index.js'), 'webpack-hot-middleware/client'],
    output: {
        path: dir_build,
        filename: 'bundle.js'
    },
    devServer: {
        contentBase: dir_build,
    },
    module: {
        loaders: [
            {
                loader: 'react-hot-loader',
                test: dir_js,
            },
            {
                loader: 'babel-loader',
                test: dir_js,
                query: {
                    presets: ['es2015', 'react'],
                },
            },

            {
                test: /\.css$/,
                loader: 'style-loader!css-loader'
            },
            {
                test: /\.sass/,
                loader: 'style-loader!css-loader!sass-loader?outputStyle=expanded&indentedSyntax'
            },

            {
                test: /\.scss$/,
                use: ['style-loader', 'css-loader','sass-loader' ],
            },
            /*{
                test: /\.scss$/,
                loader: 'style-loader!css-loader!sass-loader?outputStyle=expanded'
            },*/
            {
                test: /\.less/,
                loader: 'style-loader!css-loader!less-loader'
            },
            {
                test: /\.styl$/,
                loader: 'style-loader!css-loader!stylus-loader'
            },
            {
                test: /\.(png|jpg|gif|woff|woff2|otf)(\?.*$|$)/,
                loader: 'url-loader?limit=8192'
            },
            {
                test: /\.(ttf|eot|mp4|ogg|svg)(\?.*$|$)/,
                loader: 'file-loader'
            }
        ]
    },
    plugins: [
        // Simply copies the files over
        new CopyWebpackPlugin([
            { from: dir_html } // to: output.path
        ]),
        new webpack.optimize.OccurrenceOrderPlugin(),
   		new webpack.HotModuleReplacementPlugin(),
        // Avoid publishing files when compilation fails
        new webpack.NoEmitOnErrorsPlugin(),
        new webpack.LoaderOptionsPlugin({
            options: {
                context: __dirname,
                postcss: [
                    autoprefixer
                ]
            }
        })


    ],
    stats: {
        // Nice colored output
        colors: true
    },
    resolve: {    
    alias: {
      carboncomponents: path.resolve(__dirname, '.', 'node_modules/carbon-components/')
    }
  },
    // Create Sourcemaps for the bundle
    devtool: 'source-map'
};

**Comment by chrisdhanaraj** [comment]
Hey @nidhiag - you have a few ways to add the `css` in

1) Include it in your HTML via a `link` tag
2) `require` or `import` the compiled css in its entirety from the `css` folder of `carbon-components`
3) Set up your own `.scss` file and - using `sass` - import the specific components you need, and then either import it in your javascript or include in your html.

Ultimately, how to include CSS is out of scope for the issues here though, I'd recommend checking out StackOverflow or the like on that.
