### ISSUE TITLE
Conditional rendering breaking TileGroup

### ISSUE THREAD

**Issue by davidmenendez** [carbon-design-system/carbon-components-react#681]
## Detailed description

> Describe in detail the issue you're having.

I'm trying to implement the selectable tile with dynamic options, but when you include conditional rendering it breaks.

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug

> Is this issue related to a specific component?

yes- `TileGroup`

> What did you expect to happen? What happened instead? What would you like to see changed?

I expect the first option from the example to be omitted as a tile

> What browser are you working in?

firefox

> What version of the Carbon Design System are you using?

latest

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Armada

## Steps to reproduce the issue

 To replicate-
```
<TileGroup
  onChange={action('onChange')}
  name="tile-group"
  defaultSelected="default-selected"
  legend="Selectable Tile Group">
  {true == false &&
    <RadioTile value="standard" id="tile-1" labelText="Selectable Tile">
      Selectable Tile
    </RadioTile>
  }
  <RadioTile
    value="default-selected"
    labelText="Default selected tile"
    id="tile-2">
    Selectable Tile
  </RadioTile>
  <RadioTile value="selected" labelText="Selectable Tile" id="tile-3">
    Selectable Tile
  </RadioTile>
</TileGroup>
```

## Additional information

<img width="1440" alt="screen shot 2018-03-06 at 11 06 03 am" src="https://user-images.githubusercontent.com/6370760/37046638-6a97d3c8-212e-11e8-92c0-f2b29d1ad8c5.png">

it looks like the culprit is this line https://github.com/carbon-design-system/carbon-components-react/blob/eed59f99d0deb3d4a55bae0be8f9e970ab7b54bc/src/components/TileGroup/TileGroup.js#L41 it looks like `React.Children.map` doesn't properly omit items that should be omitted. This can be fixed by using the `toArray` function. Refactoring the code like this fixes this issue-
```
const childrenArray = React.Children.toArray(this.props.children);
const children = childrenArray.map(tileRadio => {
...
```
<img width="1440" alt="screen shot 2018-03-06 at 11 09 40 am" src="https://user-images.githubusercontent.com/6370760/37046842-e79d6cac-212e-11e8-9691-0b1208cda228.png">

**Comment by tw15egan** [comment]
Thanks for providing the code to fix this, makes it much easier! 😄
