### ISSUE TITLE
Missing a disabled anchor option

### ISSUE THREAD

**Issue by jokerstudios** [carbon-design-system/carbon-components-react#69]
Hey I'm using carbon and saw that if I create an anchor instead of a button, I can't disable it:
```js
const button = (
    <button {...other} {...commonProps} disabled={disabled} type={type}>
      {children}
      {buttonImage}
    </button>
  );

  const anchor = (
    <a {...other} {...commonProps} href={href} role="button">
      {children}
      {buttonImage}
    </a>
  );
```
as you can see the `disabled={disabled}` attribute is missing in the anchor.
Could you please update this?

**Comment by hellobrian** [comment]
As far as I know, the `disabled` attribute is only accepted on `<button>` elements, not `<a>`.
