### ISSUE TITLE
[TableHeader]Prop needed for disable sort on a column

### ISSUE THREAD

**Issue by nicoxxie** [carbon-design-system/carbon-components-react#691]
## Detailed description

> Describe in detail the issue you're having.

TableHeader is always showing the caret and no way to disable that.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

TableHeader

> What did you expect to happen? What happened instead? What would you like to see changed?

Default to false unless enabled.

> What browser are you working in?

all

> What version of the Carbon Design System are you using?

5.28.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Cloud

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by joshblack** [comment]
Hi @nicoxxie! 👋 Thanks for making this. We have a PR to fix this in #692 if you want to take a look!

**Comment by nicoxxie** [comment]
@joshblack thanks for the quick turnaround. +1 on the PR
