### ISSUE TITLE
InteriorLeftNavItem doesn't honor the activeHref prop passed to it

### ISSUE THREAD

**Issue by ashpc** [carbon-design-system/carbon-components-react#698]
## Detailed description
When the activeHref is passed down as a prop to the InteriorLeftNavItem then the correct element should be highlighted. However, currently the activeHref prop is not used instead it looks for the window.location.hash.

> Describe in detail the issue you're having.

When I navigate into pages that have a parent page and the activeHref is correctly set on the element the InteriorLeftNavItem doesn't highlight the correct parent element. This is because the component code now looks for window.location.hash and if present it ignores the activeHref passed down. 
For example in case the element on the leftnav `Users` has a  url console.bluemix.net/iam/#/users. When this url is visited the element `Users` is highlighted correctly but when the and the child page having the url console.bluemix.net/iam/#/users/<USER_GUID>?tab=iam is visited it doesn't highlight `Users` in the left nav. In our code we do pass down the element that has to be active using the activeHref props as shown in the screenshot attached below. 

> Is this a feature request (new component, new icon), a bug, or a general issue?

This is a bug as it was working before and after the change in the code to look for window.location.hash introduced this bug.

> Is this issue related to a specific component?

InteriorLeftNavItem Element

> What did you expect to happen? What happened instead? What would you like to see changed?

For example in case the element on the leftnav `Users` has a  url console.bluemix.net/iam/#/users. When this url is visited the element `Users` is highlighted correctly but when the and the child page having the url console.bluemix.net/iam/#/users/de100b921ba5e670d316c6fe3953cfaf?tab=iam is visited it doesn't highlight `Users` in the left nav. In our code we do pass down the element that has to be active using the activeHref props as shown in the screenshot attached below. 
I would like the component to use the activeHref if passed down and if not there then use the window.location.hash instead of ignoring activeHref props.

> What browser are you working in?
All Browsers

> What version of the Carbon Design System are you using?
   "carbon-addons-beta-react": "1.3.2",
    "carbon-addons-bluemix": "0.2.0",
    "carbon-components": "8.11.1",
    "carbon-components-react": "5.19.1",

## Steps to reproduce the issue

1. Go to https://console.bluemix.net/iam/#/users, see that the Users in the leftNav is selected
2.  Click on one of the users name in the table, this will change the url based to https://console.bluemix.net/iam/#/users/<USER_GUID>?tab=iam, you will see that the Users in the leftNav is not selected 

## Additional information
**activeHref='#/users and the item is selected**
![screen shot 2018-03-08 at 9 50 53 am](https://user-images.githubusercontent.com/1907155/37162541-1b4d6bbe-22bb-11e8-98b2-a0da2ea6a16c.png)

**activeHref='#/users and the item is not selected**
![screen shot 2018-03-08 at 9 51 13 am](https://user-images.githubusercontent.com/1907155/37162565-2a3e8630-22bb-11e8-94dd-47f266a32f64.png)

* Screenshots or code

* Notes

**Comment by tw15egan** [comment]
Issue moved to [carbon-design-system/carbon-addons-cloud-react #15](https://github.com/carbon-design-system/carbon-addons-cloud-react/issues/15) via [**ZenHub**](https://www.zenhub.com/)
