### ISSUE TITLE
DataTable should preserve sort when re-rendered and new data should be re-sorted

### ISSUE THREAD

**Issue by AndySeymour2904** [carbon-design-system/carbon-components-react#705]
## Detailed description

> Describe in detail the issue you're having.
When I update data in a DataTable the sort is reset

> Is this a feature request (new component, new icon), a bug, or a general issue?
Feature Request / bug

> Is this issue related to a specific component?
DataTable

> What did you expect to happen? What happened instead? What would you like to see changed?
Expect sort to be preserved and new data to be sorted according to the current sortKey and sortDirection

Happy to provide a PR for this if agreed

**Comment by joshblack** [comment]
Hi @AndySeymour2904! 👋 Thanks so much for taking the time to make this issue 😄 

Definitely agreed that `DataTable` should preserve sort order when re-rendered. Unfortunately we don't have the bandwidth to fix this right now, but will gladly accept any/all PRs to provide this behavior!

**Comment by joshblack** [comment]
Closed by #728 and in subsequent bug fixes, I think 😄
