### ISSUE TITLE
DataTable: TableBatchActions should de-select rows on Cancel.

### ISSUE THREAD

**Issue by Ketcomp** [carbon-design-system/carbon-components-react#712]
## Clicking on Cancel shouldn't get rid of just the action bar but also de-select all selected rows.

Why this is a bug according to Anna Gonzales (from a conversation on #carbon-components on Slack)
>I think this is actually a bug Josh (because we missed this particular use-case).  The action bar itself shouldn’t be dismissible. The user is dismissing the whole action flow.
>
>The action bar only appears when items are checked therefor if the action bar is dismissed then the items should become unchecked.
>
>The user can’t take any action without the action bar and there is no way to bring it back (unless you select another item which maybe you don’t want to)

> Is this a feature request (new component, new icon), a bug, or a general issue?
This is a Bug

> Is this issue related to a specific component?
This is related to the DataTable -> TableBatchActions

> What did you expect to happen? What happened instead? What would you like to see changed?
The `Cancel` should de-selected selected rows - see GIF for an explanation.

> What version of the Carbon Design System are you using?
29

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Decided we don't need Batch Actions so no.

![awesomescreenshot-2018-03-14t18-59-52-553z](https://user-images.githubusercontent.com/9720857/37431066-2942cb1a-27a2-11e8-8d23-eb3efbef214b.gif)

**Comment by joshblack** [comment]
Thanks @Ketcomp for making this issue! Really appreciate it 🙌
