### ISSUE TITLE
Change ComboBox & DropdownV2 'initialSelectedItem' prop type to match DownShift

### ISSUE THREAD

**Issue by Yohanna** [carbon-design-system/carbon-components-react#718]
### Description
The `initialSelectedItem` prop in both `ComboBox` & `DropdownV2` has a type of `PropTypes.object`.

The prop is then passed to DownShift [defaultSelectedItem](https://github.com/paypal/downshift#defaultselecteditem) prop which has a type of `any`. The problem happens when we pass a string to `initialSelectedItem`, we get a console warning saying it expects an Object. However, the dropdown renders correctly since DownShift accepts `any` type.

The prop type needs to be changed to allow any type to match DownShift's prop.

#### Is this a feature request (new component, new icon), a bug, or a general issue?
A bug.

#### Is this issue related to a specific component?
Yes. `ComboBox` & `DropdownV2`

#### What did you expect to happen? What happened instead? What would you like to see changed?
Be able to pass a string without getting any PropTypes warnings like:

`Warning: Failed prop type: Invalid prop 'initialSelectedItem' of type 'string' supplied to 'ComboBox', expected 'object'`

#### What version of the Carbon Design System are you using?
v`5.31.0`

#### What offering/product do you work on? Any pressing ship or release dates we should be aware of?
A new QRadar App. Initial version released in early April.

**Comment by joshblack** [comment]
Hi @Yohanna! 👋 thanks so much for taking the time to make this issue 😄 

Could you provide some code examples that show the difference between the object-approach and the string approach? When reading this initially, it feels like a minor enhancement at the cost of having to handle additional surface area that the change in prop type exposes (like supporting booleans, for example).

While these may not be typical code paths for developers, it feels like constraining to the object type is a step forward to help eliminate the chance of ambiguity in the component API.

Would love to know your thoughts 😄
