### ISSUE TITLE
DatePickerInput calls 'onClick' prop even if it's not passed to the component

### ISSUE THREAD

**Issue by Yohanna** [carbon-design-system/carbon-components-react#720]
### Description

`DatePickerInput` component calls the `onClick` prop event if it was not passed in. This results in a `TypeError: _onClick is not a function` error in the console.

#### Is this a feature request (new component, new icon), a bug, or a general issue?
A bug.

#### Is this issue related to a specific component?
Yes. `DatePickerInput`

#### What did you expect to happen? What happened instead? What would you like to see changed?
`onClick` is not a required prop, it shouldn't be called if it wasn't passed to the component.

#### What version of the Carbon Design System are you using?
v`5.31.0`

#### What offering/product do you work on? Any pressing ship or release dates we should be aware of?
A new QRadar App. Initial version released in early April.

### Steps to reproduce the issue
https://codesandbox.io/s/k0wqqw8k27

### Additional information
Mari Johannessen looked into the issue on Slack and found a workaround by passing an empty `onClick`: `onClick={() => { }}`

**Comment by tw15egan** [comment]
Could we simply add a default prop?  `onClick: () => {}`?
