### ISSUE TITLE
IE11 Bug - Modal content overflow when max-height on parent is reached

### ISSUE THREAD

**Issue by Noodles006** [carbon-design-system/carbon-components-react#722]
Step to reproduce:

1. Open http://www.carbondesignsystem.com/components/modal/code
2. Narrow down the height of the window
3. Click a `Transactional Modal`
4. You will see part of the modal is overlaped 

![1](https://user-images.githubusercontent.com/8025633/37576957-f7737dcc-2b26-11e8-962b-5254f1d1d2da.png)

**Comment by joshblack** [comment]
Hi @Noodles006! 👋 Thanks so much for taking the time to make this issue. Going to move this over to `carbon-components` since that's where the styles are defined.

**Comment by joshblack** [comment]
Issue moved to [carbon-design-system/carbon-components #663](https://github.com/carbon-design-system/carbon-components/issues/663) via [**ZenHub**](https://www.zenhub.com/)
