### ISSUE TITLE
When will TypeScript be supported? 

### ISSUE THREAD

**Issue by ilovepumpkin** [carbon-design-system/carbon-components-react#727]
## Detailed description
I am going to use TypeScript with carbon-components-react, but I can not find the types files. I searched the old issues and found one closed discussion https://github.com/carbon-design-system/carbon-components-react/issues/580 and one pull request https://github.com/carbon-design-system/carbon-components-react/pull/581 . Does this mean this work is still ongoing? When will it be ready?

**Comment by ajdaniel** [comment]
You can create your own typings files for external libraries that don't already have them, and instruct your typescript compiler to evaluate them. This is a useful guide https://definitelytyped.org/guides/best-practices.html

**Comment by joshblack** [comment]
Hi @ilovepumpkin! 👋 Thanks so much for taking the time to make this issue 😄 

With respect to TypeScript bindings, I don't believe that we'll introduce it into the core development of React for a while. If there is more interest, we should build off of that discussion with @psachs21  in #580 and #581, like you mentioned.

One option here is to make another project in `carbon-design-system` just for the TS bindings if there is someone willing to be a maintainer on that project 😄

**Comment by ilovepumpkin** [comment]
@ajdaniel @joshblack Thank you guys for your replies! Let me see how much effort I need to make it work first. @joshblack probably I would like to be the maintainer for TypeScript binding project - will let you know,  :laughing:

**Comment by stram2020** [comment]
Hi,

Do we have react.SFC / react.statelesscomponent for carbon-components-react with TypeScript?

Thanks & Regards,
Ram S
