### ISSUE TITLE
Paginator: page size number overflow when it's 3 digits

### ISSUE THREAD

**Issue by nicoxxie** [carbon-design-system/carbon-components-react#732]
## Detailed description

![screen shot 2018-03-20 at 1 51 02 pm](https://user-images.githubusercontent.com/17915105/37676412-e15d1348-2c45-11e8-9d95-3afd268e4821.png)

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general issue?
bug

> Is this issue related to a specific component?
PaginatorV2

> What did you expect to happen? What happened instead? What would you like to see changed?
icon should flow to right

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
5.29.4

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
IBM Cloud

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by joshblack** [comment]
Hi @nicoxxie! 👋 Thanks so much for taking the time to make this issue 😄 

Definitely agree that this is a bug, we'll try to get it added to our sprints but will also accept any PRs to fix this in the meantime!

**Comment by joshblack** [comment]
Closed by #683
