### ISSUE TITLE
ComboBox bug, manual text entry is overwritten when item was previously selected

### ISSUE THREAD

**Issue by David-Yuen** [carbon-design-system/carbon-components-react#734]
## Detailed description

> Describe in detail the issue you're having.
<ComboBox
 items={<list of defined items>}
 itemToString={item => (item ? item.value : this.state.myStateVariable)}
 onChange={this.selectOption}
 onInputChange={this.inputOption}
 placeholder="placeHolderText"
/>

where:
onInputChange sets the typed value to myStateVariable
onChange will take the selectedItem.value and set it to myStateVariable

The bug I found is:
If you select an item from the list (say "Option 1") and you backspace couple of chars and rewrite part of it (say, you want to customize/override and use "Option 5" which does not exist in the list). then you click away from the box or go to a different field, it will revert back to the previously selected item (goes back to "Option 1").

If the ComboBox was NOT previously selected an item, and you type in some custom text and then go to next field, the text remains properly. So this works fine.

So it seems the problem is.. it saves the item when selected (unless you clear with the "x" button), and even though manual input is entered, it thinks it is invalid and reverts back to the previous item value

> Is this a feature request (new component, new icon), a bug, or a general issue?
A bug

> Is this issue related to a specific component?
ComboBox

> What did you expect to happen? What happened instead? What would you like to see changed?
Manual text entry is expected to be the same if an item was or was not previously selected, it should accept the manual text entry without reverting back to previous item

> What browser are you working in?
Google Chrome

> What version of the Carbon Design System are you using?
carbon-components v8.16.8
carbon-components-react v5.31.1
carbon-icons 6.3.2

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
DataFusion

## Steps to reproduce the issue

1. Define ComboBox, such as:
`
let items=[
  {
    id: "option-1",
    text: "Option 1"
  },
  {
    id: "option-2",
    text: "Option 2"
  }
];
<ComboBox
  items={items}
  itemToString={item => (item ? item.text : this.state.myStateVariable)}
  onChange={this.selectOption}
  onInputChange={this.inputOption}
  placeHolder="PlaceHolderText"
/>
`
2) Define onChange= and onInputChange= event handlers:
selectOption() is to set the text value directly from one of the pre-defined item options
inputOption() is basically setting the text to a new entry (whatever the user wants it to be)
`
selectOption(event) {
  this.setState({
    myStateVariable: event.selectedItem.text
  });
}

inputOption(event) {
  this.setState({
    myStateVariable: event
  });
}

`

3) Run the code.

4) Scenario 1: 
- On the empty ComboBox, start typing something like "Option 5". Since Option 5 is not a pre-defined item, no actual item is selected from drop down and becomes a new entry.
- Click away from the ComboBox (or move to a different input field)
-> The Text will remain "Option 5" (which is set in myStateVariable)

5) Scenario 2: 
- On the empty ComboBox, first select an item from the list, such as "Option 1". Since Option 1 exists as a predefined item, it uses that item (and saves/caches it)
- Start overwritting the existing item text (Don't click the "x" to clear existing text), such as backspace and type in something new like "Option 5", or add to it so it becomes like "Option 15"
- Click away from the ComboBox (or move to next input field)
-> The Text will revert back to the previous item

Bug: in scenario 2, it would be expected to remain as the new/custom text instead. It doesn't make sense for a user to clear/backspace-all and retype just to get a new entry value

**Comment by joshblack** [comment]
Hi @David-Yuen! 👋 Thanks so much for taking the time to make this issue 😄 

One thing that would help out a ton here is if you could provide a sample gif that demonstrates the issue that you're highlighting. On our end, we'll try to follow along with your steps to reproduce as well to get the bottom of this.

**Comment by David-Yuen** [comment]
What tool do you use to capture a gif?

Just to add, i switched from ComboBox and tried Downshift.. realizing Downshift does the same thing. And also i remember you (Josh) mentioned to me that Downshift was being used in ComboBox? so maybe that's the root cause?

Currently switched again to another Component, React-Autocomplete and havn't had this issue

**Comment by joshblack** [comment]
Sounds good! Going to close this, then. Glad to hear you found something that worked!
