### ISSUE TITLE
Remove Hardcoded id in TableToolbarSearch

### ISSUE THREAD

**Issue by bellsworth13** [carbon-design-system/carbon-components-react#735]
## Detailed description

This is a bug in the component itself. Having the id hardcoded is causing 'non-unique id' errors.
This issue appears to have been fixed in the Search component but not in the TableToolbarSearch (for reference) 

## Additional information
<img width="483" alt="screen shot 2018-03-20 at 7 55 27 pm" src="https://user-images.githubusercontent.com/17937450/37690580-da1ab1ec-2c79-11e8-823c-1a5877dc1620.png">

**Comment by joshblack** [comment]
Hi @bellsworth13! 👋 Thanks so much for taking the time to make this issue 😄 

Definitely agreed that `id` should not be hard coded here. We will try and get this added to our sprints to fix, but will gladly accept any PRs in the meantime that help to fix this as well!
