### ISSUE TITLE
The Pagination with known total number of items control is too strict when validating the page number input

### ISSUE THREAD

**Issue by zgrossbart** [carbon-design-system/carbon-components-react#736]
1. Go to the pagination with known total number of items here:

http://react.carbondesignsystem.com/?selectedKind=Pagination&selectedStory=with%20known%20total%20number%20of%20items&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

2. Click on the input control which indicates the current page.  It will say 1 when you start.
3. Try to go to page four.

You can't press backspace and delete the 1 because that would make the current page be blank for a moment.  You can't type 4 and then delete the 1 because that would take you to either page 14 or 41 and there are only 11 pages.  The only thing you can do is highlight the 1 and then press 4 which will set the page number to 4 with just one change event.

It would be great if you could delete the 1 and then type 4.  It would be even better if there was a slight delay on this field.  Changing this field will likely cause a request back to the server to load the data for that page.  If you have 500 pages and are trying to go to page 349 you don't want to have to load the data for page 3, page 34, and then page 349.  If this input field had a 0.25 second delay before it took the input that would provide a much better user experience.

**Comment by ryshah** [comment]
Looking in to this
