### ISSUE TITLE
DataTable table row cells should indicate header key

### ISSUE THREAD

**Issue by ajdaniel** [carbon-design-system/carbon-components-react#737]
## Detailed description

In the data table, when rendering the cell for each row of the data, the following object is provided for cell information:

```json
{
  "id":"[cell_value]:[cell_header_key]",
  "value":"[cell_value]",
  "isEditable":false,
  "isEditing":false,
  "isValid":true,
  "errors":null
}
```

If I want to differentiate the cell (perhaps a certain column has a different style, perhaps it's clickable) then to determine which column it's in, I need to know the header key for that cell. That information is in the object, just stringified as a token in the cell.id. To reduce processing, providing that value as an item in the object will help identify the column for that row.

> Is this a feature request (new component, new icon), a bug, or a general issue?

feature request

> Is this issue related to a specific component?

DataTable

> What version of the Carbon Design System are you using?

5.32.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Watson Assistant

**Comment by joshblack** [comment]
Hi @ajdaniel! 👋 Thanks so much for taking the time to make this feature request 😄 

I really like this idea, and I think it goes well with where I think the `cell` data structure is heading. We could definitely update the cell structure to be something like:

```js
{
  id: string,
  value: any,
  state: {
    isEditable: boolean,
    isEditing: boolean,
    isValid: boolean,
    errors: Array<CellError>,
  },
  info: {
    header: string,
  },
}
```

**Comment by ajdaniel** [comment]
@joshblack yeah that looks perfect! Are there any current changes happening on the cell data structure?

**Comment by joshblack** [comment]
@ajdaniel unfortunately there isn't any active development in this area, but we would gladly accept PRs that introduce this structure change! 😄
