### ISSUE TITLE
ComposedModal does not close when open

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-components-react#738]
@bellsworth13 reported an issue in CloudFoundry where the ComposedModal doesn't close when expected. This issue is to:

- Properly identify the root underlying issue causing the modal not to close
- Fix the issue

**Comment by ahsannaveed007** [comment]
Hi @joshblack - I just made this sandbox in regards to this issue - not sure if this solves the problem 🤔 

https://codesandbox.io/s/r41y2k16qq
