### ISSUE TITLE
Modal component does not show red line on top with type `danger`

### ISSUE THREAD

**Issue by anirudhaBapat** [carbon-design-system/carbon-components-react#739]
## Detailed description

> Tried with a carbon-component storybook, cannot get a red line there too.

> It's a bug.

> Modal component

> What did you expect to happen? What happened instead? What would you like to see changed?

It should have shown a red border at the top when I specified `danger` in the `Modal` component. 

> What browser are you working in?

Chrome, FF

> What version of the Carbon Design System are you using?
`carbon-components`: `8.15.3`,
`carbon-components-react`: `5.23.0`,

* Screenshots or code
<img width="1356" alt="screen shot 2018-03-21 at 1 25 16 pm" src="https://user-images.githubusercontent.com/23107360/37737691-d0eb0e94-2d11-11e8-9d89-af1b77f3e12c.png">

**Comment by joshblack** [comment]
Hi there @anirudhaBapat! 👋 

This was included in v5.27.0 😄 https://github.com/carbon-design-system/carbon-components-react/releases/tag/v5.27.0

Hope that helps!

**Comment by anirudhaBapat** [comment]
Hey @joshblack, I tried updating the version and I saw changes to the Modal with `danger` (added danger button) but did not see the border-top having a red color.

Also is there any chance when these changes get reflected into carbon storybook?

**Comment by anirudhaBapat** [comment]
<img width="1274" alt="screen shot 2018-03-22 at 11 52 33 am" src="https://user-images.githubusercontent.com/23107360/37791879-8941d90e-2dc7-11e8-9f6a-55fc0a56e245.png">

as you can see in the image only `border-top-color: #e62325;` is mentioned. should be `border-top: 4px solid #e62325` instead.

**Comment by joshblack** [comment]
Is your `carbon-components` dependency up-to-date?

**Comment by joshblack** [comment]
Should look like this: http://carbondesignsystem.com/components/modal/code

**Comment by tw15egan** [comment]
@anirudhaBapat Are you using the Watson theme? The Watson theme removes the border top https://github.com/carbon-design-system/carbon-themes/blob/master/themes/watson.scss#L59

**Comment by anirudhaBapat** [comment]
@joshblack Yes, I did update dependencies. Still investigating. Anyway per @tw15egan Watson-theme removed the border top, so I can just use a normal Modal instead. Thanks for your help.
