### ISSUE TITLE
Data Table does not render row data entered through this.props

### ISSUE THREAD

**Issue by davekaj** [carbon-design-system/carbon-components-react#740]
The datatable component will not render the data when it is passed through props, but is rendering when I pass the data directly from a json from another file. Please note the data passed directly through with a  json file is passed through at the very start upon rendering of the whole page, while the data passed through props is through user generated input, so happens during app usage. 

Also not no error pops up in console. 

After digging through source code, we think it may have something to do with this code block below:

https://github.com/carbon-design-system/carbon-components-react/blob/38b8f56daaed101a6cef69662e6d7b941220013a/src/components/DataTable/DataTable.js#L109-L126

It looks like the table will only render newly imported rows when you are sorting the header keys or sorting the direction. However in our case, we are injecting new rows into the rows prop of <DataTable>, see code below:

          <DataTable
            rows={this.props.investors} //why wont this render???
            headers={TableHeaders}
            filterRows={(rows) => {
              console.log('rows adam', rows)
              return rows.map((row) => row.id)
            }}
            render={({
              rows,
              headers,
              getHeaderProps,
              getSelectionProps,
              getBatchActionProps,
              onInputChange,
              // selectedRows,
            }) => {
              console.log('inside2', rows, headers)

              return (
                <TableContainer title='DataTable with batch actions'>
                  <TableToolbar>
                    {/* make sure to apply getBatchActionProps so that the bar renders */}
                    <TableBatchActions {...getBatchActionProps()}>
                      {/* inside of you batch actinos, you can include selectedRows */}
                      <TableBatchAction >
                        Remove Investor
                      </TableBatchAction>
                      <TableBatchAction >
                        Modify Restriction Dates
                      </TableBatchAction>
                    </TableBatchActions>
                    <TableToolbarSearch onChange={onInputChange} />
                    <TableToolbarContent>
                      <TableToolbarAction
                        iconName='download'
                        iconDescription='Download'
                      // onClick={action('TableToolbarAction - Download')}
                      />
                      <TableToolbarAction
                        iconName='edit'
                        iconDescription='Edit'
                      // onClick={action('TableToolbarAction - Edit')}
                      />
                      <TableToolbarAction
                        iconName='settings'
                        iconDescription='Settings'
                      // onClick={action('TableToolbarAction - Settings')}
                      />
                      <ModalWrapper
                        // modalProps={{ onBlur: { onBlur() }, onClick: { onClick() }, onFocus: { onFocus() }, …}}
                        id='transactional-modal'
                        buttonTriggerText='Add New'
                        // modalLabel='Add New Investor'
                        modalHeading='Add New Investor'
                        onSubmit={this.handleInvestorSubmit}
                        shouldCloseAfterSubmit
                      >
                        <p className='bx--modal-content__text'>
                          Please enter the information below to add a single investor.
                        </p>
                        <br />
                        <InvestorForm onSubmit={this.handleInvestorSubmit} />
                      </ModalWrapper>
                    </TableToolbarContent>
                  </TableToolbar>
                  <Table>
                    <TableHead>
                      <TableRow>
                        <TableSelectAll {...getSelectionProps()} />
                        {headers.map((header) => (
                          <TableHeader {...getHeaderProps({ header })}>
                            {header.header}
                          </TableHeader>
                        ))}
                      </TableRow>
                    </TableHead>
                    <TableBody>
                      {rows.map((row) => (
                        <TableRow key={row.id}>
                          <TableSelectRow {...getSelectionProps({ row })} />
                          {row.cells.map((cell) => (
                            <TableCell key={cell.id}>{cell.value}</TableCell>
                          ))}
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </TableContainer>
              )
            }}
          />

So we think it may be that an injection of new items does not trigger updating of the internal state of the component.

Please also note I am using the pagination component to get the length of the this.props.investors, and it is correctly reading it and rendering it, so I am definitely not passing through an empty rows prop.
It really seems like something is happening through the internal sorting/filtering of the rows prop, because this.props.investor has real data and then when it renders inside datatable it is just picking up a blank array. 

Any help or direction is greatly appreciated! 

> Is this a feature request (new component, new icon), a bug, or a general issue?

appears to be a bug

> What browser are you working in?

chrome

> What version of the Carbon Design System are you using?

5.31.1

**Comment by joshblack** [comment]
Hi @davekaj! 👋 Thanks so much for taking the time to make this issue 😄 

This definitely seems like a valid bug report, we definitely should be adding additional rows to our internal data structure in the `componentWillRecieveProps` hook. Will try to get this added to our sprints, but will definitely accept any PRs in the meantime that fix this!

**Comment by liusiran** [comment]
We also find a similar issue in latest version. After passing a updated rows to Datatable, the table doesn't update , just remain origin rows. What we implement in our code is:

render() {
    if (this.state.rows && this.state.headers) {
      this.content = this.renderTable(this.state.rows, this.state.headers);
    } else {
      this.content = <div>No Data</div>;
    }
    return (
        {this.content}
    );
 }

 renderTable(initialRows, initialHeaders) {
    return (
        <DataTable
          rows={initialRows}
          headers={initialHeaders}
          render={({ rows, headers, getHeaderProps, getRowProps }) => (
               <TableContainer>
                    .....................
               </TableContainer>
          )}
        </DataTable>
      )

We want to re-render DataTable through updating state of rows and headers of parent Component. 
It works fine in Version 5.32.0, but not work in latest version. 
I am not sure if it is as the same reason as above comment. It seems similar.

**Comment by Yohanna** [comment]
We're also facing a similar problem where our `DataTable` stopped showing data. We traced the issue to the changes in release [5.33.0](https://github.com/carbon-design-system/carbon-components-react/releases/tag/v5.33.0). Reverting to v`5.32.0` fixes the problem.

**Comment by ajdaniel** [comment]
I am hitting this bug too, and it is a breaking problem. When I update the rows property in the DataTable, it does not update the internal state. This needs to be addressed for DataTable to be usable. I will look at implementing a PR right away

**Comment by joshblack** [comment]
@ajdaniel was taking a look at this this morning as well, during some down time. Was planning on doing a simple PR with a fix like:

```js
  componentWillReceiveProps(nextProps) {
    const nextState = getDerivedStateFromProps(nextProps, this.state);

    // Preserve the sorted order by re-sorting the data
    if (
      (nextState && nextState.sortHeaderKey !== this.state.sortHeaderKey) ||
      nextState.sortDirection !== this.state.sortDirection
    ) {
      this.setState({
        ...nextState,
        ...getCurrentSortState(this.props, this.state, {
          key: this.state.sortHeaderKey,
        }),
      });
      return;
    }

    const rowIds = this.state.rowIds.sort();
    const nextRowIds = nextState.rowIds.sort();

    if (!isEqual(rowIds, nextRowIds)) {
      this.setState(nextState);
    }
  }
```

**Comment by ajdaniel** [comment]
Does this cover all cases of row changes? E.g. add, remove, change? I'm finding that the problem is deep. In `sorting.js` the `getSortedState` (called by `getCurrentSortState` in the `componentWillReceiveProps`) ignores the new `byId` props, so the array of IDs gets reverted to the old state.

**Comment by joshblack** [comment]
Relevant PR: https://github.com/carbon-design-system/carbon-components-react/pull/754

Tried to tackle this in-between some of the stuff we have lined up this sprint, so feel free to add any suggestions or offer alternative PRs that better tackle this problem 😄 

@ajdaniel in this case, the heuristic I was using is if the ids have changed, that means some kind of mutation occurred for rows so we should use the new state that we have derived from the incoming props.

For the sorting case, I'm unsure. This was a contribution by an external contributor so will need to revisit this to make sure the logic is sound. In theory, it seems like it should work since it's calculating the new sort state but there easily could be a case that we have missed.

**Comment by davekaj** [comment]
For what it's worth, I was originally running 5.31.1, and then I upgraded to 5.32.0 because other people said it was working, and now it works

**Comment by ajdaniel** [comment]
@joshblack if IDs in the row data have remained the same, that's not a perfect indication that the row data has remained the same, as the value of the cells in the rows could have changed too.

I feel like data change and sorting is failing some edge cases and needs a real hard look to ensure it's thoroughly working, and needs tests for a lot of cases. Once we get this issue sorted quickly, I might take a stab.

**Comment by joshblack** [comment]
> if IDs in the row data have remained the same, that's not a perfect indication that the row data has remained the same

Definitely a fair point. I think to be on the safe side we could just compare the old rows and new rows directly, would be worried about the perf cost but am more worried about correctness at this point, haha. If that equality check fails, then we'll most likely need to re-run through all the current state mutations like sorting/filtering/selection.
