### ISSUE TITLE
Visual glitch in Data Table component under some (unknown) conditions.

### ISSUE THREAD

**Issue by mlinnem** [carbon-design-system/carbon-components-react#758]
## Detailed description

> Describe in detail the issue you're having.

There is a graphical glitch in a specific instance of the data table as it is currently being used in the Container Service Image Report Detail" page of IBM Cloud.

In the collapsed state, it appears as a the bottom of the table row being elevated by one pixel for the first 30 or so horizontal pixels of the row.

<img width="119" alt="screen shot 2018-03-28 at 10 51 35 am" src="https://user-images.githubusercontent.com/1547834/38042922-4636de08-327b-11e8-8bed-a639b4d7042e.png">

In the expanded state, it appears as a white line mysteriously floating in the row.

<img width="177" alt="screen shot 2018-03-28 at 10 51 49 am" src="https://user-images.githubusercontent.com/1547834/38042945-5658a690-327b-11e8-85e1-cb17a3f51156.png">

The same glitch does not appear on the a very similar table on the same page.

<img width="441" alt="screen shot 2018-03-28 at 11 30 08 am" src="https://user-images.githubusercontent.com/1547834/38043013-799375fe-327b-11e8-9a82-c9aee6e44337.png">

> Is this a feature request (new component, new icon), a bug, or a general issue?

A bug.

> Is this issue related to a specific component?

Related to data table.
> What browser are you working in?

Version 65.0.3325.181 (Official Build) (64-bit)

Does not occur in Safari (Version 11.0.3 (13604.5.6))

> What version of the Carbon Design System are you using?

Unsure.

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

In prod right now of Container Service.

**Comment by joshblack** [comment]
Hey @mlinnem! 👋 Thanks so much for taking the time to make this issue 😄 

Is this related to the styles of this component? If so, I can move it over to `carbon-components` so it gets addressed there 🙂

**Comment by mlinnem** [comment]
@joshblack Yep, thank you for looking at it! :)

It may be. I see now that the glitch disappears when I remove the css rule "-webkit-box-sizing: border box". I'm just a designer and not a web science man, but that would seem to mean the cause is styling? A bunch of other stuff goes wrong when I disable that selector... (e.g. expand/collapse arrows on tables get bigger).

**Comment by joshblack** [comment]
Thanks for diving into this! Definitely seems like a style issue so will move it over there. Thank you again for your time and effort in identifying this bug, we really appreciate it! 🎉

**Comment by joshblack** [comment]
Issue moved to [carbon-design-system/carbon-components #678](https://github.com/carbon-design-system/carbon-components/issues/678) via [**ZenHub**](https://www.zenhub.com/)
