### ISSUE TITLE
Unable to get the value of NumberInput using Up/Down arrows

### ISSUE THREAD

**Issue by Yohanna** [carbon-design-system/carbon-components-react#759]
## Detailed description

I can't get the value of the `NumberInput` component when I use Up or Down arrows.

> Is this a feature request (new component, new icon), a bug, or a general issue?

A bug

> Is this issue related to a specific component?

`NumberInput`

> What did you expect to happen? What happened instead? What would you like to see changed?

I'd like either `onClick` or `onChange` to get the new value when Up or Down arrow is pressed.

> What browser are you working in?

Chrome v`65.0.3325.181`

> What version of the Carbon Design System are you using?

v`5.32.0`

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

QRadar App,  Initial version released in April.

## Steps to reproduce the issue

[Codesandbox](https://codesandbox.io/s/6v5mlqm1jz)

1. Input any number manually and notice that the new value is printed correctly to the console
2. Use Up or Down arrow to change the value
3. `e.target.value` has a `null` value.

**Comment by Yohanna** [comment]
Looking at PR #597, specifically [this comment](https://github.com/carbon-design-system/carbon-components-react/pull/597#issuecomment-365670319), looks like we now have to use `e.imaginaryTarget.value` to get the value. It has the value for both scenarios: when using the arrows & when entering the value manually.

I can work on a PR to mention this change in the docs.

**Comment by asudoh** [comment]
💯 @Yohanna You are right for both - Thank you for jumping in! 🙇
