### ISSUE TITLE
Bug: Server side rendering is broken after adding flatpickr

### ISSUE THREAD

**Issue by germanattanasio** [carbon-design-system/carbon-components-react#76]
Hi @marijohannessen, When you added `flatpickr` here: https://github.com/carbon-design-system/carbon-components-react/commit/6bc3176868abed0e509d30a4bf6f899aaf1a2626 you broke server-side rendering :(

Users trying to use server-side rendering should use `v3.2.0`

See https://github.com/coderhaoxin/react-flatpickr/issues/9

**Comment by chrisdhanaraj** [comment]
Are you importing the every component set on server render? I'm a little confused on why one component would break it (note: I pretty much never do SSR so little out of my element here)

**Comment by germanattanasio** [comment]
I just traced an error reported by one of the developers in my team. I'm going to look at the problem next week. For now, we are using 3.2.0 and it works well.

**Comment by chrisdhanaraj** [comment]
Kk sounds good - we don't use the React wrapper for flatpicker; my gut feeling says we just need to not instantiate an instance of

**Comment by alisonemiller** [comment]
I am hitting the same problem - using `3.2.0` as a workaround for now too.

**Comment by germanattanasio** [comment]
We are using `3.2.0` for now. I think that they are including all the component even that you only load them one by one.

**Comment by kemerson16** [comment]
@chrisdhanaraj Do you have any insight as to when this issue might be resolved as it is preventing us from moving to a newer version for additional fixes. Thanks in advance!

**Comment by kemerson16** [comment]
Per chat with @nfriedly, he is sending a PR to https://github.com/coderhaoxin/flatpickr to resolve the issue at it's source. Once resolved the request will be for Carbon to upgrade to the latest release of flatpickr.

**Comment by nfriedly** [comment]
Actually, I provided the wrong link - that one is a fork, the source is at https://github.com/chmln/flatpickr

**Comment by chrisdhanaraj** [comment]
Bluemix [toolchain](https://console-regional.ng.bluemix.net/devops/toolchains/6b8b7163-1ec8-4616-82fa-aa467a17af03 "storybook-toolchain-v2"): [Delivery Pipeline](https://console-regional.ng.bluemix.net/devops/pipelines/b84aaac8-8484-4a1e-902a-ebb526eb7998 "storybook-toolchain-v2") deployed [carbon-components-react](https://github.com/carbon-design-system/carbon-components-react/releases/tag/deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20170810-155531 "deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20170810-155531") to [Bluemix Design System](https://console.bluemix.net/apps/597e3f6e-c208-4e71-97d0-0e4982545e05?env_id=ibm:yp:us-south "ibm:yp:us-south:chrisdhanaraj_org:Bluemix Design System"), including commit b9e69db90d1c11cd0582b72bc8869eb373ca50f7
