### ISSUE TITLE
 ModalWrapper does not close after submit when using shouldCloseAfterSubmit

### ISSUE THREAD

**Issue by davekaj** [carbon-design-system/carbon-components-react#774]
## Detailed description

ModalWrapper does not close after submit. i am using the prop shouldCloseAfterSubmit. handleSubmit is running, because my function this.onHandleMultiSubmit is getting triggered. Looks like in the source code it is just a simple boolean change of state to close it:

```
  handleClose = () => {
    this.setState({
      isOpen: false,
    });
  };

  handleOnRequestSubmit = () => {
    const { handleSubmit, shouldCloseAfterSubmit } = this.props;

    if (handleSubmit()) {
      if (shouldCloseAfterSubmit) {
        this.handleClose();
      }
    }
  };
```

 Any ideas why this would not be working? Or am i using ModalWrapper wrong? Or is there an easy hack which would let me close this that someone else has used? Anything will do :)

Version:     "carbon-components-react": "5.32.0",
Browser: Chrome

I have posted my code for reference below.

## Code

              <ModalWrapper
                // modalProps={{ onBlur: { onBlur() }, onClick: { onClick() }, onFocus: { onFocus() }, …}}
                id='input-modal'
                buttonTriggerText='Import Whitelist'
                modalLabel=''
                modalHeading='Import Whitelist'
                handleSubmit={this.onHandleMultiSubmit}
                primaryButtonText='Send To Blockchain'
                shouldCloseAfterSubmit
              >
                <div>
                  Add multiple addresses to the whitelist by uploading a comma seperated CSV file. The format should be as follows:
                  <br /><br />
                  <ul>
                    <li>Column 1 - Ethereum Address</li>
                    <li>Column 2 - Sell Restriction (mm/dd/yyyy)</li>
                    <li>Column 2 - Buy Restriction (mm/dd/yyyy)</li>
                  </ul>
                </div>
                <FileUploader
                  buttonLabel='IMPORT WHITELIST'
                  filenameStatus='edit'
                  accept={[".csv"]}
                  onChange={this.props.handleUpload}
                  multiple
                />

                {this.props.modalShowing ?
                  <div>
                    <p className='bx--modal-content__text'>
                      <strong>Below is the data you will be sending to the blockchain, please confirm it is correct, and then click the Send button to continue.</strong>
                    </p>
                    <br />
                    {this.props.addresses.map((user, i) => (
                      <div key={uuidv4()}>
                        <div>Address: {this.props.addresses[i]}</div>
                        <div>Sell Expiry Time: {this.props.sell[i]}</div>
                        <div>Buy Expiry Time: {this.props.buy[i]}</div>
                        <br />
                      </div>
                    ))}
                  </div>
                  : null}
              </ModalWrapper>

**Comment by joshblack** [comment]
Hi @davekaj! 👋 Thanks so much for taking the time to make this issue 😄 

Most likely, this is due to `this.onHandleMultiSubmit` not returning a truth-y value such that this block would get triggered:

```js
    if (handleSubmit()) {
      if (shouldCloseAfterSubmit) {
        this.handleClose();
      }
    }
```

Let me know if this isn't the case and I can try and help debug further!

**Comment by davekaj** [comment]
Hi @joshblack ,

You were right, all I had to do was take this.onHandleMultiSubmit, and get it to return true. Previously it was returning nothing. 

So this components works properly, and I will close the issue. Thanks!
