### ISSUE TITLE
Slider: Requires more props than are documented

### ISSUE THREAD

**Issue by i-a-n** [carbon-design-system/carbon-components-react#775]
## Detailed description
The Slider component requires both a `step` property (integer) and an `onChange` property (function), otherwise it simply doesn't work with mouse events. This is neither documented anywhere nor are those props marked as `.isRequired` in the component.

I think it would be helpful to either use reasonable defaults for those two, or to mark them as required in the code and the documentation, to keep other devs from wasting time debugging why their fresh-out-of-the-box Slider doesn't work.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

5.34.0

## Steps to reproduce the issue
Check the Code Sandbox below; removing either `step` or `onChange` breaks slider dragging:
https://codesandbox.io/s/q9jvp9vj9

## Additional information
Happy to help resolve this with a PR if you guys don't have the time!

**Comment by joshblack** [comment]
Hi @i-a-n! 👋 Thanks so much for taking the time to make this issue 😄 

Definitely agree that these should be required and could have appropriate defaultProps applied. We would love it if you could take this on, but if not we can definitely try and add it to one of our sprints. Just let us know!

**Comment by i-a-n** [comment]
Sure thing @joshblack, I'll go through the contributing guide and try to open a PR within a week or so.
