### ISSUE TITLE
Pagination component spacing discrepancy (Carbon Vanilla vs. React)

### ISSUE THREAD

**Issue by mlinnem** [carbon-design-system/carbon-components-react#778]
> Describe in detail the issue you're having.

Seems like the React pagination component has a bit more space in it than the Vanilla Carbon component.
<img width="983" alt="screen shot 2018-04-03 at 11 02 45 am" src="https://user-images.githubusercontent.com/1547834/38261069-d128953a-372e-11e8-9da3-60d1d91cfbc8.png">

> Is this a feature request (new component, new icon), a bug, or a general issue?

Visual bug.

> Is this issue related to a specific component?

Yep. Pagination.

> What browser are you working in?

Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by joshblack** [comment]
Hi @mlinnem! 👋 Thanks for another spec review of Data Table, we really appreciate it 🙏 

Will flag this as a bug and try to figure out what's going on. Also will definitely accept any PRs that help to fix this!

**Comment by mlinnem** [comment]
Praise to the Carbon gods. They have answered the call with great glory.
