### ISSUE TITLE
Pagination - react vs. vanilla one pixel discrepancy

### ISSUE THREAD

**Issue by mlinnem** [carbon-design-system/carbon-components-react#779]
A dastardly crime is afoot. 

<img width="823" alt="screen shot 2018-04-03 at 12 27 55 pm" src="https://user-images.githubusercontent.com/1547834/38265207-c8df1262-373a-11e8-88ee-32092ca755ed.png">

FWIW, I'd actually prefer that these components were centered with respect to the overall pagination component, rather than bottom-aligned with the text. But, if we're to assume that the Vanilla Carbon component is the gold standard, then it seems the react component has the pagination widgets a pixel too high.

**Comment by joshblack** [comment]
Hi @mlinnem! 👋 Thanks so much for taking the time to make this issue 😄 

Definitely will try and investigate to see why we're off by that one pixel!

**Comment by joshblack** [comment]
Should be resolved in: https://github.com/carbon-design-system/carbon-components-react/pull/844 let me know if this is not the case!
