### ISSUE TITLE
Bug: TextArea label position is changed once I enlarge the textarea 

### ISSUE THREAD

**Issue by ilovepumpkin** [carbon-design-system/carbon-components-react#78]
Before

![image](https://user-images.githubusercontent.com/11310645/27848044-a6464a00-6174-11e7-9121-9cddd5bca0ab.png)

After 
![image](https://user-images.githubusercontent.com/11310645/27848046-ad64e63e-6174-11e7-96d5-1bd19cde112d.png)

**Comment by hellobrian** [comment]
Is this still an issue? 
Couldn't duplicate this bug, can you show me how exactly you produced this bug in this codesandbox? 

[![Edit TextArea](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mZpqQ3B7O)

I can reopen when we see how you were able to make the TextArea break.

**Comment by ilovepumpkin** [comment]
@hellobrian , I have reproduced this bug on CodeSandbox, please check it out. 
[![Edit TextArea](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/Wn1Qk9LJg?view=preview)
I think it might be related the Modal component and it needs enough space to show - so you had better to switch to "Preview view" to reproduce this issue.

**Comment by hellobrian** [comment]
![image](https://user-images.githubusercontent.com/4185382/28926784-74c87b30-782e-11e7-970e-a7b367784521.png)

This is what I'm seeing, what does yours look like?

**Comment by ilovepumpkin** [comment]
@hellobrian , you need to enlarge the text area by the icon at the right corner. 

![image](https://user-images.githubusercontent.com/11310645/29009924-0ee375fc-7b5a-11e7-829f-64fd30f7387c.png)

**Comment by hellobrian** [comment]
Ah okay, thanks for pointing that out. 
This can get fixed if we change `label.bx--label` to use `display: block` instead of `inline-block`, but we need to be able to give you and other devs a way to override the style yourselves so that we don't break anyone that may be relying on the label being `inline-block`.

**Comment by ilovepumpkin** [comment]
@hellobrian , thanks!

**Comment by marijohannessen** [comment]
This is resolved
