### ISSUE TITLE
TableHeader: sort caret hover tooltip not showing in FF and IE

### ISSUE THREAD

**Issue by nicoxxie** [carbon-design-system/carbon-components-react#781]
## Detailed description
For screenshots see https://github.ibm.com/IAM/access-management/issues/5014

> Describe in detail the issue you're having.
Tooltip not showing for on hover the caret but it works in Chrome

> Is this a feature request (new component, new icon), a bug, or a general issue?
Bug

> Is this issue related to a specific component?
5.29.4

> What did you expect to happen? What happened instead? What would you like to see changed?
Same behavior across all browser.

> What browser are you working in?
IE11, FF

> What version of the Carbon Design System are you using?
5.29.4

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
IBM cloud

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by joshblack** [comment]
Hi @nicoxxie! 👋 Thanks for taking the time to make this issue 😄 

Looking at the screenshots, this seems like a browser quirk more than anything else. Ultimately all browsers but firefox will render the `aria-label` as a tooltip. Is this currently breaking some kind of audit for IAM?

**Comment by nicoxxie** [comment]
Hi @joshblack , this is an item opened by GVT, I will go and explain the situation.  Will close issue once they agree.
