### ISSUE TITLE
DataTable should re-render when cell content updates

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-components-react#784]
In #740 we made it so that rows would re-render when one was added/deleted. We should also support the case of cell content updates triggering a state change as well for the rows. This issue is for adding a check to verify that cell content has been updated (or not) and updating state accordingly.

**Comment by asfordmatt** [comment]
Hi @joshblack we're stuck on an old release until this is fixed :( so wondering if I can help at all? In componentWillReceiveProps() couldn't we just compare the entire rows, e.g.:

    if (!isEqual(this.props.rows, nextProps.rows)) {
      this.setState(state => getDerivedStateFromProps(nextProps, state));
      return;
    }

**Comment by joshblack** [comment]
Definitely could @asfordmatt! Would be the fastest solution in the interim, although would be worried about deep equality checks given that this component will want to support pagination in the future. Might be a premature optimization though 🙂

**Comment by asfordmatt** [comment]
@joshblack please see the referenced PR. I've updated the storybook to add a button that increases the port number in the sample row data. I've also added a test for the same.
Do you think it's worth keeping the earlier test that just compares the row IDs? Or just leave it to the full compare to catch everything?
