### ISSUE TITLE
ToolTipSimple with no icon not displaying

### ISSUE THREAD

**Issue by johannott** [carbon-design-system/carbon-components-react#786]
## [Title]: 

ToolTipSimple with no icon not displaying

## Detailed description

The TooltipSimple without the icon does not display in the storybook. It looks like the before/after pseudo classes are not getting added on hover when there is no icon.

[TooltipSimple](http://react.carbondesignsystem.com/?selectedKind=TooltipSimple&selectedStory=no%20icon&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

**Comment by joshblack** [comment]
Hi @johannott! 👋 Thanks so much for taking the time to make this issue 😄

Definitely agreed that this is a regression. Will label it as a bug and try and get it added to our sprints. Will also accept any PRs to fix it!
