### ISSUE TITLE
Overflow menu inside Datatable having issues

### ISSUE THREAD

**Issue by davidmenendez** [carbon-design-system/carbon-components-react#792]
## Detailed description

> Describe in detail the issue you're having.

After updating to carbon 5.41.1 I saw strange behavior of the OverflowMenu inside the data table

![overflow-bug](https://user-images.githubusercontent.com/6370760/38505868-debe37d2-3bdd-11e8-84f8-ee404b2279aa.gif)

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug

> Is this issue related to a specific component?

OverflowMenu

> What did you expect to happen? What happened instead? What would you like to see changed?

I expected the menu to open normally and not jump the page or not show up at all

> What browser are you working in?

Firefox

> What version of the Carbon Design System are you using?

Currently on 5.29.3, but this issue came up after trying to update to 5.41.1

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Armada UI

## Steps to reproduce the issue

1. Have table with overflow menu inside
2. Click on overflow menu

**Comment by joshblack** [comment]
Hi @davidmenendez! 👋 Thanks for copying this over from the Slack channel 😄 

One thing that'd help out a lot is a repro link using the codesandbox template so that we can track down what exactly is going on here 🤔

**Comment by davidmenendez** [comment]
Ok I was finally able to recreate this based on how Armada UI uses the table component https://codesandbox.io/s/jzrj6wvp7v

The key to this bug is the scroll. Make the height of the sandbox browser small enough so that you have to scroll to see the bottom rows. Scroll to a bottom row and click on the expand action for that row. Leave it open. Scroll up to the top and click on the first row overflow. You are then sent to the bottom of the page.

![overflow-bug2](https://user-images.githubusercontent.com/6370760/38569300-7dbd1ae2-3cb0-11e8-822e-f65c5b616cb3.gif)

**Comment by asudoh** [comment]
💯 Thanks alot for @davidmenendez for this reduced test case! Will look into it.

**Comment by shinytoyrobots** [comment]
@davidmenendez - can you grab a Carbon developer (@asudoh is in office today before leaving to return to Tokyo) and go through the steps to reproduce this? We haven't been able to reproduce ourselves.

**Comment by davidmenendez** [comment]
I'm working remotely today, but I'd be happy to explain in person if my previous comment needs more clarification 👍

**Comment by davidmenendez** [comment]
i didn't originally save the sandbox to my account. here's the updated link https://codesandbox.io/s/ojl4yxo42q

**Comment by asudoh** [comment]
@davidmenendez has kindly updated his reduced case, which revealed that we presumably need to fix the focus management stuff. Will take a further look.
