### ISSUE TITLE
List of Carbon components unreachable - `react.carbondesignsystem.com`

### ISSUE THREAD

**Issue by apollomusa** [carbon-design-system/carbon-components-react#796]
I am receiving `502 Bad Gateway: Registered endpoint failed to handle the request.` when trying to access http://react.carbondesignsystem.com/

**Comment by joshblack** [comment]
Hi @apollomusa! 👋 Thanks for giving us a heads up. Taking a look at this now!

**Comment by joshblack** [comment]
Should be up now 😄 Feel free to re-open if you're getting the same connection issue!
