### ISSUE TITLE
The Modal component, doesn't close when expected. 

### ISSUE THREAD

**Issue by rezak-otmani** [carbon-design-system/carbon-components-react#797]
## Detailed description

The Modal component, doesn't close when expected. 

## Steps to reproduce the issue

http://react.carbondesignsystem.com/?selectedKind=Modal&selectedStory=transactional&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

## Additional information

* Screenshots or code
* Notes

**Comment by asudoh** [comment]
Copying from https://github.com/carbon-design-system/carbon-components-react/pull/805 - IIUC `<Modal>` itself is not responsible for user action of closing modal. Some higher-order component using `<Modal>` is responsible for that. The biggest example is `<ModalWrapper>` as you may have found - It handles `onRequestClose` to change its internal state and send such internal state to `<Modal>` via `open` prop.
