### ISSUE TITLE
Simplify and provide instructions fo create-react-app

### ISSUE THREAD

**Issue by rvennam** [carbon-design-system/carbon-components-react#8]
I think [create-react-app](https://facebook.github.io/react/docs/installation.html) is becoming the defacto standard for starting a new react application. The README for carbon-components-react should detail instructions for this flow.

**Comment by marijohannessen** [comment]
@joshblack is this something you would like to tackle?

**Comment by joshblack** [comment]
For sure! Will add in an `examples` folder and one will be `create-react-app` 😄
