### ISSUE TITLE
Bug - Loading component can not mask Select component 

### ISSUE THREAD

**Issue by ilovepumpkin** [carbon-design-system/carbon-components-react#80]
Maybe "z-index" should be set on the overlay div. 
```
    return withOverlay
      ? <div className="bx--loading-overlay">
          {loading}
        </div>
      : loading;
```

**Comment by marijohannessen** [comment]
Hi @ilovepumpkin , can you please explain the steps you took in order to reproduce this bug? Thank you!

**Comment by ilovepumpkin** [comment]
Please check the following demo code - you will find you are still able to operate the Select control during the Loading works. 

[![Edit LoadingDemo](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/Wn1Qk9LJg)

**Comment by tw15egan** [comment]
@ilovepumpkin thanks for submitting that example! It seems like `bx--loading-overlay` does not have an overlay set. This should be set to one of our `z-index` levels (7000 or 9000)

**Comment by tw15egan** [comment]
I'm going to move this over to the Vanilla repo as this is just a styling issue

**Comment by tw15egan** [comment]
Issue moved to [carbon-design-system/carbon-components #403](https://github.com/carbon-design-system/carbon-components/issues/403) via [**ZenHub**](https://www.zenhub.com/)
