### ISSUE TITLE
No option to focus on a transactional Modal

### ISSUE THREAD

**Issue by akim316** [carbon-design-system/carbon-components-react#803]
## Detailed description

> Describe in detail the issue you're having.

There is no property to focus on an element in a Modal.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Feature request

> Is this issue related to a specific component?

Modal

> What did you expect to happen? What happened instead? What would you like to see changed?

I expected the first element (TextInput, Dropdown, etc) in the Modal to be focused when opening, or the primary button to be focused if there are no other elements inside the Modal.

> What browser are you working in?

Chrome version 65

> What version of the Carbon Design System are you using?

Latest

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Cloud Account. No pressing release dates.

## Steps to reproduce the issue

Find an org in a Bluemix account, go to the overflow menu and click rename
In this case, the TextInput should have focus.

For a case without TextInput or other elements, go to the Remove Domain modal under Domains > click the overflow menu > Remove from Org
In this case, the Remove button (primary button) should have focus.

## Additional information

* I currently have a workaround solution in place locally, and as such would be willing to make the necessary changes on Carbon instead.

**Comment by asudoh** [comment]
Hi @akim316 seems that you got a great point! And we are welcome for contribution - It'd be great if the first focusable element can be made configurable (like [what the vanilla version does](https://github.com/carbon-design-system/carbon-components/blob/dee694d/src/components/modal/modal.js#L89)) if you want to got forward with the implementation. Thanks!
