### ISSUE TITLE
Tooltip's Icon Component Doesn't Need SVG Title Tag

### ISSUE THREAD

**Issue by showeimer** [carbon-design-system/carbon-components-react#804]
## Detailed description

> Describe in detail the issue you're having.

When using the Tooltip component, the iconDescription whether by default or entered value gets passed to the Icon component's `svg` `title` tag and this causes the title text to layover the Tooltip content when hovering over the icon.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

Tooltip & Icon

> What did you expect to happen? What happened instead? What would you like to see changed?

Title tag should not be rendered when using the Tooltip component.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

"carbon-components": "^8.6.0",
"carbon-components-react": "^5.29.5",

## Steps to reproduce the issue

You can see this problem on the [Storybook Page](http://react.carbondesignsystem.com/?selectedKind=Tooltip&selectedStory=default%20%28bottom%29&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

## Additional information

![img_20180412_085406](https://user-images.githubusercontent.com/26075187/38678655-a60f5a16-3e2f-11e8-9bd0-56f10c289e07.jpg)

**Comment by asudoh** [comment]
Hi @showeimer thank you for reporting - I think it's the same issue as https://github.com/carbon-design-system/carbon-components-react/issues/726, but please feel free to reopen this if you think otherwise!
