### ISSUE TITLE
Fix NumberInput event onChange

### ISSUE THREAD

**Issue by AdrianM20** [carbon-design-system/carbon-components-react#807]
Hi! I see that this problem persists since Jun 2017. Are you not going to do anything about it?
When you try to pass the event.target to a function for onChange the target is an svg and contains nothing regarding the NumberInput. Look it up here:
[![Edit carbon-components-react](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pw14pzw800)

**Comment by Yohanna** [comment]
Hi @AdrianM20, You can access the value through `e.imaginaryTarget.value`. I know the storybook doesn't mention this but I added a comment in the component's source in an earlier PR to hopefully guide people in the right direction: [NumberInput.js](https://github.com/carbon-design-system/carbon-components-react/blob/master/src/components/NumberInput/NumberInput.js#L19)

**Comment by AdrianM20** [comment]
Thank you for your help. It's a workaround but I think it should be temporary and should be fixed so the event data is in event.target so there would be consistency among components.

**Comment by asudoh** [comment]
@AdrianM20 I wish that would have happened, too - The way how native `<input>` is decorated makes the `target` of `event` something different from `<input>` and thus the set of properties there will be different. The workaround is allowing the event to refer to `<input>` to that allows consumer to get the full list of properties.

**Comment by emyarod** [comment]
This issue has been presented again in #984.

Would directly assigning the new `event.target` to the `_inputRef` be a feasible solution in this case?

**Comment by asudoh** [comment]
Hi @emyarod thank you for putting your thoughts here - I may have misinterpreted your question, but we preserved the original event target to let consumer detect where the original event come from, etc.

**Comment by emyarod** [comment]
Thanks @asudoh I understand the intention to preserve the original event target. I am just suggesting that given the use case of this NumberInput component, it seems more likely that the user is looking to fetch the value of the input field rather than the arrow buttons. That being said, I have no issue at all with the current implementation, if that is how the team has decided to proceed.

May be worth adding more prominent documentation about `event.imaginaryTarget` for end users

**Comment by asudoh** [comment]
My apologies for getting back on this late - :100: @emyarod! Documentation PR is appreciated any time!
