### ISSUE TITLE
StructuredListWrapper doesn't respond to the size of the screen very well

### ISSUE THREAD

**Issue by srlim** [carbon-design-system/carbon-components-react#812]
## Detailed description

> Describe in detail the issue you're having.
When the screen size is small, structured list doesn't respond the size very well.
![image](https://user-images.githubusercontent.com/5316797/38788225-903ff460-4100-11e8-8f87-a06fcf497d53.png)

> Is this a feature request (new component, new icon), a bug, or a general issue? bug

> Is this issue related to a specific component? StructuredListWrapper

> What did you expect to happen? What happened instead? What would you like to see changed?
It should be able to contain its contents in the wrapper.

> What browser are you working in? Chrome, Firefox

> What version of the Carbon Design System are you using?
carbon-components: 8.16.8
carbon-components-react: 5.29.5

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
IBM Cloud Private

## Steps to reproduce the issue

https://codesandbox.io/s/0qjlxnmz30

If you reduce the width of the browser size to smaller than 377, module wrapper content isn't contained within the window

**Comment by aagonzales** [comment]
Headers can wrap up to two lines and should be aligned along the base line (not vertically centered that's being shown. That's a bug on our side)
<img width="569" alt="image" src="https://user-images.githubusercontent.com/11670886/39149024-7217e0f2-4703-11e8-8aaf-c5dde0ddc752.png">

Structured Lists should trigger a horizontal scroll on smaller screens. Columns should decrease to their smallest size (chosen by each individual use-case made my product side designers).
<img width="591" alt="image" src="https://user-images.githubusercontent.com/11670886/39149156-db69985c-4703-11e8-8c15-02d218f80dc6.png">

**Comment by joshblack** [comment]
Thanks @aagonzales! 🙏 Moving this over to `carbon-componenst` for a style fix 😄

**Comment by joshblack** [comment]
Issue moved to [carbon-design-system/carbon-components #721](https://github.com/carbon-design-system/carbon-components/issues/721) via [**ZenHub**](https://www.zenhub.com/)
