### ISSUE TITLE
Improve accessibility of OverflowMenuItem

### ISSUE THREAD

**Issue by asfordmatt** [carbon-design-system/carbon-components-react#818]
To be accessible, overflow menus need to be usable using the keyboard. Currently the OverflowMenu component correctly opens the menu when Enter/Space is pressed, but then it appears to be up to the consumer to implement onKeyDown handlers on every OverflowMenuItem to check for Enter/Space and then invoke the action for that menu item. 

I'd like to propose a feature where the framework provides some good default behaviour, which would save the consumer doing the extra work adding key handlers. That default behaviour would be for OverflowMenuItem to call the onClick() function if the Space or Enter key is pressed on the menu item. (If the consumer passes in their own onKeyDown prop, that would be used instead).

I'll submit a PR so you can see my suggestion.

**Comment by joshblack** [comment]
Hi @asfordmatt! 👋 Does #684 help address this issue at all?

**Comment by asfordmatt** [comment]
@joshblack that looks useful in its own right, but separate to this. Pressing Space/Enter on a menu item needs to perform that action.

**Comment by joshblack** [comment]
Awesome! Sounds good, was just checking 👍
