### ISSUE TITLE
Hover over the Icon component in Edge does not work

### ISSUE THREAD

**Issue by ashleylord8** [carbon-design-system/carbon-components-react#820]
## Detailed description

While using Microsoft Edge as my browser, I do not get a description when I hover over an `<Icon />` component. 

This is a bug.

This issue is related specifically to the `<Icon />` component.

I would like the ability to hover over an `<Icon />` component and see a description while within Microsoft Edge.

I am working with Microsoft Edge as my browser.

These are the versions of Carbon I am currently using:
```
"carbon-addons-cloud": "^1.2.1",
"carbon-components": "^8.16.5",
"carbon-components-react": "^5.41.1",
"carbon-icons": "^6.2.0",
"carbon-themes": "^1.6.0",
```

I am part of the IBM Watson Assistant team using Carbon within the product.

## Steps to reproduce the issue

Go into Edge, hover over an `<Icon />` with a `description` attribute, and you will not see any description when you hover.

I originally had:
```
<Icon
    className="some-class-name"
    description={'Description'}
    name={'close'}
/>
```

With the advice from @joshblack I tried to add a `title` attribute, but that didn't fix the problem either:

```
<Icon
    className="some-class-name"
    description={'Description'}
    name={'close'}
    title={'Title'}
/>
```

**Comment by mven** [comment]
@ashleylord8 I just ran some tests on Edge and may have found a solution.

Inside the `Icon` module, try wrapping the `<title>` and `<path>` into a `<g>`. 

Might need some input from @joshblack to see if there are any backwards compatibility concerns if merged into code base.

**Comment by joshblack** [comment]
Going to label this as wont fix on our end given that this doesn't seem to be impacting any service directly in terms of a11y, or some other requirement offerings might have. Feel free to re-open if that's not the case!
