### ISSUE TITLE
Components for an instant message system in IBM.

### ISSUE THREAD

**Issue by Ketcomp** [carbon-design-system/carbon-components-react#822]
#### Detailed description
It would be great to have components directly meant for a agent-customer chat in the React repo. Currently Modules, text areas and buttons must be used like Lego pieces to put together a customer (read: non-uniform) chat experience.

> Describe in detail the issue you're having.
Having to pick and choose components for a chat system or a comments system resulting in a non-uniform experience across various IBM tools. 

> Is this a feature request (new component, new icon), a bug, or a general issue?
Feature request.

> Is this issue related to a specific component?
No.

> What version of the Carbon Design System are you using?
^ 5.39.2

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Business Application Development - Unified Support micro-service.

**Comment by joshblack** [comment]
Hi @Ketcomp! 👋 This is an amazing suggestion, although it might be possible that this would be more appropriate for a Carbon Add-on versus a core component. What do you think?

**Comment by joshblack** [comment]
A Carbon Add-on is just a way for groups to share common code in a specific sub-group of IBM. The scope of the core library is that it supplies components that can be used by all of IBM. The scope of an add-on is that it provides the components per a specific group/offering/BU/etc.

For example, IBM Collaborative Solutions has their own Add-on that they maintain that introduces new components on top of Carbon core for their development teams to use 👍 

This strategy mostly has to deal with our limited bandwidth as a team. We would love to support all the components, but unfortunately have to be realistic with the surface area of components that we can reliably maintain, provide support for, etc. As a result, the Add-on model was created to enable teams to participate in the Carbon ecosystem without direct core team involvement.

**Comment by Ketcomp** [comment]
I see. That makes sense :) This would be a work item for a team that would work on the Watson Chat bot (which _could_ be my team but currently is not) I am happy to close this issue or mark it as appropriately resolved, whatever is convention. Or you can do it too. Thanks! 👍
