### ISSUE TITLE
Card component missing details in playbook

### ISSUE THREAD

**Issue by AdrianM20** [carbon-design-system/carbon-components-react#824]
Hi! Browsing the playbook I discovered the Card component and I wanted to use it but in the show info tab is nothing usefull about how to use it and its properties. Can someone fix that, please? Thank you!

**Comment by joshblack** [comment]
Hi @AdrianM20! 👋 Unfortunately this is a limitation of Storybook and its associated info plugin. For full details and source, can always view the story itself in our repo. We're hoping to add some additional plugins that will make this kind of information available from the website directly, so be on the lookout for that!

* [Story Link](https://github.com/carbon-design-system/carbon-components-react/blob/master/src/components/Card/Card-story.js)
* [Source Link](https://github.com/carbon-design-system/carbon-components-react/blob/master/src/components/Card/Card.js)

Going to close this for now, feel free to re-open if you feel like I haven't addressed the issue!
