### ISSUE TITLE
Modal loses focus when opening

### ISSUE THREAD

**Issue by akim316** [carbon-design-system/carbon-components-react#827]
## Detailed description
Modal loses focus when opened if it does not contain any input elements in its body. Happening in Chrome in the latest version of Carbon

## Steps to reproduce the issue

With existing Domain in Bluemix account:
Bluemix account > My profile > Cloud foundry orgs > Domains > Overflow menu > Remove from org

## Additional information
(I used an extension to accentuate the focused element)
Not working as intended:
![apr-20-2018 14-46-08](https://user-images.githubusercontent.com/9680155/39071043-3a5935bc-44ab-11e8-85f3-a168bf584b3c.gif)

Working as intended:
![apr-20-2018 14-49-32](https://user-images.githubusercontent.com/9680155/39071052-46499e20-44ab-11e8-8e97-a377b896afdf.gif)

I am setting elements to be focused in the component's componentDidUpdate method in both situations, but it only focuses on the one with the TextInput. I was hoping to fix this issue with the inclusion of #808 however, it is still causing it to not submit upon pressing Enter. I have a hacky workaround in place which sets a timeout to wait 0.3 seconds after componentDidUpdate is called, and then focuses.

Workaround:
![apr-20-2018 14-57-31](https://user-images.githubusercontent.com/9680155/39071066-536f9852-44ab-11e8-8910-d73ebaa19533.gif)

If someone has encountered this issue, or know of a better fix, that would be much appreciated!

**Comment by asudoh** [comment]
@akim316 Thank you for filing this issue! My suggestion here is porting [this vanilla code](https://github.com/carbon-design-system/carbon-components/blob/a96aa00/src/components/modal/modal.js#L89) to React.

**Comment by emyarod** [comment]
would using the `autoFocus` prop be appropriate in this case? it may [create problems with a11y](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-autofocus.md) though

**Comment by emyarod** [comment]
so I can think of 2 options to solve this issue, but I would like some input before proceeding:

1 method would be to added the `autoFocus` attribute to the primary button or the `modalButton` in `Modal.js` depending on whether or not the modal is passive.

Another method would be to convert the `Button` component from a stateless functional component to a class component, so that we can attach a `ref` and call the `focus` method when the Modal component is mounted
