### ISSUE TITLE
Unknown prop `pageSize` on <div> tag

### ISSUE THREAD

**Issue by nicoxxie** [carbon-design-system/carbon-components-react#83]
```
warning.js?8a56:36 Warning: Unknown prop `pageSize` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
```

On pagination component, all other unrecognized props are passed in to the div and set as HTML attributes.  And HTML doesn't recognize pageSize.
https://github.com/carbon-design-system/carbon-components-react/blob/55d46f4ee52d4953cad18305f596974381163f86/components/Pagination.js#L104

You would just have to do what `page` attribute is doing on L96, assign it to another temporary variable(that won't be used) so pageSize won't be a part of `...other` and get set on the div.
https://github.com/carbon-design-system/carbon-components-react/blob/55d46f4ee52d4953cad18305f596974381163f86/components/Pagination.js#L96

**Comment by hellobrian** [comment]
If this issue remains unassigned, feel free to assign yourself and submit a PR with a bug fix.

**Comment by marijohannessen** [comment]
This is resolved
