### ISSUE TITLE
Tooltip: position is incorrectly calculated when margins are applied

### ISSUE THREAD

**Issue by McBrosa** [carbon-design-system/carbon-components-react#834]
## Detailed description
When adding a margin to a div that contains a Tooltip the position on the info box is incorrectly displayed.

## Steps to reproduce the issue
https://codesandbox.io/s/vq4q7m9jky

## Additional information

![screen shot 2018-04-24 at 2 23 15 pm](https://user-images.githubusercontent.com/5651466/39209282-13e1f55e-47cb-11e8-9479-1f98bf089920.png)

**Comment by asudoh** [comment]
Thanks @McBrosa for reporting with a reduced test case! Will take a look at and see if there is a bug in our code.

**Comment by asudoh** [comment]
While it seems that handling the margin there is not in the scope of our floating menu code, `<Tooltip>` has `props.menuOffset` that allows you to change the floating menu position e.g. for the case reported. An object with `left`/`top` properties or a function returning such object can be used there. @McBrosa would you try that prop and see it works for your case? Thanks!

**Comment by asudoh** [comment]
Cool that you made it working! If you want hard-coding, you may want to try `window.getComputedStyle(theDOMNodeWithMargin).getPropertyValue('margin-top’)`. As noted before, `props.menuOffset` can take a function.

**Comment by McBrosa** [comment]
Sounds good thanks for the help
