### ISSUE TITLE
[DataTable] TableToolbarSearch placeholder text not customizable / translatable

### ISSUE THREAD

**Issue by rkocheis** [carbon-design-system/carbon-components-react#837]
> Describe in detail the issue you're having.

Our UX design provides for a customized placeholder text for the Search field. This placeholder text and other default text should also be enabled for translation. 

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug

> Is this issue related to a specific component?

DataTable / TableToolbarSearch

> What did you expect to happen? What happened instead? What would you like to see changed?

Expected to be able to customize similar to regular Search component. TableToolbarSearch seems to hard-code those strings. 

> What browser are you working in?

All

> What version of the Carbon Design System are you using?

5.40

**Comment by joshblack** [comment]
Hi @rkocheis! 👋 Thanks for taking the time to make this issue 🙂 Definitely agreed that we need to externalize strings to enable use-cases like i18n. Will gladly accept any PRs that introduce this behavior into the project!

**Comment by LongBu** [comment]
@joshblack 
I have a similar request, but perhaps there is a work around?

Describe in detail the issue you're having.

react-i18next vs carbon-components-react

We're utilizing several different DataTable / TableToolbarSearch instances within the same app and need to have the placeholder text that differs for each in different languages.  Perhaps I'm misunderstanding this, but does the translateWithId only offer one reference for each of these components to point to (eg is there away for placeholder text for component 1=>'search placeholder text for widget 1' and  component 2=>'search placeholder text for widget 2' )?

Is this a feature request (new component, new icon), a bug, or a general issue?

bug or feature request (not certain?)

Is this issue related to a specific component?

DataTable / TableToolbarSearch

What did you expect to happen? What happened instead? What would you like to see changed?

Expected to be able to customize similar to Search component as we have multiple DataTable/TableToolbarSearch fields in the same app. TableToolbarSearch seems to hard-code to only one root placeholder text per app.  

What browser are you working in?

All

What version of the Carbon Design System are you using?

carbon-components-react@6.26.0

**Comment by joshblack** [comment]
Hi @LongBu! 👋 Mind making this in a separate issue? Would hate for it to get lost in this thread since it's closed.
