### ISSUE TITLE
[Enhancement] support timeout prop for ToastNotification

### ISSUE THREAD

**Issue by scottdickerson** [carbon-design-system/carbon-components-react#846]
## Detailed description
Shouldn't Toast Notifications disappear after a certain amount of configurable time?  My request is to add a configurable timeout prop to make the ToastNotification close automatically.   
> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general issue?

feature request

> Is this issue related to a specific component?

ToastNotification

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by joshblack** [comment]
Hi @scottdickerson! 👋 Thanks so much for taking the time to make this suggestion for an enhancement 🙂

Definitely agreed, and I believe the specs state that this should close automatically after 3000ms.
