### ISSUE TITLE
ComposedModal's onKeyDown does not work

### ISSUE THREAD

**Issue by showeimer** [carbon-design-system/carbon-components-react#851]
Currently working on accessibility issues on ICP.  We are not able to use the `esc` key to quickly close the ComposedModal.

---

I see that there is logic to listen for an `esc` key press and set the `open` state to false.

https://github.com/carbon-design-system/carbon-components-react/blob/master/src/components/ComposedModal/ComposedModal.js#L22

However, I think the `div` that is being returned by `ComposedModal` needs a `tabIndex='0'` in order to be able to listen to keyboard events in React.

https://github.com/carbon-design-system/carbon-components-react/blob/master/src/components/ComposedModal/ComposedModal.js#L75

---

I came across these two sources that mentioned `tabIndex` being required to use `onKeyDown`:

- https://stackoverflow.com/questions/43503964/onkeydown-event-not-working-on-divs-in-react?answertab=active#tab-top

- https://drkbl.com/div-not-response-to-keyboard-event-without-tabindex/

**Comment by joshblack** [comment]
Hi @showeimer! 👋 Thanks so much for taking the time to make this issue! Will definitely investigate further to see what the root cause is here. Will also accept any/all PRs that help to address this, in the meantime!
