### ISSUE TITLE
Add the ability to create custom named Tags and close Tags

### ISSUE THREAD

**Issue by akim316** [carbon-design-system/carbon-components-react#865]
I will be working on this issue. Currently trying to add this ability based off the Tagging project currently being worked on. Rough specs available on this [issue](https://ibm.biz/BdZLjb). Some of those specs may not be added directly to the Tag component but on the TagList or TagArea component that will also be created.

**Comment by tay-aitken** [comment]
Yes, I worked with the designer that made this so we could eventually bring it into the carbon library. I think we will need to make a few tweaks, some decisions were made for their use case that we may need to pull on on for global use. But overall, yes would like to bring this pattern in :)

**Comment by joshblack** [comment]
Thanks @tay-aitken! 🎉

**Comment by asudoh** [comment]
Hi @akim316 thank you for entering this issue and the associated PR? To get better context - Does this have something to do with the issue/PR you entered in `carbon-components` repo? If so, great to have cross-link to them here - Thanks!

**Comment by akim316** [comment]
This is the issue and PR in `carbon-components`, respectively.
https://github.com/carbon-design-system/carbon-components/issues/762
https://github.com/carbon-design-system/carbon-components/pull/763
