### ISSUE TITLE
Tooltip closes whenever parent rerenders

### ISSUE THREAD

**Issue by nicthemighty** [carbon-design-system/carbon-components-react#876]
## Detailed description

> Describe in detail the issue you're having.
Whenever the tooltip is open, if parent rerenders the tooltip closes. 

It looks like the tooltip has a default property of 'open' set to false. Whenever it receives new props (as part of parent rerender), the tooltip sets state 'open' to the value of prop.open (which is always false). This causes the tooltip to close.

> Is this a feature request (new component, new icon), a bug, or a general issue?
Bug

> Is this issue related to a specific component?
Tooltip

> What did you expect to happen? What happened instead? What would you like to see changed?
Expected tooltip to stay open

> What browser are you working in?
Chrome & Safari macOS X

> What version of the Carbon Design System are you using?
5.36.0

## Steps to reproduce the issue

[Codesandbox](https://codesandbox.io/s/ox5m94lxj5)

1. Hover on tooltip
2. Wait 3 seconds, it will then close

**Comment by joshblack** [comment]
Hi @nicthemighty! 👋 Thanks so much for making this issue. Definitely agreed this is an issue with the component, so went ahead and labelled it as a bug. Will try and get it prioritized to one our sprints as a bug fix task, but will also accept any/all PRs that help to address this!
