### ISSUE TITLE
Tooltip click to open does not update trigger position

### ISSUE THREAD

**Issue by nicthemighty** [carbon-design-system/carbon-components-react#881]
## Detailed description

> Describe in detail the issue you're having.

When the page rerenders, click to open tooltip is using the trigger position from componentDidMount(), not from the current render position

> Is this a feature request (new component, new icon), a bug, or a general issue?
Bug

> Is this issue related to a specific component?
Tooltip

> What did you expect to happen? What happened instead? What would you like to see changed?
Tooltip should open in the correct position relative to the current trigger position

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
5.36.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Click on the tooltip
2. Once the text refreshes after 5 seconds click on the tooltip again
3. Note the position hasn't been updated for the tooltip

**Comment by asudoh** [comment]
https://github.com/carbon-design-system/carbon-components-react/pull/1007 may have addressed this issue as well. Feel free to reopen if it’s not the case.
