### ISSUE TITLE
Tooltip disconnected from icon being hovered in IE11 after page scrolling

### ISSUE THREAD

**Issue by llukenbill** [carbon-design-system/carbon-components-react#882]
## Detailed description

> Describe in detail the issue you're having.

Tooltips in IE11 are disconnected from the Tooltip icon when the tool tip is initially loaded off the screen and then a user scrolls the window for it to be in view. The window scrolling seems to throw of the offsets the Tooltip is using to calculate the position of where it should be displayed. It can look like the tooltip isn't showing at all (off the currently viewed section) but if you scroll the page up it'll be there. Found this out by using the click to open attribute. This made debugging a little easier.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Internet Explorer bug. Seems to be working just fine in Chrome and Firefox.

> Is this issue related to a specific component?

Yes - the Tooltip component.

> What did you expect to happen? What happened instead? What would you like to see changed?

I expected the tooltip dialog to be next to the icon that is being hovered. Instead it is somewhere else on the page. The horizontal calculations work correctly (as in it's in line with the icon), but where the dialog is placed vertically isn't where it should be. Just want it so the user can see it with ease and not have to jump around to look for it or assume it's not showing because it's out of the current view.

> What browser are you working in?

IE11 :(

> What version of the Carbon Design System are you using?

Version bug was found: 3.12.5 , but I did also verify it was happening in version: 5.27.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Observer in Control Portal

## Steps to reproduce the issue

Codesandbox URL:  https://codesandbox.io/s/6vlqo93qmw
*make sure you're using IE and also to size the viewing window down so you have to scroll to the bottom tool tip. 

1. Add a Tooltip component to the bottom of a decent sized page with other components on it. 
2. Minimize window, so Tooltip component  is out of view.
3. Scroll to Tooltip component so it's in view.
4. Hover Tooltip component, these steps should result in the Tooltip dialog being disconnected from the icon that's being hovered.

## Additional information

* Screenshots or code
![image](https://user-images.githubusercontent.com/39274272/40014144-56a80a72-5775-11e8-82a0-e6efbe0ecd4e.png)
![ie11tooltipissue](https://user-images.githubusercontent.com/39274272/40014167-6b78a29a-5775-11e8-8833-93ec3b0f10ac.PNG)

* Notes

**Comment by asudoh** [comment]
Thanks @llukenbill for reporting and the test case! The issue sounds similar to #895 - Given `<Tooltip>` has `menuOffset` prop similar to `<OverflowMenu>`, you may want to try that for the interim.

**Comment by kglickman** [comment]
I'm seeing something similar on Chrome.
1.  Make a long page with a tooltip in the middle.
2.  Scroll so that the tooltip icon now appears near the top of the page
3.  Click on the tooltip.
The tooltip pops up at the bottom of the page, scrolled out of view, instead of near the launch icon.

**Comment by tw15egan** [comment]
@kglickman which version of the components are you seeing this on?

**Comment by kglickman** [comment]
I tried it with the latest.

**Comment by tw15egan** [comment]
I'm unable to reproduce this locally. Could you link to a Codesandbox that shows this?

**Comment by kglickman** [comment]
Here it is.  It seems to have maintained the tab title from the OverflowMenu one I copied. 
 I'm not spotting why.  https://codesandbox.io/s/ymqww0vw09

1.  Make the window small so that a scroll bar appears.
2.  Scroll all the way to the bottom
3.  Click the tooltip icon.
