### ISSUE TITLE
Warnings on console for "minDate" and "maxDate" on DatePicker

### ISSUE THREAD

**Issue by tonydiaz** [carbon-design-system/carbon-components-react#898]
## Detailed description

> Describe in detail the issue you're having.

Seeing warning appear on the console when using minDate and maxDate for the DatePicker

> Is this a feature request (new component, new icon), a bug, or a general issue?

Bug

> Is this issue related to a specific component?

DatePicker

> What did you expect to happen? What happened instead? What would you like to see changed?

I expect no console warnings for using these props

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

v5.50.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Watson Assistant

## Steps to reproduce the issue
Use the DatePicker component with the minDate and maxDate 

[Codesandbox](https://codesandbox.io/s/3y3l8q99j5) 

1. Step one - Looks at the console for the codesandbox

## Additional information

* Screenshots or code
<img width="483" alt="screen shot 2018-05-17 at 4 09 35 pm" src="https://user-images.githubusercontent.com/7145340/40201317-bc3cf496-59ec-11e8-8351-7f09c1da379a.png">

* Notes

**Comment by asudoh** [comment]
@weijiekoh Seems that we need to prevent `minDate`/`maxDate` from being propagated to DOM node. Would you want to work on that…? Thanks!

**Comment by tonydiaz** [comment]
I posted a PR to resolve the issue, incase you are interested in using it: https://github.com/carbon-design-system/carbon-components-react/pull/899
