### ISSUE TITLE
Multiselect component's initialselected items is not showing marked checkboxes

### ISSUE THREAD

**Issue by LiziParhi** [carbon-design-system/carbon-components-react#901]
## Detailed description

I am using multiselect component , i am giving it initialSelectedItems but it doesn't do anything with that. I even hard coded directly in component to test if its any syntax error or something but no still show of initialselecteditems .
Weird thing is I can see the count of intialselecteditems
<img width="469" alt="screen shot 2018-05-18 at 10 44 42 am" src="https://user-images.githubusercontent.com/12204048/40244463-8f002286-5a88-11e8-9f3b-16537879ee37.png">
<img width="412" alt="screen shot 2018-05-18 at 10 44 50 am" src="https://user-images.githubusercontent.com/12204048/40244471-9272aec0-5a88-11e8-97f7-b681ca37eab0.png">

> Is this a feature request (new component, new icon), a bug, or a general issue?
a bug
> Is this issue related to a specific component?
multiselect component
> What did you expect to happen? What happened instead? What would you like to see changed?
to show the marked initial selected items
> What browser are you working in?
safari

> What version of the Carbon Design System are you using?
5.41.6
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by LiziParhi** [comment]
@joshblack

**Comment by joshblack** [comment]
Hi @LiziParhi! 👋 Thanks so much for taking the time to make this issue. Something that would be really helpful to debug this issue is to provide a codesandbox link based off of the issue template that demonstrates the issue. Thanks!

**Comment by kylembrake** [comment]
@joshblack I'm having this issue as well. Here is a codesandbox that recreates it: https://codesandbox.io/s/yj61j6mlqx

**Comment by joshblack** [comment]
Hi @kylembrake! 👋 In this case, you just need to make sure that the reference to the item is the same 👍 for example:

```js
const items = [{ label: "Option 1", id: 1 }]

const App = () => (
  <div>
    <MultiSelect.Filterable
      items={items}
      initialSelectedItems={[items[0]]}
      placeholder="Example"
    />
  </div>
);
```

**Comment by scottdickerson** [comment]
it's doing an in-memory object comparison in the code.  Unfortunately I can't really use this approach as my previous value is coming from a server/redux store.  I'll put in a fix to do a id to id comparison instead, sound ok?
