### ISSUE TITLE
Dropdown custom icon

### ISSUE THREAD

**Issue by jokerstudios** [carbon-design-system/carbon-components-react#91]
Hey there,
could you create an icon property for the Dropdown component?
It would be great to select a different arrow icon.
For example I want to use 'chevron--down' as my dropdown arrow.

**Comment by hellobrian** [comment]
☝️ What do you think @tay-aitken or @aagonzales: are we okay with allowing other icons to be used in Dropdown component? 

Like the `chvron--down` icon:

![image](https://user-images.githubusercontent.com/4185382/28891698-0b69380c-7791-11e7-8fa0-059cb167ff07.png)

**Comment by tay-aitken** [comment]
@hellobrian I agree. I do not want to introduce another type of icon into the component for consistency. I also do not want people to get confused between an accordion and dropdown. That icon is one thing that differentiates the two.

**Comment by Kenzku** [comment]
Hej, @tay-aitken @hellobrian 

just a follow up, I was wondering if some options can be added in so, the carat can be hidden (although this can be achieved by CSS overwritten) , and other icon can be added. e.g. we have some designed request: https://github.ibm.com/TransformationAdvisor/development-tasks/issues/1200

**Comment by aagonzales** [comment]
@Kenzku If its a dropdown than we require it to have a `carot` icon to indicator that it has more options inside. Otherwise it could look just like a link.
