### ISSUE TITLE
Page of Carbon components is not working -> `react.carbondesignsystem.com`

### ISSUE THREAD

**Issue by fedecarpi** [carbon-design-system/carbon-components-react#934]
I'm getting this while trying to access to http://react.carbondesignsystem.com/ or http://carbondesignsystem.com/
---------------------------------
This site can’t be reached
http://react.carbondesignsystem.com/ is unreachable.
Search Google for react carbon design system
ERR_ADDRESS_UNREACHABLE

**Comment by joshblack** [comment]
Hi @fedecarpi! 👋 Could you provide any more information about your system? Both of these sites are loading on our development machines so am curious what's going wrong here 🤔

**Comment by scottvincent** [comment]
Both still down here in Canada.

**Comment by davegillem** [comment]
Down for me as well (Texas)

**Comment by davegillem** [comment]
Down for me as well (Texas)

**Comment by scottvincent** [comment]
Update: Works here now!
