### ISSUE TITLE
FileUploader - support setting the name attribute of an input element

### ISSUE THREAD

**Issue by nhayashida** [carbon-design-system/carbon-components-react#945]
It is helpful if we can set the `name` attribute of the input element generated by the FileUploader component as a prop value.

## Detailed description

> Describe in detail the issue you're having.

As some server side components for handling an uploaded file like 
[multer](https://github.com/expressjs/multer) use the name attribute of an input element, client code can be simple if the FileUpload component supports setting the attribute like `<FileUploader name="fieldName" />.`

> Is this issue related to a specific component?

FileUploader

**Comment by emyarod** [comment]
This issue should be resolved by #974 in v6.4.0. Forgot to tag it properly in my PR
