### ISSUE TITLE
Bug: NumberInput: can not get number input event by onChange 

### ISSUE THREAD

**Issue by ilovepumpkin** [carbon-design-system/carbon-components-react#96]
I want to get the number input value by onChange of NumberInput. But now when I input the value directly in the input, I can got the input target, but if I use up/down icon, I get the svg element event, then I can not get the value of NumberInput.

**Comment by hellobrian** [comment]
Hey @ilovepumpkin, here's a demo on codesandbox with one way you can get the input value from the `NumberInput` component: 

[![Edit NumberInput - evt.target.value](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/x1OoVGE9)

☝️ There might be a more "React appropriate" way to do this but hopefully this can get you going until someone else chimes in.

**Comment by ilovepumpkin** [comment]
@hellobrian , I am using H5 number input now. Any benefit does NumberInput component provide than directly using H5 number input?

**Comment by hellobrian** [comment]
@ilovepumpkin when you say H5 number input...are you referring to a normal number input used in HTML? Like this?

```html
<input type="number" />
```

If that's what you meant, then really there's no advantage that our `NumberInput` comoponent offers. The only thing it does is add additional markup and classes so that it can use Carbon styles.

**Comment by ilovepumpkin** [comment]
@hellobrian , okay, thanks!

**Comment by gferreri** [comment]
This issue should be reopened. The original issue exists and the proposed solution by @hellobrian doesn't work. When `onChange` fires, `event.target.value` is `undefined`. The component is basically useless as-is.
