### ISSUE TITLE
[Bug]: Filterable for Multiselect is not found by React

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon-components-react#961]
@cknabe commented on [Mon Jun 04 2018](https://github.com/carbon-design-system/carbon/issues/29)

## Detailed description
When using MultiSelect.Filterable in React I am seeing an error in the console:
```
372:1 Uncaught Error: Module build failed: Error: C:/Users/IBM_ADMIN/git/Gen1.VSI/src/client/containers/Network/index.js: [babel-plugin-transform-carbon-imports] encountered the following imports that are not currently exported by `carbon-components-react`: [FilterableMultiSelect]
    at PluginPass.ImportDeclaration (C:\Users\IBM_ADMIN\git\Gen1.VSI\node_modules\babel-plugin-transform-carbon-imports\index.js:53:17)
```
My implementation is using:
```
import {
  Icon,
  Accordion,
  AccordionItem,
  MultiSelect,
} from 'carbon-components-react';

...

    return (
      <MultiSelect.Filterable
...
```

> Is this issue related to a specific component?

MultiSelect.Filterable

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

    "carbon-components": "8.16.8",
    "carbon-components-react": "5.31.0",
    "carbon-icons": "^6.1.0",

I did update to the newest and still saw the issue.

---

@cknabe commented on [Mon Jun 04 2018](https://github.com/carbon-design-system/carbon/issues/29#issuecomment-394395673)

> Josh Black [13 minutes ago]
> They might not be using it. The `Filterable` is defined on the module entrypoint for MultiSelect, but when the babel plugin rewrites the path it’s just pointing it straight to MultiSelect so the property never gets assigned

**Comment by cknabe** [comment]
Relates to usage of MultiSelect.Filterable in https://github.ibm.com/Bluemix/Gen1.VSI/issues/760
