### ISSUE TITLE
File Content not available on the FileUploader

### ISSUE THREAD

**Issue by nidhiag** [carbon-design-system/carbon-components-react#97]
I am using a FileUploader component , but i am not able to get the content of the files uploaded.

**Comment by hellobrian** [comment]
[![Edit FileUploader: access FileList](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mwEZnX5jA)

Here's a demo of using `onChange` prop and getting `FileList` from `evt.target.files`. 
Take a look, and let me know if this helps you out or not. Have you tried doing it this way before?
