### ISSUE TITLE
DatePicker with range - allow children elements in between DatePickerInput components

### ISSUE THREAD

**Issue by tonydiaz** [carbon-design-system/carbon-components-react#976]
## Detailed description

> Describe in detail the issue you're having.

Looking to have the capability to insert an element in between the two DatePickerInput components. Below is an example of having the word `to` in between the carbon components.
 
<img width="312" alt="screen shot 2018-06-07 at 9 31 45 am" src="https://user-images.githubusercontent.com/7145340/41102778-a2963fb2-6a35-11e8-8aa4-5ae20c1a7cb8.png">

> Is this a feature request (new component, new icon), a bug, or a general issue?

Feature

> Is this issue related to a specific component?

DatePicker

> What did you expect to happen? What happened instead? What would you like to see changed?

When children elements are entered in between the two DatePickerInput components that they render correctly in the place they were added. Today if an element is added in between the to DatePickerInput components then it will move the element(s) to the end. 

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

v5.50.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Watson Assistant. Currently part of design for the DatePicker.

## Steps to reproduce the issue

Here is an example of what I mean when you look at the `p` tag element in the rendered page you will see it was moved after the second DatePickerInput.

[Codesandbox](https://codesandbox.io/s/9zkq21l92r)

## Additional information

* Screenshots or code
* Notes

**Comment by marijohannessen** [comment]
@aagonzales @tay-aitken what's your input here?

**Comment by tay-aitken** [comment]
Hello @tonydiaz is there a reason you are not using the range date picker for your use case? It already implies the 'to'?

**Comment by tonydiaz** [comment]
I am using the range DatePicker in the [Codesandbox](https://codesandbox.io/s/9zkq21l92r) I posted. Design didn't think it implies the `to` that is why they want it. I will ask them to comment on this issue

**Comment by tw15egan** [comment]
Closing this issue for now, but feel free to reopen if we want to discuss this again in the future
