### ISSUE TITLE
Need consistent exports for components (index.js)

### ISSUE THREAD

**Issue by hellobrian** [carbon-design-system/carbon-components-react#98]
The [index.js](https://github.com/carbon-design-system/carbon-components-react/blob/master/index.js) is not consistently being exported since there are a lot of main components and sub-components that composes the main component. 

Anyway, here's how it should be:

```js
export FileUploader, { Filename, FileUploaderButton } from './components/FileUploader';
```

- `FileUploader` is the main component
- `{ Filename, FileUploaderButton }` are sub-components (or non-main components)

Also worth mentioning that changing the export statements in this file is probably a breaking change. 
Is there a way to resolve this issue in a non-breaking way?

**Comment by joshblack** [comment]
This seems like it's been taken care of when looking at `index.js`. Is this not the case?

**Comment by joshblack** [comment]
Gonna close this since I think it's good to go 🚀 

Anyone can feel free to re-open if that's not the case 😄
