### ISSUE TITLE
NumberInput: when clicking on the caret onChange binding to the wrong target

### ISSUE THREAD

**Issue by nicoxxie** [carbon-design-system/carbon-components-react#984]
## Detailed description

> Describe in detail the issue you're having.

When I click on the up caret, the onChange event.target is the button/svg/path node (depending on where you click) instead of the input.

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug

> Is this issue related to a specific component?

NumberInput

> What did you expect to happen? What happened instead? What would you like to see changed?

target is the input so the input value can be retrieved

> What browser are you working in?

chrome

> What version of the Carbon Design System are you using?

6.3

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM cloud

## Steps to reproduce the issue
Pass an onChange function and print the event.target.  Then monitor the target value when the up/down caret is clicked.

https://codesandbox.io/s/1q76z8yk7

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

**Comment by asudoh** [comment]
Hi @nicoxxie thank you for reporting! You can refer to `event.imaginaryTarget` for your purpose: https://github.com/carbon-design-system/carbon-components-react/issues/807#issuecomment-381146063

**Comment by tw15egan** [comment]
Closing as `event.imaginaryTarget` returns the correct target
