### ISSUE TITLE
OverflowMenuItem React PropTypes warning

### ISSUE THREAD

**Issue by eddiemonge** [carbon-design-system/carbon-components-react#99]
https://github.com/carbon-design-system/carbon-components-react/commit/98e44188867ef3d2c328303827e24241277a98c7#diff-a717bfe2b9545e8324b9bbdbec3a9001R19 introduced a console warning about the React PropTypes module.

 ```
console.warn node_modules/react/lib/lowPriorityWarning.js:40  Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
```

**Comment by chrisdhanaraj** [comment]
Bluemix [toolchain](https://console-regional.ng.bluemix.net/devops/toolchains/6b8b7163-1ec8-4616-82fa-aa467a17af03 "storybook-toolchain-v2"): [Delivery Pipeline](https://console-regional.ng.bluemix.net/devops/pipelines/b84aaac8-8484-4a1e-902a-ebb526eb7998 "storybook-toolchain-v2") deployed [carbon-components-react](https://github.com/carbon-design-system/carbon-components-react/releases/tag/deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20170802-190905 "deploy-ibm-yp-us-south-chrisdhanaraj_org-Bluemix-Design-System-20170802-190905") to [Bluemix Design System](https://console.bluemix.net/apps/0a253845-97bd-46c9-aa04-a220aeb8ed06?env_id=ibm:yp:us-south "ibm:yp:us-south:chrisdhanaraj_org:Bluemix Design System"), including commit 5504cad2a4705c56d33b2f9b34a826dc8b0ab187
