### ISSUE TITLE
feat(DatePicker) Past or future dates should have an added class so they can be styled differently

### ISSUE THREAD

**Issue by zerostatic** [carbon-design-system/carbon-components-react#994]
Example: I'd like to grey-out past dates as show here:
<img width="359" alt="screen shot 2018-06-12 at 11 52 21 am" src="https://user-images.githubusercontent.com/209432/41307679-17d30166-6e37-11e8-9846-420951d579b5.png">

**Comment by tw15egan** [comment]
There is already a color change if you set a `maxDate` and `minDate` like so:

```
<DatePicker
      {...datePickerProps}
      datePickerType="range"
      dateFormat="m/d/Y"
      minDate="06/10/2018"
      maxDate="07/15/2018">
      <DatePickerInput {...datePickerInputProps} id="date-picker-input-id" />
      <DatePickerInput

        {...datePickerInputProps}
        id="date-picker-input-id-2"
      />
    </DatePicker>
```

<img width="831" alt="screen shot 2018-06-12 at 1 38 39 pm" src="https://user-images.githubusercontent.com/11928039/41310032-f2302196-6e45-11e8-9361-b7ea361dba2d.png">



If you'd like to override the default `flatpickr` style, you can target `.flatpickr-day.disabled` via css

**Comment by zerostatic** [comment]
Sorry I missed that! Thanks so much for the explanation

**Comment by tw15egan** [comment]
No problem! I'm actually going to add in some enchanced disabled styles for those dates in the base repo, as it is pretty difficult to differentiate between the two. So keep an eye out for an update!
